== Chapter I

[.chapter-synopsis]
* From her birth to the 25th year of her age.

Martha Routh was born at Stourbridge, in Worcestershire, the 25th of the fourth month,
1743.
She was the youngest of ten children, four of whom died in their infancy;
and the rest were brought up by their parents, Henry and Jane Winter,
with religious care.
"`By keeping us,`" she observes in her narrative, "`in subjection to parental authority,
to do or leave undone what they thought best for us,
and by being careful not to let their affection sway their better judgment,
they very much prevented the necessity of correction,
which I do not remember to have been made use of.`"

The restraining hand of the religiously concerned parent, appears to have been,
in her own case,
early followed by the visitations of the Divine principle of grace and Truth in the mind.
"`I felt,`" she says, "`the convicting evidence thereof very early,
so as to cause me to stand still in the midst of play, to which I was much inclined;
yet I knew not what it was.
But as conviction followed, from time to time, I felt desires raised,
that I might be a better child, and become more steady and watchful.
I had impressive thoughts of a future state, and often when in bed at night,
felt troubled lest I might die before the morning.
At such times I was constrained to offer prayer, that I might '`stand in awe,
and sin not.`'`"

About the seventh year of her age, her understanding became more fully opened;
and then she could look back on her very infant days, knowing of a certainty,
that what she had experienced, was the work which Truth had operated in her soul;
and she felt a desire to cleave thereto.
"`Yet,`" she says, "`I too often forgot myself;
and although accounted by others a grave or sober child, I had to mourn in secret,
that a contrary disposition would often prevail;
of which I was more sensible than others, who might judge by my outward deportment.`"

This deep seriousness and tenderness of conscience in early childhood,
is not infrequently found described in the biography of religious characters;
and probably, in very many instances, more has passed unrecorded.
It yet may be thought by some persons unnatural, and by others be decried as enthusiasm.
Let such readers,
(if this work should meet with such,) be pleased
to suspend their judgment in this respect,
at least until it may appear,
what kind of fruit succeeded to those early buddings of piety.
For we shall hereafter find the subject of this memoir, dividing her time,
in conscientious obedience to the further manifestations of grace in her heart,
between the office of instructor of the youth in useful knowledge,
and that of minister of the gospel; in a society,
in which the liberty of prophesying being
maintained on the original apostolic foundation,
women are admitted, together with men, to the discharge of the Christian duty,
of speaking to the church, "`to edification, and exhortation, and comfort.`"
1 Cor. 14:3,6:4, 5.

The same serious cast of mind, which induced thoughtfulness on her own account,
appears to have led her frequently, about this time, to steal away from home,
when she saw a corpse carried along for interment,
and be present during the reading of what is termed the burial service.
On these occasions, she says: "`I attentively watched the lips of the priest,
and found from one time to another,
that he read the same testimony over all that were buried.
And though it seemed very grateful to the human mind,
to hear that all died in a sure and certain hope of a joyful resurrection;
the better part in me, was stirred up to inquire how it could be,
that all were in that state.

For by some knowledge and future inquiry respecting their manner of life,
I found that some of them were very different from such as I had read and heard of,
as having had hope in their death; as being of the righteous number, and of the just,
whose memory is blessed.

"`These circumstances took deep hold on my thoughts: I had to ponder them in my heart,
little thinking it would be like bread cast upon the waters, to return after many days.
For, as it now revives,
(having sometimes had to touch on the subject in gospel ministry,) I
think it would be as rational to admit of a purgatory fire,
as professedly to believe that the righteous and unrighteous are
companions in the general assembly and church of the First born.
Our blessed Lord says, John 5:28: '`The hour is coming,
in the which all that are in the graves shall hear his voice,
(the voice of the Son of God, v. 25.) and shall come forth;
they that have done good unto the resurrection of life; and they that have done evil,
unto the resurrection of damnation,`' Oh Christendom!
why are not your professed advocates for religion,
better skilled in the mystery of true godliness?
Were the tender scruples, arising in well disposed minds, enough cherished,
many might become wiser than their teachers,
in things appertaining to life and salvation.`"

Being placed at a day school,
where she had not much of the company of other Friends`' children, she found,
in this situation, an inducement to deviate from the simplicity of language,
inculcated by her parents at home; and she gave way, to a certain extent,
to the temptation.

Some time afterwards, two Friends in the ministry,
came to visit the families in that meeting; "`At which,`" she says, "`I greatly rejoiced,
though I did not expect to have been so found out and melted down under their ministry,
as proved to be the case.
After reminding us who were children, of the example of our parents,
how carefully we had been brought up, and the steady attention,
manifested in the discharge of their duty,
that we might act consistently with the principles of Truth; they said,
'`What a loss and pity it would be if any of us should deviate therefrom,
when out of the sight of our parents, in not using the plain language,
which I well knew was my own case.
I seemed like one broken to pieces, and could scarcely forbear weeping aloud.
As soon as I could get to my cousin Mary Bradley, who had learned to write before me;
I got her to write me a letter, which I dictated,
to a scholar to whom I was much attached,
expressing a hope that she would not be offended,
that I could not any longer give her the title of Miss,
but must call her by her proper name, as well as the other girls,
though I should love them no less but rather better,
because I knew it was acting contrary to the mind of my parents,
and the way in which Friends spoke to one another.

"`When I went to school again on second-day morning following,
it was under as much weightiness of spirit, as mind or body could well bear;
but going early, few were in the school,
and I took my seat close to that of my governess, whom I loved much.
When she came in, she spoke to me in her usual kind way, as did the other girls,
and took no notice of my change of language, or more serious deportment.`"

About her twelfth year,
her mother fell into a lingering illness which ultimately proved mortal.
She suffered much in her feelings on this occasion herself,
and the effects upon her spirits were apparent for several weeks afterwards.

Of this affectionate and tenderly beloved parent she relates as follows:
"`Sitting by my mother`'s bedside one evening, while my sisters were gone down to tea,
after dozing a little, she awoke, and asked me who was with her.
I went to her, and said it was I; when she embraced me with endeared affection, and said:
'`My dear child, I have been praying for you,
that the Almighty would graciously take you under his notice,
and preserve you in his fear,
that you may be made fit for an entrance into his holy kingdom; where He is,
in great mercy, preparing a place for me.`'
Expression would fail to set forth my feelings at that time.`"

She relates also the following anecdote of her mother:
"`The back part of our house looked into the yard of a large inn,
that was in great reputation, which Friends as well as others usually preferred.
The landlord and his wife were very kind neighbours to us;
the latter would often come and ask advice of my mother.
An officer of distinction happened to be taking up his quarters there;
one evening having got too much liquor, he began to quarrel with some of the company,
and after some time concluded to go into the yard to decide the fray.
The landlord was not at home, and the landlady seeing the officer draw his sword,
fainted: one of the servants exceedingly alarmed,
came to acquaint us with the circumstance, fearing murder might ensue.
My father was from home, but my mother quickly slipped out,
passed through those who surrounded the officer;
and as he was holding up his glittering sword,
took it out of his hand and brought it into our house.
The act so surprised him and the rest of the company, that they soon separated,
and the family thereby were greatly relieved.

In about two hours after, understanding who had got his weapon,
the officer sent a submissive request to have it returned;
but my mother told the servant, it was safely locked up in our parlour;
that she wished it to remain there till morning,
and would be glad the officer himself would then call for it, and put it into the sheath.
This he did, and very civilly acknowledged her kind interference.
Herein was the Scripture declaration fulfilled: "`The righteous are bold as a lion.`"

It appears from her narrative, that as early as her fourteenth year,
the mind of Martha Routh was awfully impressed, after many months of deep exercise,
with a sense of duty, under the divine requirings, to appear as a minister,
and tell to others what the Lord had done for her soul; but that giving way to fear,
and to an apprehension that it was impossible for her, at so early an age,
steadily to practice those things to which she might have to exhort others,
she lost ground through disobedience,
and began to be less thoughtful about her own state.
And as one wrong step, she observes, often makes way for another,
she began now to dislike the restrictions imposed upon her in dress,
and would have chosen such apparel as might not have discovered her to be a Friend;
from which, however, her father`'s firmness,
and the example and advice of her elder sister, were the means of restraining her.

She likewise got into the company of such young persons,
as she had not heretofore been allowed to associate with, and for whose society, indeed,
she had before no relish; concealing these improprieties,
under the pretext of visiting a relation who lived near.
"`Thus,`" she observes, "`in giving way to my own delusions,
I found the truth of the assertion, '`That evil communications corrupt good manners:`' yes,
worse, they lead into '`vanity and vexation of spirit.`'`" But it was not long, before,
through the influence of her friend Catherine Payton,
whose ministry had before been made of great service to her,
she was effectually checked in these wrong propensities.

The same Friend soon afterwards proposed to her father and sister,
that a situation should be sought for her, as teacher in a boarding school,
remarking that she apprehended there was something in her natural disposition, which,
with a little improvement in learning,
might render her useful in this laudable occupation; and that well-ordered schools,
according to her observations in her travels, were much wanted for Friends`' children.
This proposal being accepted by her father, she was in due time introduced,
in that capacity, to a Friend at Nottingham; with a prospect of succeeding,
in the course of two years, to the entire care of the school.

The account of herself, may now best proceed in her own words:
I was now turned of seventeen,
and my time was much employed in taking the care and oversight of the girls,
which was not an unpleasant employ; though there was a variety of dispositions.
Our governess +++[+++Anna Coulson]
was a well qualified person; and we loved her husband much,
his disposition being very pleasant.

He had lost his outward sight, yet he often heard us read,
and could readily observe the mistakes we made, and correct them.
He had also a precious gift in the ministry, and was to me,
like a tender spiritual father.

About this time I received the following letter from my dear father.

[.embedded-content-document.letter]
--

[.salutation]
My Dear Child,

This comes with a large salutation of my dear love to you.
I have also to inform you, that through the mercy of our God,
my health is pretty well restored; blessed be his holy name.
We are now got into another house, which suits us better than that we left: so my dear,
all things work together for good, to those that love and fear God.
My dear child, my mind is biased very near to you, hoping the Lord,
whom you has been taught to love and fear, from your youth even until now,
will preserve you, and keep you from falling;
which will be more joy to me than great riches;
so that if I should never see you more in this world,
I hope we shall meet in that which is to come, "`where the wicked cease from troubling,
and the weary are at rest.`"

So my dear, I rest in dear love to you, and remain your affectionate father, until death.

[.signed-section-signature]
Henry Winter.

--

The longer I was thus employed,
the more weighty and arduous the task appeared to enter into for life.
I had many secret thoughts and desires to resign the prospect of a public school,
and be a private tutoress in a Friend`'s family,
though I said nothing to either friend or relative on the subject.
Just at this time, my kind friend and caretaker, Catherine Payton,
being again at Nottingham in the course of her religious labours,
when conversing with her in her chamber on the subject, she tenderly expressed a hope,
that it would not discourage me from pursuing
the prospect of taking the school when resigned;
and that I might not think of accepting a situation as a private tutoress,
which would render my qualifications for a public station useless.
I told her, a situation in a private family, was what I had seemed to prefer for myself,
but was desirous of following best direction.

When I had been with Anna Coulson, from my first going, five years,
her worthy husband departed this life.
I was closely with him during his illness,
and took down the expressions that dropped from him,
which are printed in one of the volumes of [.book-title]#Dying Sayings#^
footnote:[[.book-title]#Piety Promoted in a Collection of the Dying Sayings of Many of the People Called Quakers: With a Brief Account of Some of Their Labors in the Gospel, and Sufferings for the Same.#]
His close was peaceful, and his removal a great loss to us all,
his company being very pleasant and instructive.

A few months before his death, a young woman from a distant county,
came with her mother to see two of her younger sisters, who were in the school,
and during their stay, took great notice of me;
she had accomplished a very liberal education,
and was as lively and sensible a young person as any I have met with.
After their return home, her mother wrote to inquire,
if she might be admitted into the school as a parlour boarder,
and have the opportunity of being in my company as much as circumstances would admit.
The proposal was joined in with, though I almost marvelled at her choice;
but was clearly instructed in my own mind, that through unmerited favour,
there was something to be observed of the gracious dealings of divine kindness,
which had stirred up and attracted the better part in her.

With this discovery, the watch word was clearly sounded in the ear of my understanding,
that I must not let go my hold, and be drawn aside by her vivacity and strong affection;
but be instrumental, in the divine hand, to draw her to greater stability,
which was mercifully granted; and the cement of our union became very strong,
through our frequently sitting alone in silence, to wait for a renewal of strength.

After some months had thus passed away, a person who called to see her,
reported to her parents the great alteration that appeared in her,
and that he thought her health might be endangered thereby.
This so alarmed her father, who was much better acquainted with the world,
and the love of money, than with the nature and power of religion operating on the mind,
that he soon came to see her, and would not be prevailed upon,
either by herself or others to leave her behind.
Her mother was a woman of steady and religious character,
but could not persuade her husband to let her return.

This separation was so wounding to nature and spirit,
that it seemed like dividing the joints and marrow;
for I exceedingly feared the consequence of her removal, yes,
more than a final separation, in the state she then was:
for she had informed me of an attachment to a young man,
who had greatly desired to have her in marriage; but her mother did not approve of it,
and they were both thankful she was removed from him.
But alas! alas! the golden bait prevailed! and her father
allowed her to be united to an unworthy character,
very unlike herself every way, though at that time a member of our Society.
The sorrowful tears that flowed from me on her account,
are only known to that penetrating eye, which sees in secret.
What cause of mourning it is, that all parents,
to whom the precious charge of children is committed,
are not careful to train them up in the nurture and admonition of the Lord,
coveting for them the best gifts;
desiring that their tender minds may be replenished with the dew of heaven,
rather than craving for them the fatness of the earth,
knowing that all things here perish with using!
I was then about twenty-four years of age; and in my twenty-fifth year,
Anna Coulson resigned the school.
I had mentioned to her, the prospect of having one of my sisters to join me therein,
which she seemed to object to, telling me the profits divided,
would answer but little end.
In reply I remarked,
that I had had opportunity of knowing the great propriety and
necessity of keeping a constant eye over the children,
not only during school hours, but on all other occasions;
and if for lack of that care and watchfulness,
evil should befall any of those committed to my charge,
it would be more cause of regret and concern,
than a double or treble profit could make up.
