== Chapter 2

[.chapter-synopsis]
* From opening a boarding School, to her marriage with Richard Routh.

My eldest sister being now married and a very precious one, next to her in age,
having been removed by death,
my sister Ann was willing to join me in the important concern of keeping a school.
She was a faithful helper, and took the whole charge of family affairs;
which she was particularly qualified for.
My employment was entirely the care and instruction of the children,
and we went on comfortably together.

Our beginnings were small, with regard to outward circumstances;
but we were favoured with contentment to move within compass; and, through divine favour,
nothing was lacking.
We got a suitable dwelling near the meetinghouse, which we found of great advantage;
and the school increased to our satisfaction.
We had no desire to have a large number, and about fourteen was as many as was convenient.
We had a steady religious servant; the children were also submissive,
and agreeable one with another.
Thus we got along for sometime.

About my twenty-sixth year, our dear and honoured father departed this life.
He had been an approved elder in the church many years;
and in the last religious meeting he attended, we were informed, he stood up,
and in a very solemn manner repeated the encouraging declaration:
"`Blessed are the dead which die in the Lord from henceforth: yes, says the Spirit,
that they may rest from their labours: and their works do follow them.`"
This, there was no cause to doubt, was his own blessed experience;
and though at a distance from him,
yet my nature suffered deeply when I heard of the change.

It was not long before another deep and weighty exercise, the work of the ministry,
was again set before me.
The necessary preparation and restrictions, were clearly presented;
when I experienced in deed and in truth, that "`straight is the gate,
and narrow the way that leads to life;`" and found I
was still unwilling to enter it on those terms;
though anything short thereof, I thought I could be resigned to,
even to be clothed in sack-cloth, if it was required.

But this was not the sacrifice called for,
though I had some alterations to make in my outward appearance,
which as none had ever hinted the least inconsistency of, I felt a great struggle about;
and let in such arguments, as to conceive it must be a delusion;
yet as I had lost my peace by gainsaying,
I concluded I would do what I once saw to be right; and in great self-abasement,
I made the alteration in my clothing, giving up all that seemed called for.
Then, in adorable mercy and lovingkindness, light again sprung up, and my darkness;
became as the noon-day; that my soul knew right well,
the divine hand of power was underneath, opening the pathway for obedience,
in what many esteem the "`little things,`" scarcely worth their notice.
I likewise found it my place, to have all those who were put under my care,
consistent in their apparel, so as to admit of no superfluity;
and was never opposed by any parent on that account.

My heavenly Director saw fit to carry on his own work, and to lead me gently forward;
though I went heavily on my way; finding, at times,
the exercise of my mind to be so great,
that I seemed disqualified for the usual and proper attention to the children;
but when school hours were over, I retired alone, and poured out my soul in secret,
with many tears, that my Almighty helper would be pleased to show me, with clearness,
what I should do and what I should leave undone.
I greatly desired to move forward in the obedience of faith,
consistently with his divine will.

The dear children were often aware of my exercise;
and I was sensible that their tender minds felt sympathy with me.
The spirit of prophecy was given both to servants and to handmaids:
those who came from far, as well as those who were near,
clearly pointed out my state in public ministry; and some of them told me afterwards,
they could have laid their hands on my head;
but I kept as close as was possible from any discovery on my part,
till my health became so impaired, that I was scarcely able to stand;
and at length I was confined to my chamber and bed;
a skillful physician having done his utmost for me to little purpose,
and those who kindly watched with me in the night season,
thought I could not continue long.

One night my sister sat up with me, and seeing her bathed in tears,
I asked her why she was so sorrowful.
She replied, "`How can I be otherwise, when I am likely to lose you, and be left alone.`"
Her tried state so much affected me,
as to cause me to make some disclosure for the first time of my own; I then said to her:
"`My dear sister! my sickness is not designed by the great Physician of value,
for the death of the body; if that would have been accepted as a peace offering,
thankfully could I have resigned it: but resignation of will, to the Divine will,
in a way more trying to my nature, is what is required,
and what I have been struggling under, till I am brought thus low.`"

Her tender solicitude was such as might have been expected to be felt by one,
so nearly interested in my welfare every way.
She said, she had been fully aware, with many others of my friends,
of the deep exercise I had long been under; but as I had never opened the subject to her,
she was backward and fearful of mentioning her thoughts to me.

I told her, I had gone several times to our valued friend John Storer,
when I seemed as under the weight of the mountains, to have opened my state,
and have got a little relief; but though I mostly found him alone,
I could not utter a word; which made me think,
it was best to have my lips sealed with silence, as long as I could endure it.
I greatly desired her supplication, with that of my nearly concerned friends,
for my preservation and help,
when they might be favoured to draw near the throne of grace.
And feeling relieved in my spirit, after this opportunity, I was better in the morning;
with my sisters help sat up a little in my bed; and in a few days left it,
though so weak I could not stand alone.
Having afresh entered into covenant, with a covenant keeping God, willing,
through his divine help, to do what he required of me; my recovery became speedy,
beyond all expectation.
How rejoiced were our dear children, and many others thereat,
which greatly humbled my mind!
We had now kept the school nearly three years,
and most of the children had nearly finished their education;
that I secretly but fervently prayed, if the time was nigh at hand,
when I must yield obedience to the divine will,
in becoming a public advocate for the cause of righteousness,
my compassionate Father would be graciously pleased so to order,
that no new scholars might offer,
until I became fully satisfied with his designs concerning me; for, indeed,
the weight thereof seemed at times more than I was well able to bear.

The time of the yearly meeting in London coming on, my sister and myself attended it,
having several of our scholars who came from that city to take home.
A few weeks previous to our going, that worthy Seer in Israel, William Hunt,
from North Carolina, with his companion Thomas Thornborough, were at our meeting,
accompanied by Joseph Row and his wife, from London.
William seemed both in public and private,
as though he was led to "`search`" me "`with candles;`" and attached himself to me,
in so fatherly and affectionate a manner, that dear Joseph Row and his wife,
tenderly entreated me to go along with them, they travelling in a post-chaise.
I did not lack a will to go, yet was afraid lest any thing should fall out by the way,
in regard to public exposure;
but after setting forward I was favoured with quietness and consolation,
accompanying them to Mansfield, Chesterfield, and Sheffield.

When taking leave of my aforesaid dear friends, who had manifested a most tender regard,
William said in a very emphatic manner: "`Dear child,
my love is with you in the light and in the truth of our God:
therein I dearly salute you, and bid you farewell!`"
I felt exceedingly contrited, but so far strengthened,
that if I had had the wings of a dove, I should soon have fled home,
having no wish to be seen by any.

When the time came for setting out for London,
the three girls who were to return to school,
went to their respective homes during our absence.
We met with a very kind reception from the parents of the children we took with us,
and from many other Friends.
Many times did the current of ministry so flow towards me, in an encouraging manner,
that my soul at times seemed melted within me; and I think through no instrument,
more evidently pointed, or with more consolation, than through that worthy handmaid,
Frances Dodshon.
How had she to proclaim as on the house-top, the secret sentiments of my heart,
in offering up for sacrifice, all but the one thing required! but, in this,
"`I pray you have me excused.`"
She was till then, an entire stranger to me,
but afterwards became a near and intimate friend.

After our return home, we were a quiet little family,
having only the three boarders before mentioned for nearly a year,
during which time our kind friends were thoughtful in
regard to our outward circumstances;
and lest we should be discouraged, on account of the school being so small,
several kindly offered to make up our loss:
but I was not free to accept any thing of the kind, knowing on what ground I stood;
yet I had not liberty to tell any one but my sister,
that I had craved the release for a season;
and requested she would not mention it to others.
So I had to bear the imputation of some for a time,
that I was not humble enough to accept a free will offering,
which was by no means the case; and in due season they were satisfied of the contrary.

Our justly valued friends Mary Ridgway and Jane Watson, being at Nottingham,
in their way from the yearly meeting, both, but especially Mary,
were so evidently led to open my state, and administer to it,
that I was afraid all in the meeting would know who was meant.

I think this proved the breaking up of my controversy;
for I was so brought down and humbled, in deep self-abasement,
that when I got into my lodging-room, I was constrained to fall on my knees,
and to offer vocally the resignation of my will, to the will of my Heavenly Father:
that if He would be with me in the way I should go, and send me to "`say to the north,
give up,`" and to "`the south, keep not back,`" I would obey his holy commands.

Soon after this offering, my bonds were broken, in the ninth month,
and twenty-ninth year of my age, in our first-day morning meeting;
though as little expected by me, at that time, as at any preceding one.
After resignation took place, I scarcely knew how I was raised from my seat to say:
"`Keep your foot, when you go into the house of the Lord; and be more willing to hear,
than to offer the sacrifice of fools.`"
I concluded this was on account of a man of a ranting spirit, who had been disowned,
and used to disturb meetings so as often to be carried out:
but he kept quiet at that time, which I trust was generally felt to be a solemn season.
I was thankful I had been thus far helped to do what appeared right;
it was to myself a solemn day throughout, and also to our little family.

During the seasons of deep probation, from the fourteenth year of my age,
to the present time, I had much cause to sympathize with the poor Israelites,
in their wilderness travel, and to exercise more charity than I had done aforetime,
in reading their manifold back-slidings from the divine commands; on which account,
they had to go backwards and forwards, and long to encompass the mountain;
until the compassionate eye beheld them, with his wonted kindness,
and opened the way for their entrance into the promised land.
I think I never murmured, or thought any of the dispensations of unerring wisdom hard,
neither any of his sayings such as could not be complied with,
but through my own default; so in mercy he did not slay me,
but permitted life to be given for a prey, I was soon again and again called upon,
to bear further testimony to the divine requirings, but the reluctance was yet so great,
that I was plunged into unutterable distress; and our quarterly meeting drawing near,
for the joint counties of Derbyshire and Nottinghamshire, to be held at Mansfield,
I exceedingly dreaded to go, yet dared not stay away.
It was fourteen miles from Nottingham, a forest road most of the way.
My sister, myself, and our three scholars, set out early, in order to reach in due season.
When within three miles of the town,
how did I long to have been left among the trees of the forest,
there to have received the echo of my plaintive cry!
I should have feared no danger to the body,
had I remained there till my companions returned; but I went forward,
and as soon as we alighted at the inn, retired to a chamber alone.
The members of the select meeting being there the evening before,
two of them soon came to me, offering as much sympathy as they were capable of,
but I was not in a state to be comforted.

I went to meeting, which soon felt a gathering of great solemnity;
and my wounded spirit felt a little healed thereby.
Our friend John Storer, stood up, and in a very weighty manner,
opened his gospel mission, with an invitation to those who were afar off to draw near,
and those that were near, to acknowledge the Lord`'s might; which he enlarged on,
in a powerful and encouraging manner; by which I was again so far divinely quickened,
as to promise obedience if called for in the women`'s meeting,
if I might only be permitted to keep silence in that for worship.
I retired a little alone after the first meeting broke up,
and thought my state must somewhat resemble Jonah`'s,
when he was under the weight of the mountains, the weeds wrapped about his head,
and thought the earth with her bars was about him forever.
I went up stairs in much fear and trembling.
The meeting was for sometime very silent, when, a sentence or two powerfully arising,
I stood up and expressed them, so that I believed the whole meeting could fully hear,
and then remained through the business in peaceful quiet.
When meeting was over, and I had returned to the inn, I was glad to lie on the bed,
till our family were ready to return;
thankful that I was then able to join them in the carriage.
Oh my soul! can you cease to remember your misery and your affliction,
"`the worm-wood and the gall,`" and not be humbled, under a grateful sense,
that it was of the divine mercy you were not consumed!
I moved along in great weakness and fear, according to my own apprehension,
for many months; seldom a meeting day came,
but my bodily frame was affected at the thoughts of going.

Our ancient friend Sarah Beck, being at Nottingham about this time,
and having no companion, I was encouraged by Friends to go with her a few days;
and I found her a tender nursing mother.
After parting with her, my valued friend John Burgess,
accompanied me back to a country meeting, about five miles from Nottingham,
which was kept up once a quarter, where several Friends from there met us.
As we rode along, one in the station of an elder remarked,
that she thought it was as good for spiritual children to breathe fresh air,
as for those who wanted to recruit bodily health:
and then inquired if in the little turn I had taken, I had heard of any more scholars?
I said no, but I then thought it would not be long before I should: and the next day,
a letter came from a Friend of Bridgewater,
to inquire if we could take two of his daughters.

In a short time, so many offered that the house was quite full;
and an addition to our number still presenting,
Friends were desirous we should take a larger house.
I did not feel liberty to comply with their desire: yet in condescension to it,
wished my sister to go, and look at one that was thought eligible,
and the rent reasonable, both which she found to be the case.
In compliance with the wish of my friend Hannah Storer, I afterwards went;
but as I passed from room to room, was attended with a secret, but clear intimation,
that I was not to entangle myself with a greater number of scholars,
than the house we already had would accommodate; so I entirely gave up the thought,
and felt peace.

I was glad our occupation was of such a kind,
that we could lock up doors and attend religious meetings diligently,
when favoured with health, which was in general mercifully granted;
and being near the meeting-house was a great convenience; yet one afternoon,
from a heavy fall of snow, we left several of the younger girls at home by themselves;
for our servant being a religious woman, attended with us.
While sitting in meeting, I got thoughtful lest any hurt should befall them,
accompanied with an intimation,
that it was best to accustom children to endure a little hardness,
and to impress their minds with the sentiment, that to attend religious meetings,
was worth encountering some difficulties for; that many offender age,
when their parents were cast into prison, and the meeting-houses shut up, had,
with other Friends, met out of doors, and some had been taken to prison,
I believed it right in the evening, to revive these hints among the children,
which had a contriting effect on their tender minds.

In the winter season, it was our practice to have them all gathered in the evening,
and for one or two to read to the rest, alter a little space of silence;
their needle-work being of such a nature as not to interrupt the solemnity:
sometimes one kind Friend or other would come and sit among us,
acknowledging it was like being in a little evening meeting.

Thus we were enabled to go forward,
because the good hand of our Heavenly Father was near us; and He inclined my heart,
by day and by night, to supplicate for his blessing on the children; evidently feeling,
that no arts, parts, or acquirements of mine, were sufficient to discharge the duty,
or fulfill the trust reposed in me:
and being thus engaged to seek after divine assistance,
I do not remember that any dissatisfaction was manifested, either in parents or children.

About a year after my first appearance in public ministry,
the Friends of our monthly meeting, united in receiving me as an approved minister,
of which an elder was desired to inform me,
and to request my attendance at the next select meeting.
This request I was not forward to comply with,
for I still feared how I might stand my ground.

Soon after this, I received a few lines from my friend John Burgess,
informing me that Mary Malham, (now Mary Proud), who was on a religious visit,
was coming our way, and so on to Lincolnshire,
and would be glad if I would accompany her through that county.
This brought me under exercise, both on account of leaving the school,
and the little time allowed for consulting my friends on the subject;
but my dear sister encouraged me to do both, which I did,
and had the approbation of the latter: yet there was something still, in my own mind,
that was not forward to close in with the proposal,
for I was afraid my own inexperience might give way to the affectionate part:
so that although I knew she was come into town, and lodged at a Friend`'s house,
whose door was alway open to me, I did not go to see her that night.
The next day attending our meeting, I was so fully satisfied, that I no longer hesitated.
We travelled with great diligence, mostly taking two meetings each day;
and got in time to attend our quarterly meeting at Chesterfield.
From there she went to York, and I returned home.

Some months after, I felt an impression to attend the quarterly meeting at York,
which my friends uniting with,
I was accompanied by a kind female Friend in the station of an elder.

We got to York in time for the select meeting, but I had not courage to attend it:
and when entering the great meeting-house, the next morning,
I scarcely knew how I got towards the gallery; for though the gathering was very large,
I saw no person, except the skirts of those who sat near me, until in awfulness,
I had bowed the knee in supplication.
I was then favoured to feel a peaceful quiet;
thankful to hear the gospel preached by those of greater experience.
After meeting, several Friends noticed me very kindly, none more so,
than my valued friend Esther Tuke.
Our further knowledge of and union with each other became very strong,
even like "`a threefold cord.`"

When the meetings were over, my dear companion and self returned home,
taking the meeting at Sheffield in our way, on first-day following;
where Friends received us with great kindness.

Being now apprehensive that resignation of this kind, might continue to be called for,
I thought it best to seek out for a steady qualified helper in my school,
and found such a one in my cousin Ann Lowe, of Worcester.

I often visited my dear and much tried friend, Ruth Fallows of Castle Donnington,
and sometimes accompanied her to a few neighbouring meetings.
She was a true living gospel minister, and her company was helpful, encouraging,
and edifying.
She told me of a prospect she had of religious duty,
to visit some of the northern counties, and Scotland; to which I made no other remark,
than the expression of a full belief,
that the same divine hand which had been her support in all her trials, travails,
and exercises, would still be with her.

Some time after this conversation,
my own mind was impressed with a prospect of visiting the meetings of Nottinghamshire,
Derbyshire, and some parts of Lancashire.
While this was under my notice, though not mentioned to any,
dear Ruth Fallows came to Nottingham, and being at our house, remarked,
she was not gone the journey she had told me of.
I said: "`No, though I expected you would, yet I don`'t want to part with you.`"

She replied: "`I don`'t know what I am waiting for,
except it be for you to go along with me; and if so, I am willing to wait still longer;
so be honest, and let me know your thoughts.`"
I then opened to her my prospect of the before-mentioned counties, but thought,
if my friends should set me at liberty,
it would be proper to inform the parents of the children,
as my absence would be for a longer period than at any time before: which I did,
and received their cordial approbation, and from some the expression of near sympathy.

Way being thus opened, I laid my concern before friends of our monthly meeting,
who gave me a certificate, the first I had had of the kind;
and after carefully endeavouring to put all things in order,
relative to the children and family affairs, and my dear sister being willing,
as she always was, to give me up to the pointings of duty,
we took a solemn and heart tendering leave of each other.

We had many long days`' journeys, and! often felt much fatigued;
my bodily frame not being yet strong, and my appetite poor,
that I could not take much food: but the season of the year being favourable,
through divine favour, we got as speedily along,
as most who had travelled the like journey.
We had much cause gratefully and humbly to acknowledge,
that mercy and kindness had been with us, who went to the battle,
and with those who stayed by the stuff; for on my safe return, I found my family well,
to our mutual rejoicing: as did my worthy companion her kind husband.

On the 7th of the eighth month, 1776, Martha Winter was married, at Nottingham,
to Richard Routh, of Manchester; and removed to his residence in that town.
Her Journal proceeds in the next chapter.
