== Chapter IV.

[.chapter-synopsis]
* Goes to America
* Incidents on the voyage.

For several years previous to her last journey, Martha Routh had had a prospect,
that it might become her religious duty,
to visit the meetings of Friends in North America;
under which exercise she was strengthened,
by the concurrent sense and sympathy of some experienced Friends;
of whom she particularly mentions John Storer, of Nottingham, and Job Scott,
from North America, who respectively spoke encouragingly to her on this subject,
before she herself had made known her concern.

This having at length been spread before her friends,
at her monthly and quarterly meetings,
and lastly at the yearly meeting of ministers and elders in 1794,
she obtained their near sympathy and concurrence,
and was provided with certificates accordingly.

She embarked at London, in the ship Barclay, bound for Boston, New England,
the 21st of seventh month, having for fellow-passengers, John Wigham, from Scotland,
who was proceeding on a similar religious visit to America, and Samuel Emlen,
returning from one he had been performing to Friends in England; also William Rotch,
his wife and two daughters, with other Friends to the number of fourteen in all.
The voyage, through contrary winds proved tedious, and they met with much rough weather;
yet were enabled frequently to hold religious meetings on board,
to which many of the ship`'s company and passengers came.
The following incidents and remarks occur in the course of this voyage.

[.small-break]
'''

We continued at Deal on sixth-day, the wind being against us, the sea rough,
and sickness continuing; but towards evening it got more calm.
I slept comfortably that night, and waking pretty early in the morning,
felt much refreshed both in body and mind.
I was humbled and contrited to silent weeping, in my little but commodious lodging room,
under a fresh sense of the bountiful dealings of Infinite Wisdom towards me,
even from my childish years! great was the love renewed in my heart,
towards my fellow passengers; and in a particular manner to William Rotch,
who for some years, has been to me a brother beloved in the unchangeable Truth;
and as our friendship did not commence on the surface of things,
but in a heartfelt cement, from which flowed a language, as when deep utters unto deep;
so it has continued gaining ground, on that rock which cannot be shaken,
against which the gates of hell shall not be able to
prevail and under this uniting impression,
a trust was renewed that our heavenly Pilot would, in his own time,
land us safely at the desired port; for which fresh mark of divine regard,
my soul desired to render the tribute of praise to our God, who is worthy forever.

28th of seventh month.
About two o`'clock on first-day morning, I heard the captain call to his men,
that the wind was got more in our favour.
They were quickly upon deck, weighed anchor, and set sail; but it blowing hard,
and not quite fair for us, we had a tossing time, till we anchored again at Dungeness,
when we retired quietly together in our cabin, in the latter part of the afternoon;
though on sitting down, I felt very feeble both in body and mind.
The latter became a little helped through the impression of a belief raised therein,
that many brethren and sisters, from whom we were separated in body,
had been caring for us, and breathing on our behalf, both in public and private,
to the great Preserver of men, which felt humbling, accompanied with secret desires,
that I might be watchful over myself, and spreading towards, others,
I had liberty though in weakness to make some mention of it,
which was followed with an instructive addition from dear Samuel Emlen.

In the evening we sat together again, and several of our young men read to us; when,
after a pause, dear John Wigham had to revive a passage that had been read:
"`It is not in man that walks to direct his own steps,
etc.,`" from which he was led to drop several instructive remarks,
in a particular manner addressed to the young men.
He was followed by Samuel Emlen, in tender emphatical expostulation;
and I believe our minds according to our measures, were bowed in thankfulness,
through the renewings of the Lord`'s power, for being thus owned by Him, who,
in former years, ordained a morning oblation, and an evening sacrifice.

3rd of eighth month, first-day.--About noon the wind became more still,
and gave us an opportunity of sitting down quietly together;
and through the renewings of our heavenly Father`'s love,
it was rendered a contriting season.

As I lay in bed, I had been tenderly looking towards my dear friends at home,
gathered in our own meeting,
not without some apprehension that their minds might be turned towards us;
and my heart seemed to salute Zion`'s travellers,
secretly breathing to the God and Father of all our mercies, that they with us,
and we with them, might witness the continuation of preservation;
which desires I have no doubt are acceptable to Him,
who is the blessed author of all good, and who, in unspeakable lovingkindness,
has been near to sustain my mind, when outward strength and health seemed much to fail.
I have thought the reduction of bodily powers, under suffering,
is not without instruction,
for it leads into a disposition to try the foundation we are upon,
and to appreciate the blessing of knowing there is One that stands sure, having,
in the language of Scripture, "`This seal,
the Lord knows them that are his;`" and if this evidence is mercifully vouchsafed to me,
through the course of the passage, however attended with bodily trial,
I humbly trust my soul will be enabled to say, it is enough.

We have two captains on board who mess in the cabin, and appear quiet, steady men,
setting a good example to the mariners,
from whom I have not heard of any unbecoming conduct or expressions proceeding,
which I think well worthy of the observation of those,
exercised in the like trying occupation.
Our steward or cook, is a black man named Quares Bailey.
He was brought from Guinea, and sold as a slave,
to the person from whom he received his latter name.
His bonds were broken through the interest of W.
R+++.+++ He is a man of distinguished quietude,
and readiness to oblige all in his power.
We have live stock, sheep, goats, pigs, geese, ducks and fowls.
Several of the latter have died, and others appear sickly, and do not thrive;
that these poor animals seem to have their portion of suffering as well as we,
which induces me to think, if I was master of a vessel, I would not bring many.

On fifth-day morning,
several went out of the cabin to see the mast of a French man-of-war floating near us,
the account of which made my heart sad, in considering,
that probably many of our fellow creatures had sunk with the wreck of the vessel:
and how entirely repugnant the ground work of such desolation is,
to the nature of His kingdom, who came not to destroy men`'s lives, but to save them;
that I got an attendant to read me that most excellent of all sermons,
preached by our blessed Lord on the mount.
His doctrine astonished those who heard him;
setting forth the nature of that peaceable government he was about to set up;
but how few of the sons of men have been willing to understand his counsel,
or follow his example, who, "`when he was reviled, reviled not again,
and who was led as a sheep to the slaughter, or as a lamb dumb before his shearers,
opened not his mouth.`"
But ah! how widely different are the actions of many
who profess the Christian name in the present day,
who are destroying one another by every engine and artifice, that fallen nature,
through the suggestions of the enemy of souls, can invent for their destruction.

Third-day, the 12th.--Sitting alone near dark in my little cabin,
dear Samuel Emlen came down from walking the deck,
and had to dispense in the renewing of life, the language of encouragement among us;
like a well instructed scribe from the heavenly treasury,
bringing forth things new and old, which drew me forth out of my closet to hear,
and participate in the feeling of it.

The early part of fourth-day morning,
the wind freshened and we went about six knots an hour,
the vessel keeping a moderate motion, that I have nothing to complain of,
either in body or mind, though the latter has felt more secretly pressed down,
than at some other times; yet I trust not forsaken;
for I have felt united to the few who are diligent in
the attendance of our week-day meetings,
who I have seemed to look at, scattered in their respective seats;
and desires have been raised,
that none should be discouraged or drawn aside from meeting together,
when bodily health is afforded, bringing a sacrifice of that which costs them something;
yet how little do we render to God of that which is his due,
in the most diligent attendance of our meetings both on first and week days?
I trust a remnant know this, and are engaged to offer a daily sacrifice.

I have often looked towards my valued fellow-labourer, John Thorp,
in the bond of the gospel in our own meeting,
in that fellowship which has united our spirits in worship,
and raised desires that the Lord on high might strengthen his little ones, on whom,
we had cause to believe, his anointing oil was poured forth,
that they might offer to Him the turtle doves, or young pigeons,
as He might see fit to call for them;
similar to the disposition cherished in that dignified
but meek and humble leader of the tribes in days of old,
who said: "`Would God that all the Lord`'s people were prophets,`" etc.

Second-day, 18th.--This evening the vessel continued much in motion,
and remained so till towards morning, when the wind changed; and for a short time,
we went nearly eight miles an hour.
The tossing of the night and little sleep made me feel very languid.
My mind also was much proved, though not with fear of our safe landing;
but under a renewed searching of heart, respecting the embassy I was going upon;
and much solicitude was raised in me, that I might so experience preservation,
as to bring no dishonour to the cause.
Being thus humbled, my feelings were relieved by such an effusion of tears,
as I have not often shed; and I remembered, to some instruction and profit,
the interesting farewell salutation of a beloved friend and younger sister:
"`Let your Urim and your Thummim be with the holy one of Israel,
and all your needs will be made known unto Him,`" etc.
In a little time I seemed refreshed both in body and mind,
and evidently felt in this proving season, the help of the spirits of fellow travellers,
to whom I am nearly united in our present allotment together;
so that I found I had much to be thankful for.

On sixth-day morning, 29th, when about to rise,
our quietude was interrupted by information, that a ship, about three miles to windward,
had made a signal of distress; and on its nearer approach,
appeared to have lost part of the mainmast.
Our captain laid to, in order to let her come up with us,
with the humane intention of rendering assistance,
which disposition I could not but commend, when men are at peace one with another;
but at a time like this,
I thought it required great clearness of judgment to know what was best to be done;
and the little I felt, was entirely against stopping to aid that vessel:
as it was possible that not only such appearance, and the signal that was given,
but much more, might be done treacherously to decoy.
When the captain perceived it was a ship of war with two tier of guns,
he hoisted sail to make the best of his way,
and their conduct did not wear a kind aspect, for they fired after us four times;
twice the balls came so near, as to be heard whistling along the water.

Though in feeling the attention of my mind drawn inward,
I was somewhat renewedly strengthened and consoled in a hope,
that no material harm would be permitted to reach us; yet it was a great trial of faith,
etc., and some I tenderly loved, seemed to feel it so much, that all within me was moved;
and my soul bowed in supplication to our alone Almighty helper,
in like manner as when I was engaged in the congregation of his people,
in the last meeting I sat in London,
that we might be preserved out of the hands of unreasonable men,
which favour is still mercifully granted; for after our sails were set,
we had a fresh breeze, and they seeing we outsailed them,
though not more than a mile distant, tacked about towards England and left us;
for which I believe feeling minds were humbled in thankfulness.
In a little time we were quite becalmed,
and had that been permitted at the critical juncture, they might have come up with us,
for they were not then out of sight.

31st,
first-day.--In the morning about ten o`'clock we quietly sat down together as heretofore,
and had cause humbly to acknowledge that our Heavenly Father owned us,
by the breaking of bread, and the opening of counsel through his servants,
to the states of those present.

Dear John Wigham, in a particular manner,
has been rendered an instrument of instructive labour to the seamen.
We had also another meeting in the evening; and as we have a hope,
that the latter part of our voyage may be attended with
less hindrance to quietude from contrary winds,
our meeting together on fourth-day morning was then proposed.

Fifth-day.--We have felt a remarkable change in the air these few days,
the weather being much colder, and the water a different colour.
This evening we saw a large island of ice about a mile off,
supposed to be brought from Davis`'s strait.

Sixth-day.--On the grand bank of Newfoundland.
The captain sounded, found forty fathoms water; about seven lay to,
and put out fishing lines, but did not catch anything.
Saw the Good Intent from Dartmouth, in Nova Scotia,
one of the mates and some of the men being desirous to go to her, put out the boat,
not without some reluctance on the part of our friend, W. Rotch,
who was very anxious lest they should come to any damage.
I was glad when they got safe back, for the boat seemed at times so covered by the waves,
that I scarcely dared look at it.
They took a present of rum and porter, and brought back thirty-five codfish;
some supposed to weigh fifteen pounds.

Sixth-day, 12th.--The weather very fine, sea calm.
I can scarcely regret our slow motion, which is so salutary to my bodily feelings.
In the evening I went again on deck,
and stood on the hen-coop to view the solemnity of the sky.
The moon was risen; the stars were also beautifully bright; and the sea so smooth,
that the captain thought he could go safely on a plank;
such are the changes in this vast and wonderful element!

Fourth-day, 17th.--The weather still fine, the wind favourable, going smoothly along.
We held our week-day meeting,
which some of us were ready to apprehend might be the closing one of a public kind;
we had cause humbly to acknowledge it was a favoured season, graciously owned by Him,
who is a God hearing prayer,
to whom solemn supplication was made by our valued brother J. Wigham,
for the continuation of the blessing of preservation unto us.

They were preserved from any serious accident until very near the port of Boston;
where the captain`'s brother, acting as a seaman on board,
went up to reef the sails of the main-topmast,
and falling from there into the boat on deck, was killed on the spot.
This accident cast an impression of sadness over an arrival,
in other respects most acceptable to the company;
and their tender sympathy with the captain was called forth,
in due attention to his feelings, in a parting religious opportunity with the sailors,
and in the attendance of the burial of the deceased,
by the men Friends who were passengers.

Our friend landed the 23rd of the ninth month,
from which period her narrative proceeds in the next chapter.
