== Chapter V.

Her labours during the remainder of the year 1794 and part of 1795.

On fifth-day, the 25th of ninth month, I attended the week-day meeting at Boston,
in company with my valued brethren Samuel Emlen and John Wigham,
and my dear friends William Rotch and family, etc.
On our sitting down my mind was much contrited,
under a renewed sense of the protection of Divine Providence,
who had seen fit to favour us to assemble together, at the desired port;
when the testimony of the apostle was feelingly illustrated in my view:
"`That peace which surpasses the understanding
of man;`" of which I had to make some mention,
and a little to point out, who were likely to partake of this peace,
and what were their trials, etc.
My aforesaid brethren bore living testimonies to the sufficiency of the Lord's power,
to make us what He would have us to be;
and the meeting ended in supplication for the continuance of His care,
over those He called forth in his work.

My mind still felt much weight and exercise,
respecting the families that professed with us;
and my dear friends W. and E. Rotch were willing to stop with me,
till I felt liberty to go.

We staid till third-day, which gave time to sit with the families accordingly;
to mourn over the desolation which seems so general,
that when a few who have kept their places, may be removed from works to rewards,
it looks likely our Society will become extinct in that city;
unless it should please Him, who sends forth his servants to the highways and hedges,
when those that are bidden will not come to the supper, to call in others.
Amongst such, there seemed great openness, and I cannot but think,
if the few had all kept their places, there might have been here a gathering.

On first-day morning, I had opportunity to clear myself,
in a close expostulating testimony towards Friends.
The afternoon meeting being put off till six o'clock,
was largely attended by those not of our Society,
so that a great number could not get into the house.
This for some time prevented that quiet, which on all such occasions is desirable;
yet as my mind was preserved in stillness, I was so far strengthened to labour,
as to encourage a hope, that the precious cause did not suffer.
I felt a peaceful release to depart with my friends W. and E. Rotch and their son,
who met us there, and went to Bedford; getting well there on fourth-day evening.

A few miles before we reached the town, a silent solemn covering spread over us,
under which I believe our hearts were mutually comforted,
in a grateful tribute to our Almighty Helper,
in that my beloved friends were so near being restored to their dear connexions;
on whose account I had often felt greater solicitude than for myself,
during our watery passage and now I was made in some
measure to partake in their humble rejoicing.

The next day was the select meeting for the quarterly meeting, to be held there,
which felt to me rather a low, trying season;
yet my mind seemed peacefully sustained in quiet poverty.

I was most easy to confer with my valued friends W. and E. Rotch alone,
to propose and have their consent for their daughter L.'s accompanying me;
on which account I was not, void of near sympathetic feelings,
in so soon taking her from her justly beloved connections;
all which her parents endeavoured to remove, and, through their love to the cause,
and near sympathy with me, freely gave her up,
believing she would also give up to what was thought best for her;
and her father wrote to her on the subject to Nantucket,
where she and her sister Mary were gone.

Next morning at Bedford, I was favoured with inward quiet,
but little opening for public labour, till near the close,
when I thought it safe to express the plaintive language,
that had been much the attendant on my mind: "`They have taken away my Lord,
and I know not where they have laid him;`" which in a spiritual sense,
appeared to be the language of Zion's travellers.
A few remarks were given me to add, to encourage the labour of such,
that the exercise might not be let go; for I had to believe, that, in the appointed time,
the joyful tidings would be heard: "`He is risen from the dead, and goes before you,
etc.`"
I continued there over first-day, waiting L. R.'s arrival from Nantucket,
which the wind did not favour, till second-day evening;
when she came with John Wigham and David Sands, a Friend from the state of New York,
bound for England on gospel labour, and who was taking leave of Friends of this part.

14th of tenth month, 1794.--On third-day morning,
after a precious humbling opportunity with them, and the near relations of my companion,
under the melting influence of gospel love, we took leave of each other;
and were accompanied by to Salem, about eighty miles, and sat their week-day meeting.
In the evening he returned home.
Parting with him proved a fresh trial; but being provided with a suitable carriage,
and a Friend who had been eastward before,
we set forward on sixth-day morning in company with several Friends.

On first-day morning, we went to their meeting at Hailstown,
which was largely attended by Friends and others,
amongst whom I had to labour in the discharge of duty; but not feeling quite clear,
and the people living too distant to meet again that day,
another meeting was appointed at eleven on second-day morning,
which was also fully attended, and proved an open, satisfactory opportunity,
particularly towards those not professing with us.
My mind still felt heavily laden respecting Friends,
whom I requested to stop till others had withdrawn; when,
through the renewings of best help,
I was enabled to leave the burden with them in much plain counsel, as my way opened,
and thought I felt quite clear of all ranks; but going home with a friend to dine,
as I entered under the roof, my mind became again secretly and painfully exercised;
and I found I had something more to do.
Being desirous to stand in resignation, I requested the family might be brought together,
and endeavoured faithfully to impart such counsel as Truth opened;
for which I felt the reward of peace.

Third-day morning.--Soon after breakfast we set off for Pittsfield, about thirty miles,
which took ten hours diligent riding;
so that it was dark some time before we got to our lodging place, though, through favour,
without accident.

We there met very agreeably and unexpectedly with Joshua Evans,
a Friend from near Philadelphia, on a religious visit to Friends of these parts,
accompanied by T. R., brother to my companion,
and they not having seen each other for more than four years,
I was thankful our way was ordered for them to meet.
Friends being largely collected, with several not of our Society next morning,
I thought I evidently felt the travail of their spirits to help mine,
and I was enabled to discharge my duty, both in what appeared the greater,
and lesser matters, that concern our exemplary walking,
consistently with the Truth we profess.
We staid the rest of the evening together, in the course of which,
remarks were dropped to one another's help.

Early on fifth-day morning we took leave, and moved on in our different allotments.
We went to Gilmantown, fourteen miles of rough road,
where a meeting was appointed at two o'clock in the afternoon,
which was largely attended by Friends and others; and through the renewings of best help,
the doctrines of the gospel were opened among them, to some degree of satisfaction.
On sixth-day morning early, we set off for Sandwich, thirty miles, the road mostly rough,
that we only went about three miles an hour; yet, getting safely and peacefully along,
we had no cause to complain, but much for thankfulness;
having an evidence that our Holy helper sends not forth his servants,
in regard to spiritual things, at their own charge; but, as formerly,
bids them go without purse, or scrip:
and while preserved in a state of dependence upon him alone,
they can likewise say they lack nothing.

On fourth-day afternoon, we got well to the widow Folsom's, twenty miles.
She is an ancient Friend, who has been much tried with bodily illness many years,
and recently has experienced several close provings, in the loss of husband and children,
that she was very low, as also her daughter Abigail; who is an exercised woman,
and felt very near to me in spirit.

We had a religious opportunity that evening in her mother's bed-room.
On fifth-day morning, we had a meeting with Friends and others, wherein I felt,
for about an hour, as much emptiness, as I thought any one could do;
except a desire that the divine will might be done not only in, and through me,
but by others then with me, for whom I felt a near and sympathetic travail,
insomuch that I apprehended it might be right for me to express something of it;
and further communication was then opened to the people.
Though it was rather a low exercising time,
yet when the meeting was over I was favoured to feel peaceful poverty.

When about to take leave of the ancient Friend, her daughter,
etc. my mind was replenished with the quickening of the word of life;
and under its humbling operation we parted,
and for several miles a profitable solemnity was the covering of our minds.

We got well to Lee, eight miles, about five o'clock,
were kindly received at Joseph Carthling's, and next morning had a meeting there,
with Friends and others, which I humbly trust was a season owned by our Heavenly Father,
who waits to be gracious.
On fifth-day, we had the company of Comfort Collins, an ancient Friend,
who in earlier years gave up in resignation to
pay a religious visit to Friends in England,
but, after embarking, found her mind set at liberty from the concern.^
footnote:[It is related of Comfort Collins, that about the year 1760,
she embarked with Sarah Barney, of Nantucket,
to pay a religious visit to Friends in Europe.
When they had been a while at sea, she pleasantly told her companion,
she believed the will was taken for the deed.
"`How is that,`" said the Friend, "`we are now on our way.`"
"`No matter,`" replied Comfort, "`keep this to yourself and we shall see.`"
Soon after the vessel sprang a leak, the captain thought it best to return,
and they were set on shore.]

2nd of eleventh month.--First-day we attended meeting,
at which was the largest number of Friends we have met,
and it proved the most exercising meeting to labour in; yet, endeavouring to be faithful,
I felt pretty quiet, though not much relieved in my own mind.
In the evening we went about two miles to lodge,
had a quiet opportunity to drop some hints of counsel and caution,
which I believe were received in the same love, wherein they were communicated.

On second-day we crossed the river,
and attended a meeting at Kitteray seven miles distant,
which seemed for a time a low stripping season,
yet not void of secret instruction to myself,
and through attention to the leadings of it,
he meeting closed much more to my relief than that on the day before.
We dined with Elizabeth Allen, an ancient widowed Friend,
who through indisposition had been confined to the house nearly twelve years;
but she was very resigned and cheerful, feeling to me to be alive in the Truth;
so that I was glad of the opportunity of sitting with her; my mind being humbled,
and strengthened, in a renewed sense of the sufficiency of the Divine power to preserve,
through every dispensation of trial, within or without, if we cleave to it.
Several steady young Friends coming into her room, our parting was, I trust,
felt to be under the humbling prevalence of our Heavenly Father's love.

We returned to Dover that evening; and next morning went nine miles to Rochester,
a large gathering of Friends and others.
It was felt to be a season of heavy labour,
yet not without near sympathy with Zion's travellers.
That afternoon we went to Berwick, ten miles,
and in the morning five miles farther to a large meeting, which,
through the renewings of best help, was an open, relieving opportunity;
though it seemed hard labour to awaken the minds of several, to dig through the form,
and seek after the power, which from meeting to meeting,
has felt to me to be too much neglected, by many professing the Truth.

Early on fifth-day morning we set off for Portland, forty miles,
which we were favoured to reach about seven in the evening.
Next day we sat at meeting with Friends and a few others.
Though the number was not great, a humble trust was raised that we were owned together,
by the administering of a little bread from that bountiful hand,
which waits to be gracious to those who trust in Him.

9th of eleventh month, first-day,--We came to Falmouth yesterday, six miles,
and to day attended meeting, which was large.
In the early part of it, my mind felt much stripped, and according to my measure,
dipped into sympathy with the honestly concerned labourers,
believing there were several present,
towards whom the language of Encouragement went forth;
but too many appeared of a contrary sort, who were hard to reach,
and made the labour heavy; but, endeavouring to move in the ability given,
my mind was pretty quiet.

On consulting with Friends about our further movements,
several different ways being proposed, which I had not before heard mentioned,
I seemed a little confused, so that I could see no way,
but was instructed in the fresh remembrance of these expressions of Scripture:
"`In returning and rest shall you be saved;
in quietness and in confidence shall be your strength.`"

I was thankful and felt favoured with quietude,
the way opening again for our going as had been before proposed.
In the evening, several Friends being present, with John Winslow and his wife,
at whose house we lodged, under the covering of solemnity,
the acknowledgement of the royal Psalmist was impressively opened in my view:
"`Great peace have they that love your law,
etc.`" which I had to make mention of with some addition;
and trust it was a humbling season to most present.
Soon after my dear companion and I retired to bed,
fully satisfied our stopping there was right.

Second-day morning.--We set forward for Lymington, twenty miles;
dined at a Friend's house, who has lately joined the Society by convincement,
had a religious opportunity in the family; and then proceeded on our way,
but the road so extremely rough, it was dark before we arrived at Lewistown.
We had a meeting on fifth-day,
with a few members of our Society scattered in the wilderness, and several others.

Though they appeared a poor company indeed, as to the outward,
had a poor place to meet in, and it was a very cold snowy morning; yet divine compassion,
owning the opportunity, abundantly made up for all these trials.
In the afternoon we went to Green, twelve miles of very difficult road, among rocks,
wood and snow; the latter covering some deep sloughs we had to plunge through,
rendered it hazardous; but we were favoured to get safe;
and though our trials did not end with the journey,
were strengthened to bear them pretty cheerfully.

16th of eleventh month, first-day.--We rode two miles to meeting, through the woods,
and over a high mountain, but we met with no accident.
A few newly convinced Friends belonging to this meeting,
and a considerable number not of our Society also attended.
I felt much weight to attend my mind, and thought for about an hour,
no one there could feel more unfruitful than myself.
Then life seemed gently to move, I stood up,
and through steady attention to farther openings, and the renewings of best help,
it became an instructive opportunity.
In the evening, we had a sitting with a few of the Friends,
to whom I felt much love and sympathy, and a strong solicitude for their preservation,
under the direction of the holy Shepherd.

This was the first log-house in which we slept,
and so open that we could see the moon and stars.
Soon after sunrise on second-day morning, we resumed our woody travel.
The snow being about six inches deep, made the track difficult for some miles;
but the road becoming more open, we got fast along and reached Winthrop at ten o'clock,
eighteen miles.

A meeting there in the evening, was a time of exercising labour.
On third-day we proceeded to Vassalborough, twenty miles.
The next day at their monthly meeting, my mind was humbled and renewedly strengthened,
under an undoubted evidence,
that the Father of the family had not forgotten to be gracious,
to his humble depending children.
I found it my duty to bear testimony thereunto,
and believe it was a time of consolation to some secretly tried minds in that place.

On fifth-day we went to Fairfield, sixteen miles,
and were kindly received at Harper Bowerman's, where we lodged,
and were comfortably accommodated; but in the night a great storm of wind arose,
with heavy rain, which beat upon us so that we had to rise,
and move our bed to another part of the room, but I don't know that we took any cold.
During the storm,
my mind was much dipped into sympathy with those on the
sea in grateful remembrance of our preservation,
when in a like situation.
We found on our return, trees both great and small, blown down across the road,
yet were favoured to meet with no accident.

23rd of eleventh month, first-day.--Public notice had been given of the meeting,
and many not of our Society attended.
Through the fresh extendings of best help, the doctrines of the gospel were opened,
and I trust well received by many.
At the close I requested a meeting in the afternoon,
particularly of the young people among Friends, which was fully attended by such,
and various others; and under the prevalence of our Heavenly Father's love,
there was I trust a renewed visitation to many tender minds then present.

On second-day morning before sunrise, we left our lodgings, crossed the river,
which was very full of ice, in a canoe,
and after about ten miles of very rough road through the woods, came to the Ponds,
where a few convinced Friends lived.
Many not of our Society attended the meeting appointed there,
and through the regard of our Heavenly Father,
who is pleased to visit his workmanship in the most remote corners,
it proved an open time to preach the gospel;
for which my soul desired to render the tribute of praise to Him,
the God of all grace and consolation, for his manifold mercies to the children of men.

We were favoured to get safe back to R. H.'s,
who accompanied us in the evening to pay a visit to a woman Friend,
apparently in a declining state of health, with whom we had a religious opportunity;
encouraging to a humble confidence in the sufficiency of divine power,
to bring about his own blessed design,
in the administration of such dispensations as in his unerring wisdom he may see fit.

On sixth-day morning, we left Vassalborough, for Pownalborough, twenty-six miles,
part of it a very hilly rough road, yet got well to George Ramsdell's about five o'clock,
the only Friend's family thereabouts,
with whom we had a religious opportunity that evening.

Before sunrise on seventh-day, we set forward for Bread Cove, thirty-eight miles.
We had a river to cross, the day also was very cold,
and great part of the road in the woods was so exceedingly difficult,
that sometimes we could not go more than two miles an hour.
This made it more trying to us than any day before; but Moses Sleeper from Vassalborough,
who was with us, and well acquainted with every track,
encouraged us to hope we should get safely along, which we did,
arriving at the Friend's house before dark, without any material accident.

The ground being hollow in many places, occasioned by the frost,
it broke under the hind feet of the horse I was upon, and threw him down;
I fell backwards on the ground, and John Robinson, the Friend before me,
on the other side; yet, through Divine favour,
neither we nor the beast received any hurt.

A meeting was appointed next day at two in the afternoon,
which was fully attended by those not of our Society; and after a season of stripping,
and poverty of spirit, a little life arose,
and though it was a time rather of labouring in, than preaching the gospel,
my mind was favoured to feel a peaceful release.

After meeting, a German being very desirous we should call at his house,
whose wife also appeared kindly disposed, we took some refreshment with them;
and some of their neighbours coming in sat down quietly with us.
In the renewings of gospel love, I had a few hints to communicate,
by way of encouragement to their minds, who felt to me to be seekers after Truth.
We then returned to our lodgings at Isaac Lincoln's,
who came into the Society by convincement, and is the only member of it there.
His wife and family were as kind to us as any Friends we had been with.
This being the farthest part of our travel eastward, we set forward on sixth-day morning,
and got to Arnold's ferry, thirty-eight miles.
On seventh-day as soon as we could see, we crossed it, and went to Bath, five miles,
where are a few convinced Friends, but no meeting is kept.

30th of eleventh month,
first-day.-- The meeting was fully attended by those of other societies,
and through the renewings of best help, was in some degree a satisfactory opportunity,
but I believe would have been more so,
if the slow gathering of the people had not interrupted silent worship.

Third-day.--We visited a Friend who appeared to be drawing near the solemn close of life,
likely to leave a wife, and flock of young children;
yet his mind seemed preserved in much quietude,
and ours were drawn into near sympathy with them: I was glad we went.
In the evening Friends came from various parts to attend the quarterly meeting,
among whom was David Sands,
who about ten years ago spent much time in this eastern country,
and was made instrumental in the divine hand,
to convince many of the inhabitants of the principle of Truth;
and though then under extreme outward difficulties and trial,
it appeared rather a time of rejoicing, that Truth gained ground; but,
in the course of this journey, his soul has been made sorrowful,
which he expressed in much brokenness; finding many have left their first love,
and others settled down, more in the form than in the power, of pure undefiled religion.
His sense of these things, was somewhat encouraging to me,
having secretly mourned from place to place, under the feeling thereof.
The number of professors among us is very considerable in these parts:
the yearly meeting had given liberty for the quarterly meeting to be divided,
and low as things seemed, it appeared to be the pointing of best wisdom;
and through renewed condescension,
I hope proved a time of close searching to many on their own accounts,
as well as through the line of ministry;
uniting to strengthen a solemn inquiry into the state of our minds, in a general manner,
and whether we are grateful receivers of the manifold mercies of our Heavenly Father.
I trust it was a season that will not soon be forgotten.

The several meetings held three days,
and from and to our lodgings took eighteen miles riding.
On seventh-day morning, we took a tender leave of the family we had lodged with,
and in company with many Friends, returned to Falmouth twenty-eight miles.

First-day, 7th of twelfth month.--We went to Portland.
When there before, I felt my mind secretly touched with gospel love to the inhabitants,
which increased so that I requested a religious opportunity.
It was held in the town-hall, and more fully attended than I had expected,
supposing many would be strict in going to their own places of worship on that day.
Help being near to open counsel, the opportunity appeared satisfactory to Friends,
and a humble trust was revived in my own mind, that the cause did not suffer.
At the close of this meeting there was much inquiry,
if there would not be another in the evening;
but I was thankful to feel peacefully released;
and having but just time to get to the quarterly meeting at Dover,
we proceeded sixteen miles that evening.
We were accompanied by Jacob Mott, Joseph Harris, and +++______+++,
who were part of a committee, appointed by the yearly meeting,
to sit with Friends in these parts,
and to feel with them respecting the division of their quarterly meeting.

On second-day, we went to Paul Rogers's, twenty three miles;
and on third-day in our way to Dover,
breakfasted with our valued friend Mehetabel Jenkins, who, some years ago,
paid a religious visit to Friends in Europe.

On fourth-day we attended the select quarterly meeting for Dover,
where I again met our  valued friend David Sands,
who had the most close searching labour in the line of gospel ministry, I ever witnessed;
yet the evidence of Truth left no doubt there was cause for it;
and it greatly tended to relieve my mind from a load of secret exercise,
that had attended it from place to place.
In the quarterly meeting at large, attended by Friends and others,
there seemed but little channel for communication, though I felt much exercise of spirit;
and a sentiment was revived, that the more select our meetings for worship are kept,
previous to those tor discipline, the more the way is open,
to point out the situation of things among ourselves;
and it felt to me to be obstructed at that season.

When separated, my mind was dipped into sympathy with women Friends,
and made willing to encourage and instruct them, as far as lay in my power;
for though their number was considerable,
and there were several well minded Friends present;
yet there seemed little exertion for right order
in transacting the affairs of the church.
Meeting was adjourned to next day, when David Sands was engaged to come in,
and bear a lively testimony to the state of things,
so entirely corresponding with my feelings, that I could say in truth,
he was indeed a fellow-helper in the Lord.
Parting with many Friends in much tenderness, we returned to our lodgings,
where several were collected; further religious labour opened,
and our minds were preserved under profitable exercise, till we retired to rest.

Seventh-day morning.--We went early to breakfast with a Friend's family,
one mile and a half distant from where we had lodged before;
for I apprehended a little debt was left unpaid; and best help being renewed,
I believe it will be safe to say, it was a humbling, satisfactory opportunity.
Returning to our lodgings, we found David Sands and several others.
Under the influence of our Heavenly Father's love, we had a solemn parting,
likely to be a final one to several; but if, as was expressed,
we are favoured to keep our habitations in the Truth,
so as to meet in an enduring inheritance, all will be well,
and the pain of separation be felt no more.
Dear +++______+++, having the care of us, we proceeded to Seabrook, twenty-four miles.

14th of twelfth month, first-day.--Attended meeting,
a large gathering of Friends and others.
My mind being stripped of all former clothing for religious labour,
the prospect of sitting among them was humbling.
Early did I feel there were dark, opposing spirits in the meeting;
but patiently seeking for the renewings of holy help,
my mind became raised above all fear, within or without,
and I humbly trust counsel was opened,
and strength afforded to communicate it to the people in the wisdom of Truth.
The meeting was quiet, and ended under a solemn covering.

After an opportunity among a few Friends at our lodgings,
wherein encouragement was handed to the faithful labourers,
we went to Amesbury seven miles; the next day we had a meeting at Newtown, seven miles,
fully attended, but long in gathering; which made the labour more exercising;
yet it concluded to some relief and satisfaction.
We dined with a Friend who had lately lost her husband, to whom and a few other Friends,
religious labour was extended.
Parting in tenderness, we returned to Amesbury, seven miles,
had a meeting there on third-day, a time of close labour,
being dipped into several states, yet relievingly so,
and my mind was favoured to feel quiet poverty.

We went eight miles to breakfast on fourth-day morning, to a family,
part of whom had deviated much from the principle of Truth:
some solemn warnings went forth; also the language of encouragement,
to such as had not departed from the faith.
Wee returned two miles to meeting, which was a trying season indeed;
but little relief was obtained in either silent or public labour.
We got that evening to Salem, twenty-four miles;
and next morning a meeting with Friends tended more to relief, than a similar one,
in our going eastward.
At the close,
I felt an impression to have one for those not of our Society in the evening,
which was fully attended, and through divine regard, proved an open satisfactory time.
On sixth-day we went to Lynn, seven miles.

21st of twelfth month,
first-day.--We attended the largest particular meeting we had been at during the journey;
a time of close searching labour among some superficial professors,
who thought more highly of themselves than they ought to think;
but encouragement and consolation flowed freely to the humble depending children,
among whom there is a considerable number of hopeful young people.

In the evening we stepped into several Friends' families,
where further religious labour opened;
also a tender salutation at our lodgings before we parted.
On second-day we called to visit a Friend who was ill, in our way to Boston,
twelve miles, where a meeting was appointed in the evening, for the black people,
which was fully attended by them and many others.
The silence was remarkably solemn;
my mind was humbled in thankfulness to the blessed Author of all good,
that the bonds of that oppressed people, the enslaved Africans,
are in those parts so fully broken: they have now equal liberty with others.
Tender counsel and caution were opened,
and a grateful sense thereof was expressed at the close, by several of them,
who came to take leave of me.

On third-day morning we proceeded to Pembroke, twenty-five miles;
next day we attended the week-day meeting, which having sat the usual time in silence,
I felt liberty to express my expectation that it would have concluded so;
but a few remarks opened of counsel and encouragement, to Friends then present,
some of whom, I believed to be sincerely exercised members in the church;
with whom I felt near sympathy; the pure life appeared to me much oppressed by others.
Rode six miles before, and seventeen after meeting, on our way to Bedford,
and lodged at an inn.
We rose early, and got to a meeting at Longplain, fifteen miles;
afterwards visited a widowed Friend and her children,
who were detained at home with sickness; and had a tendering satisfactory opportunity.

On fourth-day we reached Bedford, and found the relatives of my dear companions,
generally favoured with health; my own mind being covered with peaceful quiet,
claimed renewed thankfulness to the great Preserver, who had mercifully cared for us,
both in perils by sea, and in the wilderness.
I here met my beloved friend Rebecca Wright from New Jersey,
with whom I had travelled nearly three years in England, in her gospel labours.
Our now meeting again at so great a distance, was attended with humbling,
but I trust not unprofitable feelings.

28th of twelfth month,
first-day.--Having had previous apprehensions of
visiting the families of Friends belonging to Bedford,
I mentioned it at the close of the morning meeting; and it being united with,
James Davis, a minister in good unity, was free to accompany me;
as was also dear Rebecca Wright.
We sat in two families that evening; and by that day week got through the whole,
in number nearly fifty.
Through the extension of divine regard, my mind felt peacefully relieved;
and after returning to our lodging, our valued friend and helper, James Davis,
was drawn forth in solemn supplication,
and grateful acknowledgement to our Heavenly Father.

6th of first month, 1795.--On third-day morning, James Davis, Rebecca Wright, and myself,
with two other Friends, went to attend a quarterly meeting for Rhode Island,
held at Somerset, near Swansea.
The select meeting began at eleven next morning, which felt to me a low season,
as did the succeeding meetings; for though largely attended by numbers,
the life of Truth seemed in an oppressed state from various causes;
some of which appeared very conspicuous,
and were well observed by my valued friend and brother in gospel fellowship, John Wigham,
whom we met there, and who had visited many of the families belonging thereto.

This being the quarterly meeting to which our truly valued friend, Job Scott, belonged,
the account from Friends in Ireland of the close of his gospel labours,
and removal from works to rewards, was read therein.
I was secretly ready to marvel,
that the revival of his memory seemed so little to affect me,
when I recollected what a struggle my very nature suffered, in my own habitation,
when I heard of his death; but being at this time dipped into a mournful sense,
of what such deeply exercised travellers have to pass through in their pilgrimage here,
I was ready to congratulate his peaceful release;
having no doubt of his being numbered among those who die in the Lord,
and enter into his rest.

On our return to Bedford, I found letters from my endeared friends W. and E. Rotch,
who were anxiously expecting us at Nantucket;
the season of the year being much farther advanced, than usually admits of navigation;
but the mildness of it had remarkably favoured our getting along hitherto.
For this, and every other mark of divine regard in things spiritual and temporal,
my soul humbly craves to be preserved in a reverent, thankful sense.

11th of first month, first-day.
Was favoured to sit two open meetings with Friends, and one appointed in the evening,
for those who had frequently attended our religious meetings,
yet not joined in membership.
Many others of several descriptions came in.
The opportunity was owned by divine regard;
and strength was renewed to labour among them; after which,
my mind was fully at liberty to leave Friends here for the present.

On the 14th, parting with the family of and other Friends, in much nearness,
Rebecca Wright, L. R. and myself, sailed for Nantucket, sixty miles,
about nine in the morning,
and made two-thirds of our passage in little more than four hours; when the wind changed,
so that, with frequent tacking, it was midnight before we reached.
The night being very dark, it required great care and skill in the captain,
to escape the rocks and sands; but our minds were preserved in much quiet,
and we had cause to esteem it a favour from kind providence that we got safe;
for before morning a heavy storm came on.
Our endeared friends W. and E. Rotch had been anxious for our arrival,
and were much relieved by it.

Next morning R. Wright being unwell, I went to their week-day meeting without her,
and though small, by reason of the continuation of the storm, I was glad I was there;
feeling a peaceful evidence that I was in my place,
and come in the right time to the island.

On first-day following, about the close of the meeting,
I informed Friends of my prospect of a religious visit to their families;
but knowing my valued fellow labourer John Wigham had felt the like impression,
I was most easy to wait till I could hear from him;
which contrary winds prevented for nearly two weeks,
during which time I sat nine meetings,
and was in some of them rather more opened in public labour than usual,
when such a prospect has been before me; but beginning to feel my prospect very heavy,
and my faith ready to fail respecting J. Wigham's coming,
and Rebecca Wright apprehending she was not called to that labour,
and that her health was unequal to it,
I told her I believed I must be resigned to enter into it alone.
I tried to keep quiet, and John Wigham came by the first packet in two days.
We began the family visit, accompanied by our friend William Rotch;
R+++.+++ M. right also going with us to a few families,
and my valued friend E. Rotch or uniting therein; as it always has been my desire,
to have in company a Friend or two belonging to the meeting,
that were ensamples to the flock.

In the south meeting were about two hundred and twenty families.
We then went to the north meeting, accompanied by Jethro Mitchell, and Sarah Barney,
two valuable Friends in the station of elders.
In that meeting, were about one hundred and thirteen families.
Feeling clear of Friends, my mind was turned to those not of our own Society,
and we had a public meeting on first-day afternoon, which was a time of close labour;
the minds of the people appearing, in a general way,
much strangers to the principle of Truth in themselves;
yet through merciful regard I was somewhat relieved by the opportunity.
We also attended the select and both monthly meetings, previous to the quarterly meeting,
and had a public one appointed at the south meeting-house,
for those in the seafaring line, (of whom there is a great number) and the black people.
Through divine regard it proved an open, satisfactory opportunity.
My mind now felt fully at liberty to leave the island, but the wind being contrary,
we staid over first-day, which was not unpleasant; for I was glad to feel,
the more I was among Friends, the more I loved them.

That evening we had an opportunity of sitting
with a widowed Friend and her surviving children,
who had that day buried her eldest daughter, a very comely young woman, who,
about eleven months before, contrary to her mother's and friends' advice,
had gone out in marriage with one not of our Society.
When so ill that her dissolution appeared near, she requested to see me,
if I was free to go.
My dear friend E. Rotch accompanying me, we went, and sat by her;
an affecting time indeed it was; her near relations were in great distress,
and her own was almost insupportable, begging earnestly in a plaintive language,
that seemed almost to pierce my soul, for a little longer time,
that she might be favoured to feel a hope of reconciliation to the Almighty,
and to her friends; saying, she was afraid she had been deceived,
in thinking she had a right to choose for herself, in the step she had taken.

I could say very little, but recommended to her and those about her,
as much stillness and inward retirement as they could attain,
and to seek the Father and fountain of all sure mercies;
feeling little or no evidence respecting her life or death,
acceptance or rejection by the Lord; yet I expressed a hope,
that a little longer time would be given,
remembering the compassion of Christ to the thief on the cross.
This proved to be the case; during which time,
my mind was brought under an unusual travail, both by day and night, on her account.

When I went to see her again, she lay very quiet, though in great bodily pain,
and seemed to have a ray of hope; saying, all she could endure while she lived,
she desired to bear with patience,
if her time might be lengthened until her peace was more fully made.
While sitting with her, I was not afraid to believe, or mention, the evidence vouchsafed,
that there was mercy for her with the Lord; at which she seemed much tendered.

On seeing her again, she had in the interim undergone much painful conflict;
and going in with L. R. a few hours before her close,
one of her sisters thought her in a quiet sleep, but on going to her,
I found it was the sleep of death, which took place in about three hours.
Nothing that could be said would then affect her,
but a passage of Scripture rising again with life, which had opened livingly in my view,
when sitting by her on a former visit, though not then to make mention of,
I believed I was now commissioned to drop it: "`Comfort you,
comfort you my people,`" etc.; for I had a firm belief,
"`her warfare`" was "`accomplished,`" which was matter of much
consolation to her afflicted mother and relatives;
yet I had strongly to recommend to the younger part of the family,
that the deeply affecting, and instructive lesson, might not be forgotten,
but remembered like "`the wormwood and the gall`" to the humbling of their souls,
which I thankfully hope will be the case with some of them at least.

My endeared friend Rebecca Wright, staid seven weeks with me,
under the bonds of near uniting love; and when she was at liberty to return home,
at the time of parting, was drawn forth in solemn supplication,
for the preservation of those she left behind; particularly for the family we were in,
and for us who were sojourners in a strange land.

24th of third month.
On third-day, after an affecting parting with some of my dear friends,
we left the island, in company with John Wigham and several other Friends,
to attend the quarterly meeting at Sandwich,
and after a fine passage of four hours and a quarter, landed at Woodshole, forty miles,
where our carriage was sent from Bedford.
With dear L. R. we went to a meeting appointed at Falmouth, her dear father,
attending us, not only taking care of driving the wagon, but being like Urbane,
"`a fellow helper in the Lord.`"
Many not of our Society attended, and through the renewing of best help,
it was an open satisfactory opportunity.
In the afternoon we rode fifteen miles to Sandwich.

On sixth-day, the select quarterly meeting was held to some degree of satisfaction,
mostly composed of aged Friends.
I was afresh confirmed in what I felt,
in the first select meeting I sat with Friends here, that those meetings suffer loss,
by Friends not enough looking at the right anointing, and qualification in individuals,
to bring such forward, before so far advanced in years, when they might be more lively,
and fit for religious usefulness.
The weather was remarkably fine on our coming to this place,
and the sun shone very bright in the evening, yet before morning a great fall of snow,
drifted by the violence of the wind,
rendered it almost impracticable to get to the meeting-house; that only a few met,
and adjourned the quarterly meeting till seventh-day,
which was then attended with difficulty,
and many that lodged at a distance did not get to it; yet the business was got through.

29th of third month.
On first-day was a large public meeting,
in which several Friends had to labour in the gospel, but not an open,
or relieving time to me.
We went that evening with Joseph Cloud and John Wigham, a few miles towards Barnstable,
where a public meeting was held next day in the court-house, wherein J. Wigham,
whose mind was impressed with the concern, had to preach the gospel.

After dining at an inn we went to a little fishing place, called Bass river,
and had a meeting there that evening, in which my valued brethren,
Joseph Cloud and John Wigham had an open time in gospel labour.
Next morning we went five miles to a meeting at Yarmouth,
which was attended by Friends and others, and was a relieving opportunity to my mind;
in the afternoon to Scorton ten miles; next day to Paul Wing's,
where we had a religious sitting in the evening.
Encouragement was handed to those that love Truth,
of which number were several both of the younger and elder rank:
their children appear to be hopeful plants.

At Longplain monthly meeting on sixth-day,
an acknowledgement was presented ft-om a Friend,
who for many years (before the American war) had stood in the station of a minister, but,
through unwatchfulness at that time, giving way to a party spirit,
got disunited from Friends, and several others with him,
who had kept up a separate meeting; but now, in his advanced age,
he appeared uneasy with the practice, condemned the cause,
and earnestly entreated Friends to receive him into membership, which, from my feelings,
I was willing to hope would be complied with.
That evening we went to New Bedford, ten miles,
to which place the prospect of returning has always looked pleasant,
since my first going there;
and I believe mutually so to my beloved friends in that place.

5th of fourth month, first-day.--The forenoon meeting was to me a humbling,
relieving opportunity: my heart was enlarged and my tongue loosened to preach the gospel,
that I could truly acknowledge times and seasons were in the hand of the Lord;
remembering several, in which I had sat among Friends there,
when the heavens seemed as brass, and the earth as iron.
In the evening, we had a meeting at Acushnet, head of Bedford river,
which I felt liberty to have appointed at three o'clock,
at which time the Presbyterian meeting was gathering, about a stone's cast from ours.
I rather expected we should have a small company; but,
as that had appeared the right time, I felt easy.
Contrary to apprehension the house was soon filled, and when settled,
I felt gospel authority to stand up, and had an open relieving time.
My valued friend W. Rotch, his son and wife, and several others in company,
returned to Bedford in the evening.

On third-day we went to Newtown, five miles, where was a large meeting of professors,
and a few not of our Society.
A painful sense of lukewarmness and formality, caused heavy labour indeed;
which was not very different next day at Aponaganset, six miles.
We went that evening to Acoaxet, ten miles; and on fifth-day morning,
had a meeting there, largely attended, and rather an Open time;
as was also one in the afternoon at Center.
On sixth-day at Little Compton, the meeting-house was very open and cold,
and the people long in gathering; yet I trust it was not an unprofitable meeting.
After dinner we went six miles to Seconet, and on seventh-day to Tiverton fourteen miles.

12th of fourth month, first-day.
We had two meetings, attended by a solid number not of our religious Society,
which were pretty satisfactory.
Though the life of Truth, with regard to Friends, appeared to me very low;
yet I felt much sympathy with the few concerned to walk consistently therewith.

On second-day a meeting was appointed at Swansea, at three o'clock.
We had a pleasant time for crossing the ferry, but soon after a heavy storm came on,
and continued without intermission.
Friends living distant I hardly expected many would gather,
and being oppressed with a sick headache, I almost doubted being able to sit the meeting,
yet was most easy to go, and it was largely attended.
After painful conflict of body and mind,
I was strengthened beyond expectation in the discharge of duty;
that I felt a peaceful quiet, and my head much relieved from pain.
On third-day morning we had a meeting at Freetown.
In the afternoon we went to Mansfield, twenty miles; part of it bad road,
and it was nearly dark when we reached our lodging at a dirty inn.

On fourth-day morning, we went to Foxberry, three miles,
at which place are a few who appear under convincement.
A meeting at eleven, was attended by many more than we expected,
and my mind was brought under great weight,
it being the first meeting of Friends held there; but, through divine regard,
it was in some degree a satisfactory opportunity.

That afternoon we reached Providence.
Our valued friend Moses Brown met us on the road, and we lodged at his house.
Their meeting on fifth-day, was to me a strengthening time in silent waiting.
Towards the close I had just to tell Friends, that I had had a good meeting.
In the afternoon, called on some Friends who were indisposed,
and in the evening returned to our lodgings, about a mile from the town,
where we staid to give time for appointing a meeting at Smithfield on seventh-day,
where M. Brown and his wife accompanied us, also to Woonsoaket.

19th of fourth month,
first-day.--A large open meeting at Woonsoaket with Friends and others.
In the afternoon went to Elisha Thornton's,
to see the children of our late valued friend Job Scott,
with whom we had a tendering opportunity.
On second-day we had a meeting at Mendham, a time of close labour;
went that evening to Northbridge, and had a pretty open meeting there next day;
from there to Leicester, called twenty-one miles, which appeared very long,
from the roughness of the road.
We had a meeting there on fourth-day;
in which the necessity of looking beyond man for help, in our religious progress,
was deeply impressed on my mind; which it seemed right to communicate.
In the afternoon we called on several Friends who, living distant,
do not often see Friends but at meeting.

On fifth-day morning we set off for Orange, thirty-five miles,
but the roads were so rough and hilly we stopped a little short at an inn,
where we were agreeably accommodated;
our guide going forward to get a meeting appointed on sixth-day morning.
Many people attended; but it being a newly settled meeting,
and containing only three members of our Society, my mind feeling very low and stripped,
was brought under much inward exercise, lest the cause should suffer; but,
through merciful regard, I hope it did not; and I had to believe,
the visitation of Truth was offered to many present.
In the afternoon we had a continuation of very rough hilly road to Richmond.

26th of fourth month, first-day.
A rainy morning, and considering the distant situations of Friends,
the meeting was pretty fully attended.
It was a season of close heavy labour,
yet encouraging to those who desire to keep their habitations in the Truth.
My own feelings are frequently so discouraging,
that I can scarcely hope any good has been done; but leaving this to Him,
whose ways are all wisdom, and his counsel a great deep,
I find it safest to endeavour to be honest;
and I trust am made thankful when favoured to feel a peaceful release thereby.
This was the case at this place;
also in collecting several young people that were about the house we lodged at,
in the evening, who I thought stood in great need of help;
and I felt stirred up to cast in my mite, in this resignation I had the reward of peace.

This was the last meeting northward, excepting one ninety miles distant,
which I then felt liberty to leave; and on second-day morning,
was made glad we could turn our faces southward.
The roads still very rocky and difficult, but I was favoured to feel a quietude,
that overbalanced outward trials; under which I was led to visit in spirit,
my dear friends and near connexions in my native land; with renewed desires,
that the blessing of preservation may be so witnessed, that, if spared to meet again,
we may be enabled to rejoice in the Lord, and joy in the God of our salvation.

This was a very wet day, and the rain beat directly into our carriage, that,
after riding twenty-eight miles, we stopped at an inn to lodge.
Next day we rode to Bolton, where, on fourth-day, we had a pretty satisfactory meeting.

In the afternoon we went to Grafton, nineteen miles,
and called in the way to see a Friend that was poorly; next day to Uxbridge;
staid the monthly meeting on sixth-day, largely attended by Friends and others,
a time of close searching labour among those of our own Society,
and strength was given to open the doctrines of
the gospel to those not professing with us.
On seventh-day we had a meeting at Douglas.

3rd of fifth month,
first-day.--At Gloucester I was led nearly to sympathize with Zion's travellers,
and remind the lukewarm of their dangerous state.
After meeting we went with a Friend a few miles to dine,
had a religious opportunity with several Friends collected there,
and in the evening rode to Smithfield,
where on second-day morning we had a large open meeting,
many not professing with us attending.

On third-day a meeting at Foston was in like manner favoured.
Here our valued friend Moses Brown met us.
On fourth-day we had a meeting at Scituate, a quiet solid opportunity.
Before the close, I had a few remarks to make in public testimony.
That evening we went to Cranston.
At meeting there next day,
my mind was dipped into sympathy with some exercised travellers;
and I likewise endeavoured to awaken the lukewarm and inconsiderate.

Here Moses Brown's wife and son also met us, with whom Ave returned that evening,
and were glad to rest on sixth-day; the weather being hot and sultry,
I felt relaxed and faint.
On seventh-day, a gentle breeze made it more pleasant:
we went a few miles to see the near relatives of our much beloved friend Job Scott,
who was mostly the subject of our conversation; and in reading some of his remarks,
solemnity was the attendant of our minds; that it was a satisfactory visit.

10th of fifth month, first-day.--Sat three meetings at Providence,
and may in humble gratitude acknowledge, the evening crowned the day,
though not so fully attended by people of other societies as was expected.

Second-day morning.
Very heavy rain, yet it seemed best to proceed on our way,
as a meeting was appointed at three that afternoon at Greenwich.
The meeting was largely attended both by Friends and others;
my mind soon became secretly exercised, and the more I bowed under it,
the more I found the way closed up from public labour.
After sitting about an hour and a half,
I felt liberty to say I was free to sit a meetingJn the court-house at Greenwich,
if spared till ten next morning, when their company would be acceptable;
but should take it kind if they would then withdraw,
and leave the members of our Society.
To these, after a short pause, I was helped to relieve my own mind.
The public meeting next morning was large and satisfactory.

After dinner we proceeded to Wickford, nine miles,
where a meeting appointed at the third hour, was largely attended;
and great willingness manifested in the people, as in all other places,
to hear the gospel preached;
but too few are willing to become the disciples of our blessed Lord,
by taking up their cross in the denial of self.

We had a long ride that evening to South Kingston, very foggy,
and quite dark before we reached the Friend's house.
The road was so bad, that when we went over a part of it again next morning,
it was marvellous in my eyes that the carriage had not been overturned;
which raised in us grateful acknowledgements.

We attended the Back meeting, which, though small, was in some degree satisfactory.
That afternoon went a few miles through the woods to see a Friend very ill in a decline,
though as to years in the bloom of life.
She was married and had one child: we had a tendering opportunity with her.
On sixth-day, at Hopkinton, we had a large meeting,
in which my way was opened to deal plainly and honestly with the professors of Truth,
among their neighbours; feeling my mind strengthened in hope, there were a few preserved,
walking consistently with our high and holy profession.

We staid that evening at a Friend's house,
who had been a physician of considerable account, and of a lively disposition;
but for sometime had lost the noble faculty of reason,
and was reduced to the capacity of a child; his words and actions very innocent.
It was more humbling than painful to be with him,
proving how little as men and creatures, we can either procure or prevent.

17th of fifth month, first-day.--We had a very large meeting at South Kingston,
of most descriptions of people, among whom I humbly trust the gospel was preached,
and the nature and spirituality of the pure principle +++[+++the
immediate manifestation of the Holy Spirit to the mind of man]
set forth, as professed by us,
in a manner distinguished from those of other religious societies;
how it would guard and influence such as walked consistently with it:
and what those were, who only made a profession of it.
My mind was humbled under a thankful sense of our Heavenly Father's regard,
towards the mixed multitude.
It was near two o'clock when this meeting ended,
and we had another appointed to begin at five that evening, nine miles distant,
three of them by water.
We had some detention at the ferry, and could not get our carriage over then;
but we went forward on horseback, and reached the meeting in due season at Canonicut,
and found the time more suitable than next morning would have been,
as Friends were invited to attend a burial at a distance.
It is not customary to have a meeting on such occasions,
except at the house of the deceased.
I felt a liberty to attend this sitting, which was a quiet opportunity;
nothing was handed about to the company.
This I could not help wishing might become generally the case in our country.

We did not go to the burying ground, but called on a sick Friend;
and in the evening crossed a ferry to Newport on Rhode Island,
accompanied by John Hadwen, his son and daughter, at whose house we lodged.
We had rather a tossing passage, but were favoured to land safe.

On third-day evening we went to Portsmouth.
Their meeting on fourth-day, was a time of close searching labour,
yet attended with encouragement to the sincere hearted.
We returned to Newport in the evening, calling on our way to visit a Friend confined,
with whom we had a satisfactory opportunity; her mind appearing in a quiet,
resigned state.

24th of fifth month, first-day.
We sat both meetings at Newport.
I was engaged in further labour, yet not fully relieved;
but having a prospect of being there again,
I was entirely at liberty to leave on second-day morning,
and returned to Bedford with our kind attendant W. R. jun.
who had been with us six weeks.
Going again to his house, was in some degree like returning home,
where we met with a most affectionate reception even from the little children,
who feel very near to me; and these circumstances make a little respite from travelling,
I trust in the liberty of Truth, a quiet enjoyment.

31st of fifth month, first-day.
At Bedford.
During my stay here we visited several Friends to my satisfaction,
being favoured to feel the renewings of best love flow towards them,
particularly to my ancient and honoured friend Mary Rodman,
who was in a declining state of health, and at times much tried in mind,
when the beloved of her soul saw fit to withdraw
the sensible feeling of his life giving presence;
yet there is no cause to doubt His arm being underneath, to support,
and take into his own keeping, till the time of bodily conflict is over.

My valued friend William Rotch, being under appointment with another Friend,
Jeremiah Austin, an elder, to attend the monthly meeting at Pembroke,
I was free to accompany them, also to another at Longplain.
On our return we met with dear Samuel Smith from Philadelphia,
in whose company I had been both in England and Ireland;
that it was cause of rejoicing to meet him again,
and to feel unity and near fellowship with his spirit and gospel labours.

We came to Bedford, and staid first-day, 7th of sixth month.
On second-day, I went with him to Aponaganset,
which more clearly opened my way to leave Friends, than on my former visit.
On third-day morning, I left Bedford, and accompanied by William Rotch and his wife,
went to attend the yearly meeting for New England, held on Rhode Island.
At a tavern on the way,
we had the satisfaction of meeting my endeared fellow labourers from England,
Deborah Darby and Rebecca Young,
which I believe was felt to be a solemnly affecting season to us, and others present.
Silence ensued for a considerable time; and much contrition spread amongst us;
that I have scarcely known the like.
What most deeply impressed my own feelings, was the renewed humbling sense,
that we poor females were found worthy of being
commissioned with such embassies to a distant land,
and to become fellow sufferers in the bonds of the gospel.
In our united labours through the various sittings of the yearly meeting,
the strength of Israel being our hope, we were rendered a comfort to one another,
and made at seasons a little joyful in the house of prayer,
in near and dear fellowship with the living members of the church,
in every rank of the family.

14th of sixth month, first-day evening.
We sat a meeting appointed for the black people,
which was largely attended by them and proved satisfactory.

On third-day evening, we again parted under the renewed,
humbling influence of our Heavenly Father's love,
proceeding in our different allotments of labour in the vineyard.
My valued friend John Wigham and others, eastward in New England;
my dear companion and self, parting with her near relations at Portsmouth,
proceeded through Connecticut towards New York,
where of late time there is great openness in the people towards Friends,
especially about Hartford; in the neighbourhood of which we had,
on the 21st of sixth month, first-day morning,
a satisfactory meeting among some who had requested to
be joined in membership with our religious Society;
and in the evening a public one held in the court-house,
which also tended to some relief,
and was the closing religious opportunity in New England,
before proceeding to the southern states.
Much solicitude was expressed by the people that we should stay and have more meetings,
but I was pressed in spirit to journey forward.
Sitting the week-day meeting at Mamaroneck in our way, we arrived safe at New York,
on seventh-day evening, and were kindly received by John Murray,
brother to my valued friend Lindley Murray, who has resided some years near York,
in England.

28th of sixth month, 1795.
First-day.
At both meetings; we also attended the select monthly meeting, and that for discipline.
We went to see several Friends;
but the time did not appear to be come for much
communication in the line of gospel labour;
and I felt entire resignation thus to pass through their borders,
expecting if life and health permit, to return there again.
We left this city for Philadelphia.

On our way we went to Nathan Wright's,
whose valuable wife I had travelled with in England as before mentioned.
We reached safely next evening about five.
Our valued friends Samuel Emlen and Rebecca Jones, were much our acceptable companions,
both in meetings, and at many Friends' houses; but my way, as at New York,
was rather closed from much gospel communication, except in one or two meetings.
We visited Hannah Pemberton, widow of our late justly endeared friend John Pemberton,
whose meek exemplary life closed at Parrmont, in Germany,
where his lot had been cast in gospel mission.

After stopping eight days in the city, we proceeded on second-day morning,
13th of seventh month, and got that evening to George Valentine's,
son of Robert Valentine, who was a noble warrior in the cause of Truth,
and left many seals of his ministry in his travels in Europe.
On third-day we had a meeting at Downingstown, held in a malt house,
there being no settled meeting in that place.
It was largely attended by Friends and others; and a humble trust was raised,
that the Father of mercies owned us, by the breaking of bread.

Several Friends who had come with us from the city, returned from this place,
P+++.+++ B. son-in-law to Elizabeth Drinker, on hearing we were likely to lack an attendant,
felt his mind impressed with a desire to accompany us,
which his friends and connexions uniting in, he continued with us.
We took the meetings at Sadsbury, Lampeter, Lancaster, and Wright's Ferry,
in all which we were favoured with a renewal of strength in the discharge of duty.
We crossed the river Susquehanna, to Yorktown.

19th of seventh month, first-day.
The morning meeting was a time of close searching labour, among those of our own Society.
The evening meeting was fully attended, an open satisfactory opportunity.
This week attended the meetings at Newberry, Warrington, Huntingdon, and Monallin:
the weather so extremely warm, my frame felt at times exceedingly debilitated; yet,
through divine regard, strength was renewed in the needful time,
so as to feel a peaceful release, though through close searching labour.

26th of seventh month, first-day.
We attended meeting at Pipe-creek, in Virginia,
which was a time of close labour to the different states of the people.
Through divine assistance, a peaceful acquittance was gained thereby,
and my spirit was united to a small number who are exercised for the welfare of Zion.
A meeting that evening at Bush creek, a large mixed gathering,
proved a time of heavy labour, many appearing hard to reach;
but towards the close a little ground seemed gained.

Next day crossed the rivers Monoquasy and Potomac; we found the roads very bad,
that it was dark before we reached Fairfax, but preservation was still continued.
We sat an appointed meeting next morning, in which a humble trust was renewed,
that in the power of gospel authority, the state of things was spoken to;
and my soul bowed in supplication before the Lord, that he might bless the labour.

2nd of eighth month, first-day.
Friends of Goose creek were desired to meet at ten,
to give us time to attend another in the evening, ten miles distant,
which they readily complied with.
When we got there the house was so full, and many out of doors,
that it was somewhat difficult to get in.
A sense of the compassion of the Shepherd of Israel,
was soon feelingly raised in my soul, and gospel power renewed,
to the information and humbling, I believe,
of many minds--with bodily strength to go through the exercise;
having to stand about an hour and a half, with the heat very great.
To the Lord alone belongs the praise of his own works!
We called and got some refreshment at a Friend's on our way to Southfork.

Though we had heavy rain, and the roads were bad and full of water,
we got in time for meeting; in which the labour was more exercising,
and less relieving than the former;
but as resignation of will in the servants on all occasions, ought to take place,
I felt no disposition to murmur, or to think either outward or inward labour hard,
if but preserved in the line of divine appointment.

Between the meeting and the Friend's house where we lodged, is a creek,
which soon becomes impassable with heavy rain.
This being the case next morning,
it was nearly eleven o'clock before we could get through,
and then we were conveyed in the Friend's wagon,
apprehending the water would run into ours.
A meeting was appointed at Berkley, to begin at ten next morning.
We had upwards of twenty miles of very stony road, over the mountains called Blue Ridge,
and a dangerous river to cross, called the Shenandoah.
The rain still continuing, the prospect for a time was discouraging,
but being favoured with inward quiet, it soon brightened a little;
yet I don't know that more secret thoughtfulness ever took hold on my mind,
respecting our situation, during our crossing the great deep, than while in the boat.

The stream of this water was so rapid, owing to the flood,
that we had to steer up it a considerable way;
and great was the diligence and care of three black men who attended the boat,
to escape the trees that were standing in the water, and others floating in it; yet,
with all their vigilance, we struck against one, which broke the oar,
and made some of our horses ready to start overboard; but at this critical juncture,
one of these careful mariners jumped on the side of the boat,
and clasped his arms round the tree, with his feet keeping us from striking again,
so as to do any material hurt: we then got in a right course for land.

The exertion of these men who are slaves to their employer, did not go unrewarded.
This opportunity, with many others, of observing their usefulness,
and what they might be to the community at large, if in the way of receiving instruction,
religious as well as civil, has affected my feelings with sorrow and mourning,
that any should thus be continued in bonds by their oppressors;
yet with many others concerned, a hope is renewed,
that the oppressed will in the Lord's time be set free.
On their account my soul travails, that neither they nor any of their race,
may be bond slaves to sin; for as I have sometimes had to tell them,
this would be the sorest of all evils, as the torture of the body can only kill that;
but sin leads the soul into endless misery, where the worm dies not,
and the fire is not quenched.

We got in seasonable time to a Friend's house, and were kindly received:
attended meeting next day, composed of Friends and others, situate in the midst of woods;
a few black people were also among them.
In the course of gospel communication,
I had to make some remarks concerning them and the unjustness of the traffic;
yet felt a care while speaking, that the zeal kindled in me might not be misguided,
and so lose the desired effect;
and having a humble trust that preservation was witnessed,
in quiet recollection as we rode along, I thought I should not have cared,
how many slave-holders had been present.
I found afterwards from information, there were several,
among whom was George Washington, nephew to the president,
who made himself known to a Friend in company,
acknowledged the truth of what was remarked, and gave us a kind invitation to his house.

