== Chapter VI.

Continuation of her Travels in America, in the remainder of 1795.

9th of eighth month, first-day.--We attended a very large meeting at Berkley.
I had for some days been much indisposed, and rested on sixth and seventh,
at a kind Friend's near the meeting-house.
My natural strength was greatly reduced, through the oppressive heat of the weather;
my head and throat were much affected, attended with strong symptoms of fever;
swallowing even liquids was trying, and I could scarcely bear to sit up;
but my mind was mercifully favoured with such entire resignation as I had not often felt.

I remembered the same Wisdom that had seen fit to remove other servants,
when in a land distant from their connexions,
could also give resignation to those most nearly allied to me, if I should be removed.
So clear and strong, for some hours was this secret impression,
that I was more than once very near acquainting
my tenderly beloved companion with what I felt,
and how I should like to have the order of my burial; but believe it was best I did not,
as it might have overwhelmed her with sorrow,
being daily sensible of her near regard and affection to me.

I was instructed that this state of my mind was permitted,
in order to fit me for further provings; that my day's work was not finished;
yet had I been at home under such a weight of illness,
I should not have thought it unlawful to have kept quiet in my chamber;
but I went to meeting, and about an hour and a half was a time of unspeakable exercise,
in silent wading, among a large mixed gathering;
the minds of the people being much afloat,
and the quietness becoming a religious opportunity interrupted,
which is too often the case in many places.
When it appeared near the time of breaking up the meeting,
a gentle motion of life impressed me to say,
that if no servant or handmaid had received more commission to speak than myself,
I believed it right nothing had been said;
not knowing that I should have any addition to make, or indeed that I could be heard,
for my throat was much swelled, and very painful; but, to my humbling admiration,
I was led forward, though in a line of labour in which no flesh could glory;
but as resignation, and dedication of will took place,
I felt healing virtue both of body and mind.
Finding myself not quite clear of the members of our Society,
I requested others to withdraw, and got peacefully relieved.

On third-day morning we were at Bear Garden, the last meeting on that side the Alleganies.
In the afternoon we went fourteen miles towards them,
had considerable difficulty in crossing Capon-creek, from great rains;
the water ran into our carriage, but we were preserved from any material damage,
and got before night to the tavern where we lodged, a poor dirty place,
but the people appeared kindly disposed.
I was taken very ill in the night, and got little rest;
great was the conflict of flesh and spirit.
My faith was tried as to a hair's breadth; and deep were the searchings of heart,
whether I was right in going to encompass the rugged mountains sixty miles over,
and we then thirty from the foot of them--because other servants had been sent;
or whether it was really required of me,
in the discharge of my own duty towards God and man.

I believe it would be difficult for any,
but exercised travellers in the line of experience, to read my state at that time.
How gratefully could I have embraced a peaceful release; but had then to remember,
my resigned state of mind a few days before;
and why not as willing to accept my life for a prey,
in filling up the measure of suffering yet behind?
This secret inquiry and tender monition, so instructed, and brought into passiveness,
that as soon as able to rise, we journeyed forward;
and with some difficulty I bore to ride twelve miles; when, stopping at a tavern,
I went directly to bed; but getting a little quiet rest that night,
was somewhat refreshed; and after another day's very rough travel,
we got to the foot of the Alleganies, beyond which is a settlement of Friends.
The difficulty of travelling in a carriage was beyond description;
yet without it I believe I could not have performed the journey.

We hoped to have reached the first meeting of Friends by the seventh-day evening;
but illness preventing, we were twenty six miles from it,
and had to lodge at a miserably dirty tavern; yet the poor people were kind in their way.
We rested very little,
and great was the sympathy I felt for the inhabitants of such uncultivated places.
The man and his wife acknowledged, that, though young people,
they were old and almost worn out in constitution, by their toil for a livelihood;
which appeared to be the case with many.

16th of eighth month,
first day.--We rose very early and journeyed on--my strength a little recruited.
We got one of our young men to hasten forward,
so as to reach the first meeting of Friends before they separated,
and request them to appoint one at four that afternoon.

We reached in due time the meeting called Sandy Hill, three miles from Union Town,
and beyond all expectation, a renewal of strength was mercifully vouchsafed to labour,
I humbly trust in the ability God gives;
that according to my measure I could acknowledge,
that when the Son of Righteousness is graciously pleased to arise,
healing virtue is witnessed, both inwardly and outwardly.

We went about three miles on our way after meeting, toward the next;
and being favoured to lie down in peace, and rest well, I was much refreshed;
and my mind was humbled in a thankful sense thereof We
proceeded to the meetings on that side the mountains,
as follows: Center, Providence, Sewickly, Fallowfield, Redstone, and Westland.

23rd of eighth month, first-day.
-- In the morning at Pike Run;
in the evening we had another meeting appointed at Westland for Friends and others.
At the monthly meetings at Redstone and Westland, which were largely attended,
and many seemed innocently disposed,
to transact the affairs of the church to the best of their understandings;
and my mind felt impressed to encourage them,
also to guard against receiving superficial requests to join our religious Society;
but to endeavour to feel whether real convincement was the ground work,
that the church might not be enlarged with useless members.

On second-day morning, we turned our faces towards the mountains;
and being informed of some friendly people on the way, I felt liberty in the Truth,
to sit a meeting at nine on third-day morning, held in a barn.
The number was not large;
but I was favoured to feel there were some sincere seekers after Truth,
towards whom encouragement went forth,
that they might not rest satisfied until they had found, in and for themselves,
Christ the true Teacher, and Bishop of souls.
Exhortation and counsel were also extended to those less
attentive to the inward principle or spirit of Christianity.
The people in general seemed well satisfied with the meeting,
and appeared to part with us in love: many of them are called Menonists, or Dunkers.
Some of the elders wear their beards, as they say, according to ancient custom,
but do not enjoin it as a part of their religion.

We next went to Sandy creek, the last meeting of Friends in these parts,
which was attended by many not of our Society; and on early sitting down,
what the Prophet had to express in the opening of vision,
when he saw Israel scattered on the mountains, as sheep having no shepherd,
was livingly opened in my view; attended with a motion of life to revive it,
and put Friends in a particular manner,
upon an examination how far it might be applicable to them:
for in the outward it was indeed so, and whether their inward state was not similar.
The Most High was supplicated, that He might be graciously pleased to preserve those,
who, not daring to lean to their own understanding, put their trust in Him alone.

After dinner we took leave one of another, and our little company proceeded,
lodging that night at a disagreeable tavern, where we got little sleep;
which proved trying to the bodily frame.
This is often the case, and may he esteemed in its measure,
a part of the sufferings we have to partake of; yet I felt a regard for the landlady,
who was kind to us.
We arose early and journeyed forward.
From the prevalence of fogs, it seemed for some miles like riding in a cloud.
On seventh-day night we reached a Friend's house at Back creek,
which felt comfortable both to body and mind.
Here we had an open meeting with Friends and others.

30th of eighth month, first-day.--We went to Hopewell,
which we had left just three weeks;
and our being favoured to witness the blessing of preservation,
called for renewed humble thankfulness to our Heavenly Father,
who has a right to dispose of us, as He sees fit.
After stopping two days for some repairs, etc. we proceeded southward,
taking meetings at Center, Mount Pleasant, Crooked run, and Smith's creek.

6th of ninth month, first-day.--We were at the meeting at Smith's creek,
attended by many not professing with us, in which exercising labour was my portion;
but sincere are my desires to be preserved from murmuring, and that I may rather rejoice,
that I am in any degree found worthy to suffer for the cause sake,
or with the seed in suffering.
After meeting, we went on to New-Market, a small town.
When riding into it, about three in the afternoon, many people standing about,
the motion of life arose in me to "`Gather the people:`"
and not having much time or desire to reason upon it,
being brought in measure to experience,
its becoming my meat and drink to do the will of my Heavenly Father,
though we had rode about eighteen miles and sat a meeting,
I could partake of no refreshment till I had inquired
if there was a place in which we could hold a meeting.
A person offered his store, etc. which we accepted.
After dinner, our kind attendant assisted in procuring planks;
the rooms were seated with such expedition,
that the people had notice and were chiefly gathered by half past four:
and a humble trust was renewed that the opportunity was owned;
and I was favoured with the reward of peace.

Next day had a meeting at Linwell's creek, held in a barn,
which was a time of heavy labour to me; and I gained not much relief;
yet I believe some minds there have been visited for good; and strong was my solicitude,
they might not rest in that which is polluted.
Next morning we proceeded towards South river, the roads very rough and hilly,
accommodations at taverns indifferent, particularly in lack of cleanliness.

We had upwards of three days' journey before we got among Friends.
The last night was a very trying one, at the house of a slaveholder,
there being no other to lodge at on the road,
otherwise it was wounding to nature and spirit to be with such.

We arose early in the morning, and got to South river about nine o'clock,
which we crossed, to a small town called Lynchburgh, where are several Friends;
and finding it was their meeting day, we took breakfast and hasted to it,
though five miles of rough, hilly road; and were there as early as some of the members.
It was close work, but we did not regret it,
being well satisfied in sitting with Friends, though a low exercising time,
in silent travail.

13th of ninth month, first-day.--I had informed Friends at Lynchburgh,
that I wished to have the company of their neighbours, both black and white;
and though the morning proved very rainy, yet there was a large gathering of people;
and though I thought myself clear of Friends,
great heaviness and exercise was again revived concerning them,
but when relieved from it, through further discharge of duty,
my way was opened towards others; and after meeting many of the black people,
who appeared much reached, came to us, and expressed their gratitude.
To this class, my companion and self in the course of our travels,
felt great love and sympathy.
A meeting was appointed in the town at four in the afternoon,
and held in a large room called Free Mason's Hall; which was filled,
and many stood without;
and though several appeared strangers to the doctrines of the gospel,
through the channel of free ministry, they were quietly attentive, seemed well satisfied,
and my own mind was relieved; so that we left the town next morning in peace.

We had a meeting on fourth-day appointed at Upper Goose creek,
and another in the evening at Lower Goose creek, ten miles distant;
which was largely attended, and an open satisfactory time;
concluding in supplication to the Father and Fountain of all good,
that the blessing of preservation might be continued to those,
who are sincerely desirous to walk acceptably before him.
From there we went to Seneca and Hill's creek, both small as to Friends;
but many seeking people attending; the regard of our Heavenly Father was manifested,
who is no respecter of persons, and gospel truths were largely opened:
the tribute of praise and thanksgiving ascending to his holy name, who is forever worthy.

On seventh-day had a long trying journey to Bannister, in crossing rivers,
etc. and had to beat about the woods till near ten o'clock,
before we could get a lodging place.

20th of ninth month, first-day.-- We sat their meeting, which was small of Friends,
but largely attended by others,
who mostly appeared so very raw and ignorant of the principles of religion,
that it was hard to fasten the testimony of Truth on such minds.
The iniquitous practice of trafficking in our fellow-creatures,
and keeping them in bonds, was closely spread before them,
which I expect was not very grateful, as few are clear in that part of the country;
but in the discharge of duty I was favoured with relieving peace;
feeling much sympathy with the few,
who are desirous to walk consistently with the profession we make.

We went forward that evening towards North Carolina,
and on second-day evening got to the first settlement of Friends there.
On third-day morning we attended a meeting at Eno, where, finding some kindred spirits,
and fellow-labourers in religious exercise, my spirit was comforted in the love of Truth;
and in silent waiting,
I thought I could adopt the language of the spouse in the mystical song:
"`My beloved is mine, and I am his.`"
This time of renewed favour to my own mind, was esteemed as a mark of Divine regard,
in order to sustain under future exercises, of which I had deeply to partake,
in attending the succeeding meetings in North Carolina.

These were Spring meeting.
Cane creek, Rocky river, Tyson's, Dixon's, Holly Spring, Euwary, Back creek, Hoover's,
Springfield, Piney Woods, Deep river, Marlborough, Providence, Sandy creek.
Center, Sherborne, Newgarden, Hopewell, Dover, Muddy creek, and Blue creek.
In all which I was led in a. line of close searching labour,
that ray work seemed indeed in the furnace.
I had also nearly to feel for, and sympathize with, the mourners in Zion;
and was favoured to feel peaceful quiet in the faithful discharge of duty,
which supported in a good degree of resignation, under the trials permitted.

We crossed the Blue Ridge a second time, to visit meetings in Old Virginia,
from which we were favoured to return in safety,
to attend the yearly meeting at New Garden,
having felt a release from proceeding further westward, to a small settlement of Friends,
two hundred miles distant, which I thankfully accepted.

The yearly meeting was largely attended, and held by adjournment seven days,
wherein several strangers from distant parts,
were engaged to labour for the promotion of good order among Friends.
After it was over, we staid two other meetings.
In the last my mind was instructively led in silent waiting,
to review the line of labour in which I had been exercised,
wherein I witnessed the gracious acceptance of Christ, to a female servant in his day:
"`Let her alone,`"-- "`she has done what she
could,`" attended with an encouraging belief,
that the renewings of Divine regard were towards his flock and family to do them good,
which I had to make some mention of, in much brokenness of spirit.

8th of eleventh month, first-day.--We were at Hunting creek,
where I had to labour among a mixed gathering, some of whom appeared very raw;
others I hope were sincere seekers after truth.
Near the close I requested to have a select opportunity with Friends,
in which I reminded them of the many deviations that appeared in many places,
some of which had caused great reproach;
and the earnest solicitude I felt on their account, as members of a new settled meeting,
was that they might watch and guard against every thing
that has a tendency to undue liberties;
in a particular manner on account of the rising youth.
I then felt a peaceful release;
and after a tendering opportunity in the family where we lodged,
we proceeded on our way to the next settlement of Friends.

We had upwards of one hundred and fifty miles of wilderness travel,
during which we had several times to seek lodgings,
and entertainment from house to house, on the road; and with difficulty obtained it,
after riding in the dark; and when obliged to stop at the houses of slave holders,
our minds were deeply affected on their account,
and that of the oppressed people under them.
Where openness appeared, we dropped some remarks respecting the injustice of the traffic,
in buying and selling their fellow-creatures.
We had also several large rivers, and deep creeks to ford,
several bridges being washed away by the sudden rise and rapidity of the waters;
but through providential care, we sustained no material hurt, and got to Cane creek,
in South Carolina, on seventh-day.

15th of eleventh month, first-day.-- We attended meeting there;
early my mind was renewedly humbled,
under a sense of the continuation of our Heavenly Father's love to the true seekers,
who are waiting for his law: on which subject gospel labour opened,
and though as too often is the case,
the solemnity of the meeting was much hurt by the late coming in of several,
there seemed cause to hope it was a profitable season;
closing in grateful acknowledgement to the blessed Author of all good,
whose compassions fail not, towards the children of men.

22nd of eleventh month, first-day.--At Raybourn's creek:
and I trust through the pouring forth of the Spirit it was a memorable day.
In the afternoon we had a religious opportunity among a few Friends,
and a tendering one next morning in the family where we lodged.
We then set forward to Georgia, two close days' journey,
and attended three meetings there.

29th of eleventh month, first-day.--At Allwood,
the nature and spirituality of the principle of Truth was opened to a mixed gathering.
From there we returned to Bush river, and stopped two days on account of writing.
On fourth-day proceeded to Charlestown, taking a small meeting in the way, at Edisto.

First-day, 6th of twelfth month.--This was another long and trying travel,
from which I would gladly have escaped, if a peaceful release had been granted.
As we drew near the city,
suffering of spirit became more heavily the secret attendant of my mind;
but I was favoured with a degree of hope,
that I could bear testimony with an apostle of Christ:
"`Tribulation works patience;`" and though I could not apprehend,
that we found one among those professing to be of our religious Society,
who acted consistently therewith,
I had to believe there was a seed groaning under oppression;
and that the regard of the compassionate Father was towards it as formerly.
We staid there a week, and through the faithful discharge of duty in public and private,
I was favoured with the reward of peace.

13th of twelfth month, first-day.--The last meeting we sat there was on this evening,
requested for the black people,
and such of their employers and others as chose to attend, in the City Hall,
a very large commodious room for the purpose, which was nearly filled.
The instruction given to the apostle Peter: "`What God has cleansed,
call not you common,`" etc. impressing my feelings with gospel authority, I stood up,
and humbly trust, spoke as the Spirit gave utterance.
A becoming attention appeared given to the illustration;
yet I seemed as if standing among scorpions,
and when the subject turned in a few sympathetic expressions
towards the peculiar objects of that meeting,
tending to draw their attention to what might
further open in the line of instruction to them,
a person stood up, who appeared of high rank, and said: "`Madam!
I am sorry to interrupt you; but as my office is the care of the police of this city,
I must desire you to stop; for what you say is against it, and will not do.`"

I was favoured meekly, but with firmness to reply: "`If you will please to have patience,
until I have discharged my duty, I believe you will neither have cause to be hurt,
or to be sorry that you have done so.`"
He then remained silent;
and the meeting ended in solemn supplication to that Almighty Being,
who is no respecter of persons.

Before we left the room, this person, who we found was the mayor,
requested a Friend to apologize for the interruption,
acknowledging it was not anything I had said, but the apprehension of what I might say,
that made him afraid; but hoped I should not take it as an affront.
I desired the Friend to inform him, I had taken no offence,
having nothing in view but the welfare of mankind;
yet I was afresh sensible of the little openness in these southern states,
to plead the cause of the oppressed:
and therefore but little room for the spirit of Christianity to spread.
We then set forward, having one hundred and sixty miles to travel,
and five ferries to cross to the next settlement of Friends.

20th of twelfth month, first-day.
-- We reached a meeting in North Carolina,
which was attended by a number not professing with us;
and though a time of heavy exercise to myself, and not so relieving as some others,
yet a little hope was afforded, that the labour was not wholly in vain.
In the evening, requesting the family where we lodged to sit down,
with several others present, I was closely led to open counsel,
that Friends might be more in the practice of gathering their children into quietude,
which appeared greatly neglected; and for lack of such care,
their minds remain barren and uncultivated,
and many seem more raw and ignorant than those who make no profession with us.

Several not of our Society, came twenty miles to attend the next meeting,
which through Divine regard, was an open instructive opportunity.
A grave elderly man with his wife,
(the former had been at meeting on first-day,) came to our lodgings and said,
the doctrines of the gospel had, in both those opportunities,
been fully and clearly opened to him, as he had never heard or remembered before;
for which he had cause to bless the Almighty.
His wife also hoped what she had heard that day, would never be forgotten by her.
They were by profession baptists.
We parted in tenderness of spirit, and my mind was made humbly thankful,
in hope the cause of Truth had not been hurt.

After dinner, we rode twenty-five miles towards the next settlement of Friends,
much by moonlight, of which we mostly take advantage, both morning and evening.
The third night of this travel we could get no lodging but in our wagon,
which we had before found more comfortable, than some beds we had been in.
Our brethren slept on the floor of the house in their clothes.
And in our little inclosure, after getting some sleep,
my mind was suddenly but pleasantly turned towards my friends at home,
as though sitting in meeting with them;
witnessing the renewing of that fellowship with some,
with whom I had taken sweet counsel, and gone up to the house of the Lord in company.

I thought I had scarcely ever felt the prevalence of best love,
more strong to the different classes of the people,
even to the most distant wanderers from the pure principle of Truth;
and for this fresh mark of the Heavenly Father's regard, in the night season,
my spirit was contrited.

27th of twelfth month, first-day.--We attended meeting at Neuse river,
in which I had to arouse carnal professors,
but to encourage those who were cast down on account of the low state of things.
From there to Upper Trent meeting, a time of close labour, both to professors and others,
in having to point out the states of the righteous and unrighteous,
and that such could not unite together in time, nor dwell together in eternity;
we went about twenty miles after meeting, and night coming on,
we missed our way in the woods, that it was near ten when we reached the Friend's house.
We were out early again next morning, though it rained heavily,
to reach a monthly meeting at Core-sound, full fifty miles distant;
in which my mind was early impressed with the
remembrance of what our blessed Lord spoke of,
that a man's enemies were those of his own household, which was much enlarged in my view,
to my own instruction.

