== Chapter VIII.

Further labours in America in the year 1796.

We proceeded to Stephentown, about eight miles of such extremely rough, hilly road,
as was very fatiguing to the body;
and the appearance of the people at a meeting appointed in the evening,
was not less discouraging to the mind; for they seemed to come as if to merriment,
rather than to a religious opportunity; yet there was cause to hope that,
through a trying labour,
some minds were reached and brought into quietude by
the power of Truth but as in the outward,
so in the inward, cultivation is much lacking.

On third-day, at East Hoosack, in the renewings of gospel authority.
Truth was declared, tending to encourage the rightly exercised,
and awaken such as professed with us, who were too much settled on the lees of formality.
We proceeded that evening, about twenty miles, on our way to White creek,
lodged at a poor tavern, and got in time for their meeting next morning;
in which things appeared very low.
This was also the case at Pittstown, where we attended meeting next morning;
but we were comforted in the company of a young woman,
who had been confined to her bed nearly eleven years, through bodily weakness,
which she seemed to endure with much cheerfulness;
her mind being conversant with the Spirit of Truth.
She had a much clearer sense of the state of Society,
than many who are able to attend meetings.
We parted with her in near affection; and reached Saratoga that evening,
where we rested sixth and seventh days, at the house of very agreeable Friends,
to recruit bodily health, having taken cold.

3rd of seventh month, first-day.
We attended meeting at Saratoga, which was large, and a time of close searching labour;
but in the faithful discharge of duty, I was favoured with the reward of peace,
which is a support under bodily trial.
We got to Easton next morning, in time for the meeting, a very large mixed gathering;
and great was the desire of the people to hear the gospel preached,
that for a considerable time I was led to apprehend it would please Infinite Wisdom,
to permit a peaceful release in silence; but when we had sat nearly the usual time,
I rose with little expectation of saying more than what had been my feelings,
respecting the strong desire to hear the sound of the gospel through instrumental labour,
rather than to attend to that by which it is preached in every mind;
but before I could feel at liberty, many things opened,
setting forth the purity and spirituality of the principle we profess;
and that those amongst us who were got no farther than form or tradition,
would be no better than such among other professors.

On fifth-day, the monthly meeting at Danby,
tended much to the relief of my oppressed mind, the Spirit of Truth opening counsel,
in a close testimony against wrong things;
also for the information and encouragement of those who
were truly seeking after the knowledge of it.
The meeting for discipline held very long.

By the minutes, the number that had applied for membership appeared great;
which I was glad I knew nothing of, before the preceding meeting,
wherein I had to remind Friends that it was a time of
much requesting to become members of our Society,
and that a very ready admission of such, might multiply the numbers,
but not increase the church's true joy;
which could not be promoted by any means short of coming in at the right door, by Christ,
the way, the truth, and the life, I had been for sometime willing to hope,
that Danby monthly meeting would be the extent
of our wilderness travel in this yearly meeting;
but I found my mind still drawn forward, and in desiring resignation to the divine will,
was strengthened to proceed.
Next morning soon after sunrise we journeyed on, and rode by moonlight in the evening,
before we could get to a suitable lodging place.
The people were gone to bed, and unwilling to let us in,
but by entreaty were at last prevailed upon;
and though we got very little for ourselves or horses,
we paid a higher price than for much better fare in England, which is often the case.

10th of seventh month, first-day.
We attended meeting at Ferrisburgh, and in the evening one at Monkton;
in both which were a considerable number not of our Society,
to whom the way of Truth was opened; and those who made profession of it,
were reminded of the necessity of walking consistently therewith.

We went a few miles that evening, on our way to the Grand Isle, in Lake Champlain.
On our way, much rain having fallen, the prospect was discouraging,
of travelling through the woods,
where in many places it was difficult for the horses to pass one after another:
we had left our carriage at Ferrisburgh.
On the third day's journey, after riding about eight miles, my companion, myself,
and a woman Friend in company, were obliged to take to a boat,
though very small and poor, not much bigger than a canoe,
having three miles to go on the water, part of which was a disagreeable swamp,
that sometimes our shattered bark seemed ready to stick fast.
Our men Friends had also much difficulty in getting along with the horses,
being sometimes nearly plunged to their shoulders in sloughs,
and having a mile to ride in deep water.

We could not but esteem it a great favour, that during our passage it did not rain,
but when we got to the other side, it came on heavily, and continued several hours.
We set forward again when it cleared; and being favoured with a secret evidence,
that the Lord had a seed on that Isle, which he designed to visit,
and bring to the knowledge of Himself,
I was therefore thankful that resignation was wrought in me,
to obey his will in going there;
some being already measurably convinced of the principle of Truth.
My way seemed opened to call on these in their families, as we passed along:
a Friend and his wife being along with us,
who were under appointment to visit one of the meetings,
could inform us where they lived.

Rising early next morning, and going down the lake in a canoe,
we sat with most of them before meeting, which began at eleven.
Public notice being given, a large number came, among whom, as I was afterwards informed,
was a Presbyterian minister, who lived about eight miles distant,
and had been much prepossessed against women's preaching,
but was observed to sit very solid and attentive.
Feeling the word of life to arise,
I had early to point out the opening of the gospel day,
and the memorable conference between our blessed Lord and the woman of Samaria.
A humble trust was raised, that things opened as the Spirit gave utterance,
to the information and instruction of many present.
When clear of those not yet of our fold, I requested such as professed with us,
and any of their families that inclined, to stop a little;
when caution and counsel farther opened,
respecting those acquainted with the teachings of the Holy Spirit,
pointing out the importance of attending thereunto,
that they might witness preservation themselves, and become as way-marks to others.

After dinner, we left them in near affection,
and took a boat to cross another part of the lake, about four miles over;
in which Friends were kindly assisting, taking our horses in a scow,
and us in a sail boat.
We went about six miles further that evening, towards another settlement of Friends,
and lodged at a poor tavern.
We set off about sun-rise in the morning; but our way being through thick woods,
and many deep sloughs, we were more than five hours,
in going what was called fifteen miles.
A Friend who led the way, on one of our carriage horses, got so deep in the mire,
that he had but just time to dismount, before the horse sunk to his shoulders;
but by the care and activity of men Friends in company,
he was got out without receiving much hurt;
and we did not meet with another place so bad, though we had to dismount several times,
and walk on logs.

The meeting at eleven, proved a trying time of heavy exercise;
but it felt right to appoint another in the evening for those not professing with us,
which was also a laborious season,
and seemed as though little ground was gained on the right side;
that I wished to experience that situation of mind the Apostle mentions,
who had learned in all states to be content.

Next day, we had another rough trying travel, and lodged at a tavern, near the lake,
which we crossed next morning; and in the afternoon reached Ferrisburgh again.

17th of seventh month, first-day.
We attended their meeting,
in the afternoon had religious opportunities in some of their families,
and on second-day morning proceeded towards Queensbury.
On fifth-day many not of our Society assembled; an exercising season it was,
in silent suffering with the seed, under a painful sense,
that too few were sincerely desirous of becoming acquainted
with the nature and spirituality of Christ's kingdom,
or the religion he teaches, which makes the tree good,
and washes clean the inside of the cup and platter.

Of this, near the usual time of concluding a meeting,
I found an engagement to point out the necessity, in the ability received,
and to hold forth the language of encouragement to Zion's travellers;
hoping there were a few names that had not denied the faith,
but who desired to love the Truth above all other things;
with whom I felt fellowship in the bonds of the gospel.

24th of seventh month, first-day.
At Greenfield, a small number of Friends, and a great number of other people attended,
who seemed strangers to the nature of religion,
that my spirit was much oppressed among them for some time; but,
through a painful exercising labour, I got a degree of relief;
and on silently pondering as we rode along,
the cause of such deep wading on account of others,
an instructive intimation opened on my mind,
that those who are filling up their measure of suffering which is yet behind,
for the body's sake which is the church,
have a portion to bear of the deviation of others, among whom their lot is cast;
and to wait the appointed time, until help is renewed by a superior power,
is indispensably necessary; so I much desired in all states to be content,
if only favoured with the blessing of preservation to see and do right.

The next day, at Gralloway, a large number attended not of our Society;
and on first sitting down I was ready to feel dismay,
lest it should prove such a meeting as the preceding;
but a profitable quiet spreading over us,
I had to believe there were many seekers after Truth;
and in the renewings of gospel light and love, I had to point out what it was,
where to be sought, and how to be found; and that it would be exalted in man,
above all outward and shadowy performances, by giving victory over sin and evil,
which none of these could do.

The next day at Ballstown, a small exercising meeting,
too much of a self-righteous spirit was prevalent.
That evening, we returned to Saratoga, and attended their monthly meeting.
After sitting in silence some time, a remark or two impressing my feelings, I stood up;
and my way was altogether unexpectedly opened, in a close searching testimony,
tending to lay waste that righteousness which is no better than filthy rags.
I had to point out some particular things,
on which many were in danger of laying greater stress,
than in attending and directing others, to the inward cleansing Spirit of Truth,
the power whereof would lead to a consistent walking in all respects;
but the form without it would do little.
I was sensible such plain dealing went hardly down with some;
but my peace consisted therein, of which I largely partook from my blessed Master,
whose secret power upheld and sustained, beyond all that could oppose, within or without.

That evening, we had a humbling precious opportunity,
in the Friends' family where we lodged; and early in the morning,
took leave of them in tender love, proceeding to Albany, about thirty miles,
where we had a meeting the same evening.
My bodily frame was greatly oppressed with the heat of the weather,
and during the night there was an awful storm of thunder, lightning, and heavy rain,
that I was ready to query whether there was any sinner in Zion,
that would not be made afraid?
or hypocrite, that fearfulness would not surprise,
at such a display of the Omnipotent Hand?

31st of seventh month, first-day.--We sat two meetings,
both deeply exercising in silent wading, till near the time of breaking up the latter,
when I felt a commission to speak.
The remembrance of the prophet being sent to visit the children of the captivity,
and sitting where they sat, in silence and astonishment, for the space of seven days,
had been much opened in my view.
Some close expostulations were dropped, and the tried travellers Zion ward,
encouraged to hold on their way.
We purposed leaving early next morning, but my health did not admit of it.
On third-day after a humbling opportunity at our lodgings, we set forward for Crum Elbo,
where a meeting was appointed next morning, and was fully attended by Friends and others.
The Shepherd of Israel was graciously pleased to own us, by the breaking of bread,
to the encouragement of Zion's travellers, and instruction of others.

That afternoon, we proceeded on our way to Clinsophus,
and next day attended their meeting,
in which I was engaged to labour in the ability received,
to feel with the seed and to administer such counsel as Truth opened;
and though it was a low exercising labour, I felt inward quiet.
After dinner we had a stony, rough travel, towards Newburgh Valley,
where a meeting next day seemed fully attended by Friends and others,
though in the height of their harvest;
and my mind became early humbled under a secret sense of the hovering of divine regard,
in accepting and owning the dedication of the people,
in leaving their outward callings to wait upon Him.

We went that evening to New Marlborough, where a meeting was appointed next morning,
in which for a time, my mind was exercised in a low travail, I believed,
with the seed and for its sake.
As preservation was witnessed to abide therein the appointed season,
the consoling evidence of Truth arose in this language:
"`Zion knows her rest:`" which remains the dwelling place of the righteous;
and in due time, my way was opened to enlarge thereon, in communication,
I trust to the help and encouragement of the true travellers;
also in expostulation to the different states of the
people and my spirit bowed before the throne of grace,
for the continuation of Holy help, to carry forward his own work.

7th of eighth month, first-day.--We attended their meeting;
and after a season of much inward poverty,
my empty vessel witnessed a fresh supply of the divine anointing,
and I was enabled to speak of things as the Spirit gave utterance;
opening counsel to the learned and unlearned in religious matters;
with a call to such as are living from under the fear of God.

On second-day, was a select meeting at the same place,
in which the members of two monthly meetings united;
some encouragement to the tried travellers was given to communicate.

On third-day, the select quarterly meeting was held at Nine Partners,
wherein further counsel was opened to that part of the body,
which I believe was well received.
Next day that for transacting the affairs of the church, was held;
a large number of Friends assembled, and Truth opened my way in discharge of duty,
I humbly trust, to the instruction and encouragement of many,
and to the relief of my own mind; though it was very unexpected when I left these parts,
that my lot would be cast there again.

On fifth-day was held a public meeting, largely attended by those not of our profession,
wherein several testimonies were borne; yet it felt an exercising season,
both in silence and while engaged in communication;
leaving a secret impression heavy on my mind,
that though many loved to hear the gospel preached, it might be said as in former days:
"`Who has believed our report?
etc.`" the painful evidence continuing with me,
that many were much in the state of the people,
among whom our blessed Lord did not many mighty works, because of their unbelief.
That evening we left Friends in nearness of spirit, proceeding some miles on our way.
Next morning we parted with Abraham Underbill, a valuable elder,
who had accompanied us many weeks.
Feeling near regard, the separation was a fresh trial;
yet believing the right time was come for his leaving us,
we were enabled cheerfully to resign him,
under those tendering impressions that unite the children of one Father.

14th of eighth month, first-day.--We were at Cornwall,
the particular meeting of which David Sands is a member,
who is now on a religious visit in Europe.
In the early part, through the renewings of gospel fellowship,
and under the influence of that love which many waters cannot quench,
my spirit was united to his; and contrited in considering,
how it pleased unerring Wisdom to call forth his
servants from one part of the vineyard to another,
to publish the gospel of peace; yet through the remaining part of the meeting,
I was made fully sensible that unless there was a
willingness in those that heard the sayings of Christ,
to become doers thereof, all the labour bestowed would be unavailing.
I was engaged to press home to the consideration of those present,
the importance of the subject; and in the discharge of my duty felt peace;
parting with some individuals in much tenderness of spirit.

The next settlement of Friends being seventy miles distant,
we went part of the way that evening, and on third-day morning,
were at meeting at Hardwick, in New Jersey;
which was a season of deeply exercising labour, but in resignation thereunto,
sustaining hope was granted, that fragments necessity to be gathered up,
were offered to the people.

On fourth-day at Kingwood,
in the meeting my mind became humblingly impressed with a belief,
that a gracious regard hovered round a backsliding people,
in order that they should return, repent and live; and through a renewal of strength,
I was enabled to discharge my duty,
and was favoured with a secret hope that the labour would not be wholly in vain.

21st of eighth month, first-day morning at Trenton meeting,
many attended not of our religious Society, several of them esteemed of the higher rank;
among whom a renewal of strength was vouchsafed, to open the Truth as professed by us;
to exalt its power above all the contrivance of men; and to remind our own members,
what manner of men and women we should be, if we acted consistently therewith,
agreeably to our holy profession:
and I was favoured with a sustaining hope that the cause did not suffer.
In the evening at Bordentown, I had again to labour in a mixed gathering,
having to believe there were some tenderly visited minds;
yet that others present were tinctured with infidelity.
That evening we went home with Nathan Wright,
husband to my endeared friend Rebecca Wright, before mentioned.

On second-day at Crosswicks, we had a very large meeting,
which gathered into quietude becoming the dignity of such assemblies;
and a tender spirited handmaid, young in the ministry,
was commissioned with a call to come out of Babylon; when suddenly was opened,
the remembrance of Mystery Babylon, where was the harlot and false prophet;
and as my spirit became weightily baptized with the impression,
I trust I was enabled to speak as the Spirit gave utterance;
and through an exercising labour in the discharge of
duty to the different classes of the people,
I experienced inward quietude.

From Crosswicks we went to a meeting called Robins's,
and on third-day morning were at Upper Freehold, a large meeting,
particularly of young people,
wherein the humbling display of divine kindness was graciously manifested,
in a peculiar manner; and I trust it will be a memorable day to some.
In this meeting my dear companion,
who had been for some time under the preparing hand of her Heavenly Father,
for the work of the ministry, yielded resignation to his will,
in publicly espousing his cause, to the humble rejoicing of my spirit.

That evening we went home with M. Newbold, a living minister of the gospel.
On fourth and fifth-days, we were at Upper Springfield, Shrieve Mount, and Vincent Town.
The greater part of the last meeting were not of our Society;
and through divine regard it was an open time of labour, though under much bodily trial,
from the extreme heat.
On sixth-day morning, we were at Mount Holly,
the particular meeting of which that dignified servant of Christ, John Woolman,
had been a member; but low indeed is now the state of it,
and painfully exercising was the labour;
yet not without a sense of near sympathy with the lowly travellers.

In the evening, we were at Rancocas, wherein a solemn call was proclaimed,
to remember their latter end, with many gospel truths pointing out the danger of delay;
which I hope had a humbling effect on some.
On seventh-day, we attended the select quarterly meeting at Burlington.

28th of eighth month, first-day.--At Burlington we attended two meetings for worship;
and I was thankful to feel quietude in silent waiting,
while other servants were employed in bearing testimony to the Truth.
On second-day the meeting for business not beginning till the eleventh hour,
which I think a great loss of precious time, the heat was so extreme,
and the air so oppressive,
that my bodily frame seemed scarcely able to support its feelings;
yet I was favoured with patient resignation,
and before the meeting ended I got some relief,
by a renewed display of the Omnipotent hand, though awfully exhibited in thunder,
lightning, and heavy rain, which appeared to bring solemnity over many minds;
when my way was opened to bear testimony to His Sovereign Power,
whose dispensations are all in wisdom;
and the meeting closed in supplicating his High and Holy name,
that the blessing of preservation might attend His flock and family.

We went home with my dear friend Rebecca Wright, and attended their meeting at Mansfield,
on fourth-day, a very large gathering, the more so on account of a burial.
My mind became exercised before the Lord;
and under a sense of the great cause I was engaged in,
my cries were strong to Him in secret, for preservation in the discharge of duty.
When rising on my feet I felt it to be in fear and trembling;
for while sitting under the renewal of baptism, I had to believe,
that the state of the meeting was very complicated.
But it is only for you to read.
Oh! fellow-traveller, you who are able to do it, in a similar line,
what it is to be so engaged, and how great the care and watchfulness which is necessary,
even when under the holy anointing.
The states of the people are opened like flowers in a garden,
some appearing beautiful to the eye, and affording a pleasant savour;
others of a contrary appearance, yielding an offensive smell;
others having little or no scent.
To know how the culturing hand should be turned upon these, in order to help,
is indeed a weighty matter; and nothing short of that adorable Wisdom,
which alone is profitable to direct, can accomplish it according to the divine will.

Having laboured in the ability received, I felt the reward of relieving peace,
which marvellously supported the outward frame; a great solemnity was over the meeting,
and a becoming attention to what was delivered.
If any good was done, I am thankful in knowing,
the praise is due only to the blessed Author of all good.
It being their preparative meeting day,
women Friends were left to transact their part of the business,
when I found it further my duty, to expostulate with the mothers of children,
and such as had them under care, that no undue liberty or wrong indulgence,
might be allowed on their parts;
some of which were pointed out and closely cautioned against;
and the great Name was supplicated for the preservation of the lambs of the flock,
who are brought under the forming care of the Heavenly Shepherd.

On fourth-day, at Old Springfield, many attended not in profession with us;
and the truths of the gospel were again opened, and I trust,
had a reaching tendency in some minds;
yet there seemed a painful prevalence of the spirit of unbelief in others.
I was afterwards informed that some then present, had openly declared such sentiments;
but a hope was expressed that they might at that season be a little reached.

In this neighbourhood we lodged at Nathan Wright's;
and we had the company of some of my companion's near relatives from New England,
which seemed like a little encampment by the wells of water, and palm trees;
but for the work's sake we had now to be separated.
On sixth and seventh-days we were at Mansfield Neck and Makefield,
both seasons of close exercise, in sympathy with the seed under suffering,
and of labouring to awaken carnal professors.

4th of ninth month, first-day.
At Plumstead, in a large mixed gathering;
in the early part of it my mind was afresh brought under close inward exercise;
the remembrance of our blessed Lord's enquiry concerning his servant John,
"`What went you out for to see?
A reed shaken with the wind, etc.,`" seemed so applicable to my inward state,
that I felt much bowed in renewed desire, to know and do the divine will,
if any opening should arise therefrom, to communicate to others;
which after a time of silent waiting became my engagement, and though laborious,
I was enabled to discharge my duty to several classes of the people;
for which I felt the consohng evidence of peace,
the only sure reward of those who desire to be faithful.

On second-day at Buckingham, a very large monthly meeting, was an open time of labour,
previous to transacting the discipline of the church.
We then attended the following monthly meetings, in the same county, namely:
on third-day, Wrightstown; fourth-day, Falls; fifth-day, Middletown;
all which were seasons of exercising labour, both in worship and discipline:
the latter appearing to me painfully unsettled,
in part occasioned by the admission of those not
of our Society to see the passing of marriages,
and the great aptness of too many of our own members to go in and out.
I endeavoured faithfully to discharge my duty, in warning the unruly,
and encouraging those who are concerned for the welfare of Zion;
enjoining parents of children, and those who had the care of them,
in much sisterly sympathy and affectionate solicitude,
to be more religiously engaged to have them
under right government and subjection at home,
and then I believed they would conduct themselves better at meetings.

On sixth-day morning, a meeting appointed for the black people,
under the care of Friends in that quarter, was fully attended,
and I trust was a time of instructive,
sympathetic labour through which I hoped some would be encouraged to do well.
That evening we were at a meeting at Bristol,
largely attended by those not of our religious Society, wherein, I trust,
the doctrines of the gospel were opened, and reached the witness in many minds.
We crossed the river to Burlington by moonlight; and for lack of sufficient hands to row,
were about an hour on the water, but were favoured to land safe,
and were again kindly received by the family of our valued friend John Hoskins,
who had been acceptably and encouragingly with us, in our travels in that neighbourhood.
Next morning, we rode fifteen miles to the monthly meeting of Upper Evesham,
rather a newly settled one;
and I rejoiced to find Friends under the weight and exercise thereof,
that things might be rightly conducted;
and a testimony went forth to animate and encourage them,
in the continued discharge of duty, that none might grow weary or faint by the way.

11th of ninth month, first-day.
At Old Evesham, we were at a very large mixed gathering,
wherein many minds felt to me to be greatly afloat,
far from being gathered to the house of prayer; and for a considerable time,
the heavens seemed to me as brass, and the earth as iron,
and my way was shut up as in thick darkness; but after the dedication of some others,
in giving up to the pointings of duty, light broke forth,
and counsel was opened in a close line, yet encouraging to the faithful,
to the relief of my own mind.
We went home that evening, with Martha Allinson, a valuable Friend,
who was left a widow with a large family of children;
and being religiously concerned for their welfare, the divine blessing has attended,
so that it was pleasant to be under her roof.
A religious opportunity with them was in a very encouraging line.

On fifth-day, the 22nd, we were at the monthly meeting at Byberry,
where the children of a large school under Friends' care were requested to attend.
Towards them and others much counsel was opened by several strangers then present,
and a hope was raised that some part at least, might be as bread cast on the water.

On sixth-day, we attended the quarterly meeting at Haddonfield;
that for worship was a large mixed gathering,
which has often appeared to me to obstruct the opening
of counsel to the members of our own Society.
I found nothing with clearness to communicate, till in the women's meeting,
when my mind became much dipped into sympathy with a number,
exercised for the cause of Truth; and I trust there was great openness to receive,
what appeared right to spread among them.

On seventh-day morning, we crossed the Delaware to Philadelphia,
in company with several Friends, and got in time, to the meeting of ministers and elders,
being the commencement of the yearly meeting, 24th of ninth month,
which held by adjournment till the evening of 1st of tenth month;
and such meetings as I attended among brethren and sisters,
were mostly conducted in a solid, weighty manner,
tending to the help and instruction one of another.

The women's meeting was much larger than I had ever before seen;
and there was great openness to labour therein, both in ministry,
and for the well ordering of the discipline of the church.
At this season,
the further consideration of admitting black people into membership with Friends,
was revived; and a large committee was appointed,
wherein concerned women Friends were admitted.
Their weighty deliberations felt to me to be evidently owned of Truth;
the result whereof was, that no distinction of colour should be an objection,
when such as requested to be joined with us,
appeared to be convinced of the principles we profess.
This being spread before the yearly meeting, was united in, without a dissenting voice.
Friends had also under their notice, the continued care of the native Indians,
as opened the year before;
likewise the establishment of a large boarding school for Friends' children.

Several women Friends with myself, attended these committees;
and great appeared the care and benevolence of many, on these interesting accounts;
wherein they had my near sympathy and sincere solicitude,
that they might be strengthened for the work.
I attended about thirty sittings, and was renewedly supported beyond expectation;
several more select opportunities at our lodgings,
were preciously owned with the renewed offers of heavenly love.

2nd of tenth month, first-day.
We staid the morning meeting at Pine street,
then had a tendering opportunity with many near and dear Friends,
and proceeded on our way to Baltimore.
On third-day, we crossed the Susquehanna; on fourth-day we were at meeting at Deer creek;
fifth-day, at Fawn; and sixth-day, at Gunpowder; and reached Baltimore that evening,
in company with dear John Wigham, who fell in with us at the last meeting;
and we were enabled to labour together in gospel fellowship.
On seventh-day, was the meeting for ministers and elders preceding the yearly meeting,
wherein +++[+++ had very close labour, having to point out, in much plainness of speech,
the neglect of parental care and authority over the children;
so that many of those belonging to that rank of the family, were stumbling blocks,
instead of ensamples to others.
I believe the evidence of Truth so made its way, that none were offended;
but I hope were rather animated to greater watchfulness over their families.

Several of the sittings, in transacting the discipline, were so oppressive,
and the life so low, that secret mourning was the portion of many exercised minds;
until it pleased Infinite Wisdom to disperse the cloud,
in favouring with ability to discover the hidden things of darkness,
and to point out the cause, why Israel could not journey forward.
It appeared convincingly clear, that, among other things which needed searching into,
the young children, and those more grown up, among the black people under Friends' care,
were greatly neglected; from a sense whereof, it became the judgment of the meeting,
to appoint a committee to visit the families of such,
in order to feel after the pointings of Truth for their help every way;
which prospect was laid before the men's meeting, and so made its way,
that a number of men and women Friends were appointed.

Much labour was also bestowed, for the help of the young people assembled with us;
though the minds of many appeared so afloat, as scarcely to admit of any impression;
but some were much tendered,
affording ground to hope it would tend to their lasting profit.
On seventh-day the meeting concluded,
under the renewed prevalence of our Heavenly Father's love

