== Chapter XI

[.chapter-synopsis]
* Her voyage from America.

17th of tenth month, 1797.--I embarked with the dear Friends before mentioned,
and when the loved objects of tender regard had left us, and were no longer to be seen,
after a little retirement, I was fully employed in helping to arrange matters,
for the accommodation of my dear friends and fellow passengers.
Mary said, it did her good to see me so lively, but feared I should be overdone.
I told her I was doing that then, which perhaps I could not do tomorrow;
and so it proved, for towards evening the ship began to roll,
and my head somewhat to roll with it, that I was glad to return to bed.
The wind has been rough, and sometimes a-head,
yet we got along pretty well in a tossing way.

On seventh-day afternoon,
we were somewhat alarmed by the appearance of a frigate at some distance;
which chased us, and fired several times, so the captain lay to.
She proved English, going to the West Indies; the captain came on board,
examined the ship papers, and then returned to his own vessel.
I felt a good deal tried when I first heard the report,
but was soon favoured to remember, that One mightier than man rules;
and my dependence became more firm upon the right support, and fortitude was replaced;
for which I felt thankful.
It was also strengthening to know, that I had fellow servants on board;
though our weapons were not carnal,
the hope was revived that they would be found mighty through God,
to sustain in the needful time.

I have not been in the cabin since the day we came into the ship,
but hear and see enough, to make me sympathize with my beloved brother J. Wigham,
who is nearly surrounded by sons of folly; though they behave pretty civilly as men,
but appear to have as little claim to Christianity as most I have met with,
that don`'t esteem themselves among the profane.
Dear Mary Swett I am informed, has given them a little counsel once or twice,
which seemed to have no other effect, than to raise ridicule in some of them,
and in none more than an Englishman, who declares himself an Universalist.

The captain is civil and attentive, and I believe would be more so,
if he had not such a company about him, towards whom he seems readily to yield.
The mate appears a steady man; and the sailors as quiet as most I have known.

How different our situation to what it was in the Barclay,
when fellow-helpers made way for, and loved to come together to wait upon the Lord,
for the renewal of strength; and when, as iron sharpens iron,
so did our countenances one another`'s! We have such a company now,
that no way seems to open for even the little band coming together.
On first and second-days, we went most of the time nine knots an hour before the wind,
with only three sails up, and the sea running high,
tossing and rolling almost incessantly.

On fifth-day, the clouds gathered, the wind was very high,
and the sea dashed over the vessel, more than any day before;
which verified the impression I had pleasantly mentioned to Charity Cook,
before its coming on.
In the evening, I sat up a little,
and was favoured to witness the beloved of my soul coming to his temple;
(truly his reward is with Him!) contriting my spirit, and enlarging my heart in his love,
which sweetly flowed towards my beloved friends on both sides the great deep;
who seemed brought near, in a manner scarcely to be expressed:
my soul was poured forth in prayer,
for the flock and family of our God wherever scattered; and faith renewed,
that the little band within this trying inclosure, would in his own appointed season,
be safely conducted to the desired port; in which hope I retired to bed.

On seventh-day, I sat about an hour in the cabin;
some of the company professed to be glad to see me, said I was a great stranger, etc.
I told them I did not know but I should have oftener come a little,
but they made so much noise, laughing and talking,
that my head had enough of it in my own apartment.
One of the young men from Carolina, made some excuse,
alleging that there were many of them,
and sometimes conversing on subjects they did not well understand;
and so the matter ended, for they seem so much strangers to serious things,
that little ground can be gained by expostulation;
and I believe it is best to labour for patience to have its perfect work.

29th of tenth month,
first-day.--The vessel going with a steady motion from five to seven knots an hour.
About half past ten, our little band went into the cabin and sat down quietly together.
I believe some of the young men were aware of our motive; one of the elder,
and if possible more light and talkative than the rest, kept asking them questions,
till Mary Swett said something to them, and they became more still,
but did not wholly refrain from conversing.
I was favoured with an inward quietude, attended with a secret hope,
that Truth would rise so as to gain some present victory.

Soon after dear Charity Cook appeared in solemn and reaching supplication;
she had also something further in close testimony, during which time they were quiet.
Then did the secret fire kindle in my heart,
and I had to seal and strengthen what had gone before;
and to speak to the elderly man in particular, of the example he set the younger,
telling them plainly, that nothing short of becoming the followers of Christ,
would make us Christians; to the truth of which some of them openly acknowledged.

What cause of thankfulness have those, who are taught in a different school,
to become the followers of Christ in the regeneration, and who as dear children,
unfeignedly desire to serve him, according to the manifestation of His holy will.

On deck a little after dinner; the sea very smooth, scarcely any wind.
The mate thought we did not get forward at all; I reminded him,
what daily dependent beings we are, on a power superior to that of man;
which I believe he had a mind capable of acknowledging.

Third-day.--Unstable is the element we are upon;
the calm was succeeded by what I have been ready to call a storm; however,
we get fast on our way, which is a comfort.
On fourth-day, the sea ran very high, broke over the quarter deck,
and the companion doors.
By the log we have come one hundred and thirty-six leagues, in forty-eight hours.
Last night, one of the yard-arms was taken away,
but no other damage done that I have heard of.

Fifth-day.
-- The ship still keeps rolling, though we have not gone so fast to day,
as for some time past.
I have felt rather more relieved from bodily trials:
my brother J. Wigham thinks I am abundantly better this voyage, than before.
He is not so well, which I marvel not at,
his surrounding shipmates being of such a different class.
Dear Charity Cook is much the best sailor of us three women, and frequently visits me,
when she can get across the stairs.
The present state of my mind is well suited to my situation;
for I feel it no trial to be much alone, and in silence;
yet have no desire to be thus living to myself, when the All-wise disposer of events,
sees fit it should be otherwise.

Sixth-day.--It was calm part of last night;
but I awoke about four o`'clock with the usual feelings, preceding a change:
the wind soon blew hard, and the sea rose so high,
that the main deck has been knee deep most part of the day;
yet notwithstanding these commotions without,
my mind has been favoured to feel as perfect a calm, as at any season I remember.
The captain thinks we are about twenty degrees from Liverpool.

Seventh-day.--A very trying time indeed till the early part of this morning, when,
for the first time,
I felt a petition raised in my heart that bodily
suffering might be mitigated by a stiller getting along;
and though I dare scarcely think I am worthy that such a desire should be granted,
I am thankful in knowing we had a very favourable day,
so that I got into the cabin after five days retirement in my little dark apartment;
for such it is, except when the lamps are lighted.
Some of the passengers are ready to hope we shall land in a few days; but that I resign,
and leave among the hidden things, not knowing what trials may yet overtake us.

5th of eleventh month, first-day.--I awoke from a trying dream,
with thoughtful reflections; remembered it was the first-day,
and considered how we should get together,
and whether any of the ship`'s company would be
religiously desirous to sit with our little band;
but all seemed wrapped up in such a mist, I could gather nothing from it;
so concluded to leave it till nearer the hour.
I was informed a ship of war was in view, with English colours,
only little wind at the time, and that in their favour.
The captain discovered it to be a French-built vessel.
They presently boarded us, and showed themselves Frenchmen, not by any uncivil act,
for they did not so much as fire a gun.
When they came into the cabin, E. W. who was with me in my little room,
thought if I would go it might have some reach upon them; to which I had no objection;
for my mind was favoured, through Divine help, to witness much quiet resignation;
and I entered the cabin with as much calmness as I had done at any time.
I knew it was the Lord`'s doing, thus to strengthen; and it was marvellous in mine eyes,
for I think no one can feel a greater trial either of nature or spirit,
than the prospect of falling into the hands of unreasonable men, was to me.

Soon after I sat down, poor James, the cabin boy,
who set up a lamentable cry when they came on board, followed: I called him to me,
for I pitied the child,
and in a whisper gave him some advice which seemed to quiet his agitated mind;
and desired E. W. to tell the other Friends where I was, who presently came.

The men who examined the papers appeared about middle aged,
and rather docile than hostile, and spoke English easy to be understood.
They seemed satisfied respecting the vessel;
said they were out on a three months cruise from Bourdeaux,
had only met with three small vessels--were going towards the
Western islands--and had forty days still to be out.
Fearing their bread would fall short, they requested the captain would let them have some.
After some consideration, most of the passengers appearing willing, he consented,
letting them have as much biscuit as he could spare, and one cask of flour;
for which they paid hard money.

When the boat returned with sacks for the bread, a young man came along with them,
who had an innocent countenance, who could also speak English.
He said we looked like the Nuns in France.
I told him we were Friends or Quakers,
and inquired if they had heard of such in their country.
They replied, yes.
I asked if they knew any there.
They did not know of any yet, but believed they would some time.
I further inquired if it was not very disagreeable to be sailing about on such business?
whether it would not be much more pleasant to be tilling the land,
and reaping the peaceable fruits of it, or following other useful employments?
to all which they pleasantly answered in the affirmative,
and thought peace was best for all.
They asked us to certify at the bottom of the receipt for the money,
that they had behaved civilly on board our vessel,
which was done on behalf of the passengers and captain.

This event somewhat accounts for the cloudy prospect of our meeting,
which was not obtained in a collective capacity;
yet there is room to hope a small renewal of strength was felt in private retirement;
and we were renewedly helped to bear the trials of the day,
by hearing E. W read a part of the journal of Job Scott;
which peculiarly sets forth his deep and manifold exercises,
with his hope and confidence in God, through them all.
Indeed, concerning what the Lord is pleased to allot to us for our refinement,
it becomes every resigned follower to say: "`Not my will, but yours, O Lord! be done.`"

Second-day.
A strong head wind and foaming sea, were our attendants last night,
worse than any time before.
I was very much tried with pain in my head and stomach,
and could scarcely keep myself in bed, from the violent motion;
but the trials of the night were followed by greater, and repeated ones in the day;
a French privateer came up with us, and fired for us to lay to,
which was done accordingly; when four men armed with cutlasses came on board,
two of whom searched the cabin, while the others took our captain on board the privateer.
We knew not for a time but he was taken close prisoner, and we soon likely to follow.

I believe our feelings at that time can scarcely be described; yet,
through adorable mercy, all confidence in the unfailing arm of the Lord, was not lost;
whereby I was enabled to sooth and encourage dear E. W. who sat by me weeping.
I thought it was almost impossible for me to rise;
but hearing that the man called the prize-master was searching our trunks,
I went into the cabin, with the keys of mine in my hand, and what money I had;
I thought I had hardly ever seen a man of more savage, or fierce appearance.
My innocent fellow servants were all in the cabin.
When I sat down, he asked if J. Wigham was my husband.

I told him no; but a fellow-labourer in the gospel of Christ,
and that to preach it was the errand we had been upon in America;
that we with the rest of the women, were of the people called Quakers,
and that our peaceable principles were known in France.
He made a reply, which I did not well understand,
for he did not speak so good English as those who came yesterday,
neither was his conduct or disposition at all like theirs; however,
he did not ask for our keys, or do more than just lift the lid of J. Wigham`'s chest;
though he routed to the very bottom of several others, and took a very curious spy glass,
and some other valuable articles from two of the passengers.

Just about this time the captain returned, said they were satisfied with his papers,
and had given him liberty to proceed, which was very grateful information to us,
but seemed much to disappoint the menacing usurper, who had repeatedly said,
that by their laws all the English should be made prisoners;
but he went off pretty quietly with his booty, to the great relief of our minds.
To be in some measure tried after this manner, has not been altogether unexpected to me;
my mind being invariably impressed with such a prospect before I left New York;
and my greatest solicitude under these emotions was,
that we might not be taken to the West Indies; which continued prayer of my heart,
I yet hope will be mercifully granted; and though one woe is past,
and another should be permitted to come quickly, yet I have a humble trust,
that the Lord in his own time will deliver us out of them all.

Third-day morning.
On waking early,
my mind became seriously impressed with considerations on various subjects;
under which I was led deeply to mourn over the fallen state of man,
few appearing desirous to seek after, or accept the terms of redemption,
though so freely offered by the Saviour of men.

Fourth-day.
On waking I remembered it was our week-day meeting; and desires were raised,
that our little band might retire together,
to wait on the Lord for renewal of strength--which proposition
was acceptable to those acquainted with silent waiting;
but a little before the time for our meeting came,
so great an alarm was again given to our ship`'s company,
there was no retirement for us in the cabin;
so that my sister in tribulation came into my little room,
and I believe we laboured after quietude,
endeavouring to put our trusts again in the only sure Helper.
A ship had been observed for some time at a distance, which appeared to follow us,
and by her motion to be a ship of war; but a thick fog arose,
and hid her from us two hours, when she was seen going to the southward;
which tidings were thankfully received.
This afternoon the top-gallant sail was carried away by the wind,
which has been a-head four days.

Fifth-day.
The wind still a-head.
Last night and today the sea has run very high.
This afternoon while Charity Cook was paying me a visit,
the sea broke in so suddenly upon us, it seemed like the bursting of a water spout.
When we had got things put to rights, we had a second attack as heavy as the first,
which seemed to try our steward`'s patience;
but I had rather have two such swells every day, than see one French privateer.

Seventh-day.
Yesterday and to day nearly calm; the little wind we have continues a-head.
This disappointment in our progress, I think,
has had a tendency somewhat to quiet our too often noisy shipmates;
but having been favoured not to have any additional trials from without,
my mind is mercifully sustained with resignation and quietude;
for which I desire to be thankful: also for being recruited in my bodily health;
the rest of my companions are also partakers thereof.

12th of eleventh month.
The ninth day since the wind has been a-head.
Though to continue thus is not desirable,
my mind is favoured with resignation to the All-wise disposer of events.
My fellow sufferers and myself, retired religiously into the cabin this morning;
but our desire of quietude was much interrupted by the unbecoming conduct of a young man.
We were told before we sailed, that their company would not be agreeable to us,
and more light and vain men than some of them are,
I think could scarcely have been met with;
that I never felt more strongly the force of that sentiment:
"`Silence is wisdom where speaking is folly;`"
wherein my brother in bonds cordially unites.
We speak a little of our present and former situation on the great waters;
and mournful indeed is the case, where the sons of men so strikingly manifest,
that they are lovers of pleasure, more than of God; though it is to Him we owe our life,
breath and being.

Fourth-day.
On second-day the wind began to turn in our favour,
and has continued gradually increasing.
We are now within soundings; and from the top-mast, some parts of Ireland have been seen;
which has much elated some of our company.

Sixth-day.
From about eleven last night, we have had again a head wind,
several of the company talk of trying to get ashore at Milford-haven,
of which the captain thinks there may be a probability tomorrow,
if the wind continues in the present state; and if all the male passengers go,
except our brother, I believe they will have our free consent.
The day being calm,
and the sun shining very pleasantly-- the face of the water so serene,
that scarcely a bubble was visible--the mountains of Ireland and Wales in view,
and several ships at a distance,
our female band were longer on deck than at any other time.

Seventh-day.
How great a change since yesterday.
A strong wind and high swelling sea began last evening, and have continued all day.
Our captain hoisted his colours about ten o`'clock this morning for a pilot;
but none has yet ventured to come to us.
They suppose we are about thirty five miles from Liverpool.

19th of eleventh month, 1797, first-day.
A very trying night indeed! all hands were on deck;
there was so strong a gale that the ship was kept almost constantly
on the tack to prevent her from going out to sea or running ashore.
I felt much sympathy with the mariners, believing they were toiling hard,
under much dismay--which proved to be the case;
the captain said this morning he had wished us not to
know the difficulty and danger we had been in:
but I believe I was as sensible of it as if he had told me at the time;
yet my hope and confidence in the preserving hand of Power were unshaken.

About day-break the wind abated; and a pilot soon came on board,
but brought tidings that greatly disturbed some of the passengers,
and one of them in a particular manner;
informing us we were likely to perform quarantine.
This report did not in the least move me;
but a thankful sense of Providential care so filled my heart,
that I could have proclaimed aloud the following tribute;
"`Rejoice oh you Heavens! and break forth into singing, all you that can praise the Lord,
on the banks of deliverance.`"

At ten o`'clock we cast anchor about three miles from the town;
and at twelve the health officer came on board,
and said it was only vessels coming from Philadelphia, that they had orders to detain;
but the wind or tide not serving, we did not go on shore till third-day;
when we were all favoured to land safe.
May gratitude and dedication to serve the Lord faithfully,
ever be the clothing of my spirit.

I was three years, three weeks, and three days on the continent,
and travelled about eleven thousand miles; and was so far favoured with bodily health,
as not to miss one meeting appointed, or intended to be appointed; for which,
and every other mark of unmerited favour, from the bountiful hand of Israel`'s God,
may my soul bow before Him, who lives forever and ever.
Amen.
