== Chapter III.

[.chapter-synopsis]
* Several visits after her marriage
* Travels with Rebecca Wright
* And at different times with several other Friends
* Visits Worcestershire
* Ireland
* Dunkirk, etc.

My bodily health, for two or three years after our marriage, was not very strong,
and my exercises were many; yet I went several short journeys,
besides attending our monthly and quarterly meetings,
and several times the yearly meeting in London;
going on horseback with my husband and divers other Friends,
which was the general mode of travelling at that time.

I attended the yearly meeting for the principality of Wales several times,
once in company with my dear and valued friend Frances Dodshon;
and on our return we visited the meetings and families of Friends in Shropshire.
My dear and much esteemed companion, though in a very low, depressed state of mind,
was often clothed in her gospel mission, as with the King`'s royal apparel.

Some time after,
I felt again the pointings of duty to attend another yearly meeting in Wales,
to go from thence to Bristol,
and to take meetings as they lay in the way to the yearly meeting in London,
and others on my return home.

For this service I had a certificate from our monthly meeting,
and was accompanied by my dear friend Elizabeth Jolly;
but not having gone such a journey before, without a yokefellow in gospel labour,
it felt very weighty.
My mind was often under secret discouragement, and in a particular manner,
when my kind companion was likely to return home from London, and leave me alone,
having several counties to visit.

This time of holding our annual solemnity in 1784, was a very memorable one,
not only in being favoured with the company of many ambassadors from America,
fraught with gospel mission,
but in having the women`'s yearly meeting fully authorised and established.
When the yearly meeting closed, I felt exceedingly dismayed;
which my dear uncle John Routh perceiving, inquired the cause of my being so affected.
I told him I was likely to be left without a companion,
and scarcely knew how to sustain the prospect.

He encouraged me, with all the tenderness of a beloved father in the Truth, not doubting,
but I should be helped along beyond my expectation:
and the way soon opened for my joining my dear friend, Rebecca Wright,
one of the before-mentioned Friends from America.

Friends in general appeared well satisfied with our being united as companions;
and after visiting the meetings in the city,
we set forward through the counties I had in view, till we came to Manchester,
where finding my dear husband and relations well,
was cause of renewed thankfulness to the Author of all good,
who had thus helped and provided for me beyond all expectation.
It was needful for Rebecca to make some stay here, and my dear aunt, Sarah Taylor,
accompanied her to several places, and meetings,
which was very acceptable and encouraging to her.

My husband and friends being willing for me to join her again,
we bent our course northward, taking our quarterly meeting in the way,
where we had the acceptable company of Nicholas Wain.
We proceeded through the northern counties into Scotland,
more than twenty miles north of Aberdeen, visiting not only the meetings,
but the families of Friends.
It was in the depth of winter, which proved a very cold one, attended with more snow,
than aged people in those parts could remember; but Friends were very kind,
in caring for us.
We had much trial and jeopardy in crossing some of the large rivers,
on our return to Edinburgh; where we also visited the families,
and had deep exercise in the labour.
In coming thence to Kelso, forty miles, a very bleak open road,
scarcely a track was to be found for the horses, the snow was so deep;
yet that Almighty power, who calleth forth his servants and handmaids,
thus to work in his vineyard,
was graciously pleased to lead us safely through our perilous journey,
in time to attend the quarterly meeting for Yorkshire, held at Leeds;
whence I returned home, and Sarah Birkbeck accompanied my dear companion for sometime;
as did also my dear friend Elizabeth Jolly.

After this, I joined Rebecca Wright again,
and accompanied her through the western counties, nearly to the Land`'s end in Cornwall.

My dear companion Rebecca Wright was a greatly tried traveller,
and was often in the deeps, of which, according to my measure, I took part with her:
and sometimes hearing her mention,
how differently she got along in her own country in her gospel travels,
was fearful I was not such a companion to her as she had there,
which often caused me to weep in the night season,
and think it might be best for me to return home:
but this she could scarcely bear to hear mentioned;
and being closely united to her in the bonds of the gospel, I staid with her,
till I saw her on ship-board, with several others of her fellow-labourers,
returning to their native land.
I then staid at home a considerable time,
and was thankful I had peaceful liberty to do so.

About the year 1787, I had for some time had an opening prospect of religious duty,
not only to visit the meetings, but also the families of Friends in Worcestershire,
my native county; and with this impression was led to look towards Martha Howarth,
a member of our quarterly meeting, as a companion.

When the time came for moving,
being furnished with certificates from our respective monthly meetings,
we set forward by way of Cheshire, and Coalbrookdale;
and entered the county of Worcester, at Dudley,
where the ancient and honourable family of the Paytons used to live;
but they were then all removed by death or otherwise.
Thence we went to Stourbridge, where I first drew breath.
In the city of Worcester, as in other places, in visiting the families of Friends,
we were favoured with the company of one in the station of an elder,
who could bear testimony to what we had to minister;
which has always been my choice in such service.
This Friend being baptised with the one baptism,
could feelingly partake with us in the cup of suffering,
and rejoice with us when Truth was raised into dominion;
that our spirits were tenderly united, and also to the seed of God in that place.
Our labours there closed with a public meeting on a first-day evening, which was a large,
open, and satisfactory opportunity.
We then took the other side of the county, and were favoured in like manner,
with the company of helpers in the work, which closed at the monthly meeting at Alcester.

I felt pressed in spirit to return to Tredington, about six miles distant,
to our friends John and Sarah Lambley`'s, though the evening was very stormy,
the snow falling very thick.
We got there safely, and were taking some refreshment, when a young man,
son of Thomas Norton, came into the house, and seemed much affected.
His father had been threatened with imprisonment for non-payment of tithes;
and he said two constables were at their house,
and talked of taking him part of the way to Worcester that night.
I then believed that this was the cause of my being impressed to return there:
so we sent the young man back to request the constables to stop a while,
as some Friends wished to see his father.

The distance was about a mile, and the snow falling so thick,
it was not safe to go any other way but on foot, which we willingly did,
accompanied by John Lambley and his valuable wife.
We found Thomas Norton in a quiet, resigned state.
The men very civilly offered to leave the room, and withdrew into the kitchen.

Our visit was very grateful to him,
and seemed to strengthen his mind in resignation to the permitted trial.
His children also seemed more settled;
and the constables were willing to stay in the village till morning.
On our return through Worcester, we went to see him in his prison-house,
found him very composed, and reading [.book-title]#Sewel`'s History;#^
footnote:[[.book-title]#The History of the Rise, Increase, and Progress of that Christian People Called Quakers,# by William Sewel]
the jailer and his wife were very kind to him.
Some skilful Friends in the city, on looking over the indictment believed it faulty,
and took a counsellor`'s opinion, who advised them to bring it to an assize trial;
which they did, and the judge quashed the indictment,
and set the prisoner at liberty in open court.

Soon after our return from this visit, a weighty exercise came over me,
the time appearing to draw near for my paying a religious visit to Friends in Ireland.
The prospect had been opening for several years, and on its nearer approach,
believing from some hints dropped by Martha Howarth,
that she had something of the same kind in view, I opened my mind to her,
and pointed out the season when it might be right to move,
if Friends united with us therein.
So being furnished with certificates from our monthly meetings,
endorsed by the quarterly meeting, held at Lancaster in the ninth month, 1789,
a Friend was appointed by that meeting to accompany us to Whitehaven,
where we intended to take shipping.
We were detained twelve days by contrary winds;
during which time we visited divers families;
and being at the house of our endeared friend Jane Pearson,
a living minister of the gospel, the detention was made more easy.

We crossed the sea in a small vessel, were two nights out, greatly tossed, and very sick.
We had two religious young women with us,
who had been assistants at Friends`' school at York,
and were then going to be in the like station, with dear Sarah Grubb,
at the boarding school at Clonmel.
We were favoured to land safe at Dublin, and were cordially received by our kind friends,
Joseph Williams and his family.

Next day, the first of the week,
my companion was opened in testimony in the morning meeting;
but I felt closely shut up from anything of that kind,
with a secret intimation very clear to my understanding:
"`Thou shalt not go forth in haste or by flight, so the Lord shall go before thee,
and the God of Israel be thy reward.`"
The revival of this divine promise gratefully humbled my spirit.

The half-year`'s meeting drawing near,
Joseph Williams accompanied us to the meeting at Baltibois,
once the dwelling-place of that great and excellent minister Mary Peisley,
which lying rather at an outside, it was thought best to take it then.
It was a small meeting, but owned by the blessed Master;
and was the closing meeting to our dear friend Samuel Smith, from Philadelphia,
who after attending the half-year`'s meeting, returned to England.
But my dear companion and myself had to travel diligently for the space of six months,
in which time, according to our measure,
we largely partook of the tribulations of the gospel:
and were also partakers of some of the consolations in Christ Jesus our Lord,
being nearly united to the Seed in that land.
Our justly valued friend Richard Shackleton, at different times and places,
accompanied us many weeks, much to our comfort and satisfaction.

We had likewise in the course of our travels,
the company of several very hopeful young men,
who appeared to be coming forward in the paths of righteousness,
and with many others had not only made a good beginning,
but they ran well for a considerable time;
yet alas! alas! how has the gold become dim! and the most fine
gold changed! the precious sons of Zion comparable thereto,
through the devices of Satan,
become like earthen pitchers! and those things which they not only once knew,
but held sacred, have, like the stones of the sanctuary, been poured forth,
as at the top of every street!
May the merciful Lord, be graciously pleased to turn back the captivity of all such,
even as the streams of the south; then shall Jacob rejoice, and Israel be made glad.

When leaving Ireland,
we had the company of many Friends who were
coming to attend our yearly meeting in London.
We took shipping for Parkgate, but the wind being against us, we had to go to Holyhead,
where we had much difficulty in landing; the sea was so boisterous.
Our beloved friends Robert Grubb and his wife, etc., came with us to Liverpool;
from whence my companion and self got safe to our respective homes.

Sometime after returning home from this visit in Ireland,
I found an engagement to visit Friends in some of the southern, eastern,
and western counties; but not wholly through any of them.
I was accompanied, in this journey, by my endeared friend Christiana Hustler,
who being taken ill in London, my dear friend Sarah Row of that city,
went with me to the eastern quarterly meetings,
in which we had the very acceptable company of George Gibson and his wife,
and David Priestman and his wife, who all, except David, have been sometime past,
gathered to the mansions prepared for them in the heavenly Father`'s house.
The near unity and fellowship in which we travelled together, is grateful in remembrance.

On our return to London, finding my dear companion restored,
we crossed the channel to visit Friends at Dunkirk; about seven families,
who had lately removed from the island of Nantucket, in North America.
We visited their families and sat several of their meetings:
our valued friend William Bleckly being with us on the like gospel errand.
We were obliged to have passports at Calais,
which gave liberty for us to travel to any part of France, during the space of one year.
After stopping about eight days in the city, we were easy to leave,
and wished to go thence by water to Dover; but whilst one of the Friends was gone,
to the wharf, to see if there was a suitable vessel, it suddenly presented to my mind,
we should not get away that day, which I told my companion, and other Friends present;
and had but just done so, when the Friend returned, saying the city was all in an uproar,
the drawbridges taken up, no passage by land or water,
and that cannon were going to be placed at the avenues of the streets.
This was occasioned by the arrival of an account,
that the poor King had attempted to make his escape.
It felt an awful time.
Next morning, with a fresh endorsement on our passports,
we were permitted to go to Calais by land, and crossed the water, the same evening,
to Dover, which felt cause of mutual thankfulness.
We were again kindly received at our friend Richard Baker`'s.

My companion and self then proceeded to London, and westward as far as Bristol.
In our return we came through Worcester and Stourbridge, my native place,
staid a few days with my dear brother William Winter,
who some months after departed this life.
He had been an approved elder in the church many years, though not an aged man.
He had feared the Lord from his youth.
He left a precious widow and three children.
My dear companion and I proceeded pretty directly home,
and found our near connections favoured with health, which,
with other manifold marks of divine regard,
was cause of reverent thankfulness to our Almighty Helper.
