== Chapter VII.

[.chapter-synopsis]
Her travels in America, in 1796, to the 26th of sixth month.

3rd of first month, 1796, first-day.--We attended a meeting at Club Foot creek,
largely attended by those not of our Society, among whom were many black people;
and the compassion of the Everlasting Father, who is no respecter of persons,
was greatly manifested towards the different classes.
In the afternoon, we attended a small meeting of ministers and elders; and on third-day,
were at Lower Trent, where we met my valued friend John Wigham.
I believe we were mutually glad to see each other again, and were nearly united,
as we had often been, in the bonds of the gospel,
wherein we were engaged among the people;
and the meeting closed in supplication to our Heavenly Father,
that His preserving power might continue near to those who put their trust in Him,
whether in going forth or staying at home.

We proceeded to Bear creek, sat meeting there on fifth-day, which though small in number,
was much interrupted with the noise and playing of children:
a caution was given in the early part, but it had little or no effect,
that I was ready to give wholly up the apprehension of
its becoming a religious opportunity;
yet after a time of painful exercise,
through the watchful dedication of a younger brother,
in opening the door with a few expressions,
my spirit became somewhat at liberty to speak of things as I felt them,
and to deal plainly with the careless professors of religion,
who might have liked smooth things; but I had them not in commission.
Next day we attended the monthly meeting at Contentney,
where was a large gathering of Friends; yet it felt a low time, in secret travail,
and was held in silence as to ministry.
I had some remarks to make to women Friends in their meeting,
who seemed honestly concerned to do their best; and they received the,
little help then afforded with gladness.

10th of first month, first-day.--At the meeting at Contentney, which was very large,
divers not of our Society were present; and soon after retiring in spirit,
to the measure of the Divine gift in my own mind,
a clear opening of the states of the people was given,
when on a sudden all was taken away,
and I was favoured with much quietude and resignation.
After sitting some time under it,
I felt liberty simply to express how it had been with me;
that if it should then be the case, it would not be the first time,
wherein I had known the scripture declaration fulfilled,
that the spirits of the prophets were subject to the prophets,
and that a small key unlocked a cabinet of rich treasures, when a larger could not do it.
Soon after sitting down, a tender spirited Friend, who was then a stranger to me,
dropped a few expressions in a lively manner,
when my way was again opened to discharge my duty, and I humbly trust,
through the renewings of divine help, to divide the word.

We attended the meetings in that neighbourhood, Holly Spring, Turner's Swamp,
and Nahanty, in all which I had to labour in the gospel, and returned to Contentney,
to the quarterly meeting.
That for ministers and elders beginning on seventh-day,
where we again met our beloved friend John Wigham.

17th of first month, first-day, in a very large gathering of people,
the public labour fell to the lot of the brethren;
and I was thankful to feel peace in silence.
Towards the close, I felt it right to request the meeting,
previous to entering on the discipline of the church next morning,
might be select for our own members, which I believe was much the case;
and I had to labour in a close searching line among the different ranks of the family,
wherein I felt near sympathy with a lowly tried remnant,
particularly in the women's meeting,
who appeared humblingly sensible of the situation of things among them.
After this meeting I was at liberty in mind to depart,
but it being a flat part of the country, and much rain falling for several days,
the waters prevented our journeying,
except to a meeting or two again in the neighbourhood.
My valued fellow labourer, John Wigham., was detained there with us.

24th of first month, first-day.
We each had some further labour in the gospel,
then took a solemn and tender leave of Friends, and again parted for the work's sake,
he going southward, and we northward.
Some bridges being washed away,
it was with difficulty we got to a settlement of Friends on third-day night,
after ten o'clock, at Jack Swamp.
We attended their week-day meeting, and though a time of heavy rain, many assembled.
The outward trials were made easy through the gracious ownings of the Heavenly Shepherd,
who influenced with the language of encouragement to the exercised travellers.
The next meeting was called Richsquare, but too few of its member appeared to be so,
in faith and good works; rather in love with the world, and other undue liberties.
Hence it was a time of close labour; yet there seemed a few mourners in Zion,
who were encouraged to keep to their exercises,
that in the appointed season of the Holy Shepherd,
His gracious promises might appertain to them;
who through the mouth of His prophet declared.
He would give "`Beauty for ashes, the oil of joy for mourning,
and the garment of praise for the spirit of.heaviness.`"

31st of first month, first-day.
We attended meeting at Finey Woods, in the morning, and Beach Spring, in the afternoon;
the two following days we were at Wells's, Western Branch, Little river,
and Simon's creek.
On fifth and sixth-days, at Newbegun creek, and the Narrows;
in all which I had deep exercise and secret travail of soul,
that I might experience the blessing of preservation, in true discernment,
and discharge of the trust committed to me.

And my great and gracious helper condescended to accept the dedication,
and favoured with a renewal of strength, to go through the almost unremitting labour,
with a good degree of relieving peace, in sympathy with the oppressed seed;
and in earnest expostulations with the backsliders,
who were warned to flee from the wrath to come;
and heads of families were entreated to look
more closely to the well ordering of the flock;
to keep them out of hurtful company, and the many evils which sorrowfully abound,
even in a wilderness country.

Many black people attended these meetings, to whom the gospel was preached;
and the testimony of Truth went forth in a close manner against their oppressors,
who are grievously bending their wicked designs against those who never belonged to them,
in taking up, imprisoning, and selling men, women, and children,
whom Friends have set free, and settled on their own plantations, to work for themselves.
The hearing of which, with many aggravating circumstances,
hath brought nature and spirit into deep mourning.
Great pains and care have been, and still remain to be taken by Friends,
on account of this afflicted people,
in pleading with the rulers of the state of North Carolina,
to protect those who are set free; but such is their hardness of heart,
the pleaders have yet pleaded in vain;
neither are the people willing to bow to the chastising rod of Omnipotence,
which hath been gently, yet increasingly shaken in this part of the vineyard,
various ways.

On seventh-day we attended the monthly meeting at Piney Woods,
wherein I had a little to open the right qualification
for usefulness in the discipline of the church,
and how preservation would be witnessed by those exercised therein,
to keep their places and help to bring others forward.
I had also some close remarks to make among women Friends,
apprehending the true state of meetings was too easily passed over,
in superficial answers to the queries; which sentiment the honestly disposed united with.

7th of second month, first-day.
We staid meeting again at Piney Woods, and I was favoured to feel, I trust,
in the silence of all flesh, a peaceful release from the bonds of the gospel,
wherein I had laboured in that part of the vineyard;
and under a renewed feeling of the gracious condescension of
our Heavenly Father towards the children of men,
my soul was humbly bowed; and in fellowship with those whose fellowship is with Him,
was led to supplicate his holy name,
for the continued blessing of preservation to them that put their trust in Him;
that those who were afar off might be brought near, to unite in the acknowledgement,
that the kingdom, power, and glory, belong unto Him for ever.
Afterwards my mind was covered with such solemn silence,
as felt very instructive and precious,
and I hope it was in degree witnessed by many in the meeting.
In the evening, we had a religious opportunity in the family where we lodged.
Several black people were present, who appeared very serious and tender in spirit;
and I had to leave with Friends as my last testimony,
that there was no way so likely to bring about a thorough reformation,
as a frequent attention to religious retirement in their families,
wherein useful instruction might be handed both to children and servants,
which would scarcely be attained any other way, tending to preserve from evil,
and encourage and strengthen them in that which is good.

In the morning, we set out early towards Somerton, in Virginia; and on third-day,
attended a large meeting there, though few of our own Society,
among whom the life of religion felt low;
but in the discharge of duty towards them and others, I felt a peaceful release.
In the same week attended the meeting at Bennet's creek.
Western Branch, etc., in all which much exercise was assigned me,
one was particularly trying; desolation appearing so much the state of it,
that in returning, the secret impression was like visiting the sepulchres of the dead;
without a sensible feeling, that the quickening power of Truth had any reach.

On seventh-day, after a religious opportunity in the family where we lodged,
which appeared to be a contriting one to some of the young people,
we attended the quarterly meeting for ministers and elders, at Black Water,
which felt to me a low time in silent wading.

14th of second month, first-day.
A public meeting was held, composed of a large mixed gathering; but many,
both professors with us and others, appeared so inattentive to what they were come about,
that painful indeed was the labour.
On second-day, previous to entering on the discipline,
I was led in a close searching line among Friends,
which tended greatly to the relief of my own mind.
That evening, we went a few miles on our way to a meeting, called Stantons,
which was appointed next day at ten; attended another in the afternoon at Seaconch,
and in the course of the week Burleigh, Gravelly Run, and Curies.

21st of second month, first-day.
At Wainoak, which was a large gathering, many not of our Society attended,
and through the renewings of holy help, the doctrines of the gospel were opened,
and the Lord's power magnified, who is worthy for ever.
On second-day we went to Skimino, had an appointed meeting there on third-day,
in a poor miserable house, that needed no other light,
than what came from the vacancies in the wood, that we were almost pierced with the cold;
but finding a few worth visiting, we were somewhat comforted together;
that I could feelingly bear testimony, I did not serve a hard master,
but a rich rewarder of those that put their trust in Him.
After meeting we rode thirty-five miles.
On fourth-day at Black creek, a small meeting.

On sixth-day, we had two at Richmond, the first with Friends,
through the ownings of the great Shepherd, was a contriting time to some;
who were tenderly counselled to keep under his direction.
The other was in the Mason's-Hall, with the town's people, who conducted becomingly;
and a humble trust was raised that the cause did not suffer.
Thence we proceeded to Cedar creek,
and attended the monthly meeting there on seventh-day,
the business whereof seemed more agreeably and satisfactorily conducted,
than that of any which we had been at.

28th of second month, first-day.
The select quarterly meeting at Cedar creek began at nine,
which felt more lively than some others we had attended,
and my mind was strengthened in the discharge of duty.
At eleven, the public meeting for worship came on, which was a large gathering.
A Friend from North Carolina, in the course of a religious visit, being there,
had a short but living testimony to bear.
On his closing, the word of life arose in my heart,
and opened gospel truths to the different states of the people; and near the close,
the testimony went forth like a two-edged sword,
against the iniquitous traffic of buying, selling,
and evilly entreating the sons and daughters of men.

Through the arising of His power, who binds Leviathan, the crooked serpent,
the spirits of such were chained, so as to make no opposition;
though I was afterwards informed,
that divers were present who made it their particular
business to buy and sell the black people.
I humbly trust many minds were made thankful to the blessed Author of all good,
who is worthy of praise.

On second-day, the quarterly meeting was held,
wherein tender counsel was opened to Friends.
On third-day, we were at meeting at Genito, and returned to Cedar creek in the evening,
feeling a draught in my mind to be at their meeting on fourth-day.
There being a school for Friends' children and others,
the first we had seen in the southern states, they were particularly desired to attend;
and though a wet morning, and all lived distant from the house, they were fully gathered,
with most of the members about the tenth hour;
and through the gracious extendings of our Heavenly Father's love,
I believe it was a tendering and instructive season, to the children and others.

We then took leave, and went sixteen miles on our way to Carolina,
where a meeting was appointed next day, in which through divine favour,
spiritual strength was renewed to preach the gospel--setting forth the nature of,
and qualification for such services--what the purity and
spirituality of the Spirit of Truth would lead into,
and preserve out of; and the true ministry as taught by Christ,
was set over a false hireling one.
Many not of our Society were present, who appeared attentive; and if any good was done,
"`Thanks be to God for his unspeakable gift,`"
mercifully dispensed to the children of men.

We next morning proceeded on our way to Stafford,
and had considerable difficulty in getting through the waters,
which were much out of usual bounds, by reason of heavy rain.

One instance of preservation when we appeared in imminent danger,
I think worthy of notice: when about the middle of a very wide and deep water,
which covered a foot-bridge, one of our horses and the wheels of the wagon got upon it,
and put the other in such a position, as hardly to be able to keep his feet;
both he and the carriage appearing nearly thrown over.

Our guides were at some distance; but at this critical juncture,
when it seemed alike unsafe to stand still or to move,
I was favoured with presence of mind to call them back, to hold up the top of the wagon,
while we gently moved on to a level place; which we accomplished without any damage.
Thus have we experienced merciful deliverance, through the great Care-taker,
when much danger hath seemed to await us!
We then requested our guides to ride abreast before us, at a suitable distance,
that they might discover any bank or hollow, and avoid it;
which we had often found very useful.
I mention this for the help of other travellers in similar situations.

6th of third month, first-day.--We attended meeting at Stafford, a large mixed gathering,
and the labour was exercising, yet I hoped might be to some profit.
We lodged that night at a tavern on the way to Alexandria;
in getting to which we had much difficulty, from the depth of mire and clay.
Next day we called to see a family who had once been members of our Society,
who still seemed to retain much love for Friends;
and being detained by a heavy snow storm,
I felt religiously engaged to have the people of the village, both black and white,
invited to come together; which was readily made way for,
and the meeting held at our lodgings.
Though divers appeared scarcely to have heard tell of the Holy Ghost,
or the inward appearance of the Spirit of Truth; yet through an exercising labour,
a hope revived that some little knowledge was communicated to the learned and unlearned.

Towards the close, I had to plead the cause of the oppressed,
"`to proclaim the acceptable year of the Lord,
and the day of vengeance of our God,`" in his own appointed season,
on those who should continue the evil traffic; using our fellow-creatures,
only differing from us in the colour of the skin, as the brute creation.

When the meeting ended, a well looking man took leave of me, expressing a desire,
that the Divine blessing might attend the work.
When he was gone, I was told he kept many slaves and was far from being a kind master:
so that there seemed some ground to apprehend,
the power of conviction at that time touched his mind.
We reached Alexandria next day, sat their meeting on fifth-day,
and had to labour in the gospel in a close awakening manner,
much to the relief of my own mind, which had felt secretly weary and heavy laden.
Some not of our Society being present, had informed others,
so that when about to depart next day, a Friend asked me if I had been informed,
that one of their chief magistrates had sent a request I might be stopped longer in town:
I told him I had heard nothing of it, and having often thought,
when unclothed of strength,
it would be no marvel if bonds and afflictions
awaited me from the hands of unreasonable men,
rather expected it might be something of that sort,
and felt quieted in resignation if it should be the case.
He then produced a letter he had received from the above mentioned magistrate,
expressive of a desire on the part of himself and others,
that my departure might be somewhat deferred, in order to admit of another meeting.

I wished the Friend to inform the writer,
that having felt a peaceful liberty of mind from further religious labour in that town,
I was then about to leave it;
that I had found my way much shut up in the southern states, from having public meetings,
being painfully impressed with a feeling,
that there was but little room availingly to preach the gospel,
which breathes peace on earth, and good will to men,
while so much oppression and cruelty is exercised towards our fellow-creatures,
entirely repugnant to the nature and spirit of Christianity;
and until that evil was done away, I did not believe it would spread much amongst them.
The Friend said he would endeavour to communicate the message, agreeably to my desire.

13th of third month, first-day.--We attended a meeting at Indian Spring,
in which much painful exercise was my portion,
the state thereof appearing like that described by the prophet; the head sick,
the heart faint, and scarcely any soundness to be found.
On second-day we journeyed on to Elk Ridge, where a meeting was appointed on third-day,
which was a large mixed gathering,
and mercifully owned with a renewal of strength to labour in the gospel;
though the testimony of Truth, as at many other seasons,
went forth like a sharp threshing instrument,
against those that oppressed their fellow-creatures.

From thence we went to Baltimore, in Maryland, where we rested one day;
and the next attended their week-day meeting,
which was a very large gathering of Friends,
and many others not of our religious Society, who I evidently felt,
were desirous to hear the gospel preached;
but I was favoured with a peaceful acquittance, in keeping silence before the Lord.

Next morning, we set forward to a meeting called Littlefalls;
but there appeared a great falling away,
from the purity and spirituality of the principle we profess, which caused heavy labour,
to awaken carnal professors.

20th of third month, first-day.--We attended a small meeting;
divers not of our Society came in, and counsel was opened,
also encouragement to the few belonging to us, in a consistent walking.
We went some miles on our way that evening,
where we had fresh opportunity painfully to observe,
how little attention is paid by many Friends scattered in the country,
to take their families steadily to religious meetings;
for we found nine females where we lodged, none of whom had attended that day,
though divers of the younger were then out, on an excursion of what is called pleasure.
Mournful indeed is the neglect of many parents
in the discharge of care towards their children;
and great are the undue liberties taken by many of the young people,
which hath been cause of much close and exercising labour, in public and private.

We crossed the Susquehanna next day, and called to see a family of Friends from England,
who had been greatly tried with indisposition incident to that part of the country:
we felt much sympathy with them,
and our visit appeared comforting and reviving to their minds.

On fourth-day we were at White Clay creek,
where it was satisfactory to feel there was a wrestling seed,
with whom my spirit united in travail, though too many were in a lukewarm state.
On fifth, we were at Wilmington, a time of close labour.
On sixth, at the monthly meeting at Providence, which was largely attended by Friends;
and through the renewings of Divine help, it was an instructive season.

That evening we got safe to Philadelphia, where we again met my beloved fellow-labourers,
Deborah Darby and Rebecca Young, with other near and dear Friends;
and under a grateful humbling sense of the manifold trials and difficulties,
we had been preserved in and brought through,
by the sustaining help of our Heavenly Father,
the silent tribute of acknowledgement was raised in my soul: "`Thine is the kingdom,
the power, and the glory, both now and for ever.`"

On seventh-day morning, began the Spring meeting for ministers and elders,
which was largely attended; and after the previous business was gone through,
our friend Samuel Emlen and three others,
spread their concern to pay a religious visit to some parts of Europe.

It having been a short time since the former returned,
the consideration of his going again,
had impressed my mind with more than common exercise,
almost to doubting the propriety of it;
but in that opportunity I was favoured to feel the Spirit of Truth,
so bear witness with my spirit, that the holy Shepherd was again putting him forth,
that all within me was made to say.
Amen.

In the evening of that day I was seized with a heavy cold, attended with sickness,
and strong feverish symptoms; arising I believe from the heat of the house,
and the chill in going into the cold air.

27th of third month.--I sat the meeting at Pine street in the morning,
under so much bodily suffering, that I doubted the propriety of being there,
believing I might rather be a hurt to it than otherwise: knowing by experience,
that fellow-labourers are sometimes apt to look towards strangers,
and neglect the exercise of their own gifts.
As soon as I got to our lodgings, I found it needful to retire to bed,
where I continued till next evening, in a serene peaceful state of mind,
having all I stood in need of tenderly administered to the bodily frame;
and I was so far restored as to attend the last
sitting of the select meeting on third-day.
Certificates of concurrence were then produced for the before mentioned Friends,
also certificates for our beloved Deborah Darby and Rebecca Young,
expressive of Friends' near unity with their religious labours and deportment.

3rd of fourth month, first-day.--Attended the meeting at Chichester,
which was a large mixed gathering, wherein a renewal of strength was experienced,
to labour in the gospel.
In the evening we were at a meeting appointed for the inhabitants of Wilmington,
which was largely attended.
During the gathering of the people, greatly was my mind humbled,
and I was brought into a very low dependent state, with a secret but earnest cry,
that the Holy Head of the Church, who had compassion on the multitude,
might be graciously pleased to own us together by the breaking of bread,
whether in silent waiting, or in public labour; and feeling the gentle moving of life,
opening my way to express a word or two of my own feelings, I stood up,
and in this dedication,
the gradual arising of the water of life not only touched the soles of the feet,
and reached the ankles, but became like a river.
The doctrines of the gospel were largely opened,
and the right anointing for gospel ministry, whether in male or female, was pointed out;
also that life and salvation came by and through Christ,
as we his creatures yield ourselves to obey his will; with an earnest solicitude,
that all might be brought into that state.
I humbly trust it was a solemn season,
the tribute of acknowledgement ascending to the Lord on High, who is worthy for ever.

I was weary in body, but felt peaceful quietude of mind;
and next morning we set forward to visit the meetings
on the Eastern shore of Maryland and Delaware,
taking them as follows: Sassafras on third-day, a very small meeting of Friends;
divers others coming in, it proved a more satisfactory opportunity than I expected,
in which some counsel was opened, I trust, to the states of those present,
both in reproof, caution and encouragement.
On fourth-day we sat the week-day meeting at the head of Chester.
Many not of our Society attending, the house was filled;
and the doctrines of the gospel were renewedly opened.
We were at Cecil on fifth-day, and Chester on sixth-day morning;
in the evening we had a public one in the town of Chester;
in all which I was engaged to labour, in the ability received, for the discharge of duty,
wherein I felt peace.

10th of fourth month, first-day.
We sat a small meeting of Friends at Choptank bridge,
where the inhabitants of the village came in; and gospel truths were opened,
tending to awaken and stir up the mind, to seek after pure and undefiled religion;
to which many appeared much strangers.
On second-day, at Tuckahoe; in the silent part of the meeting,
an instructive sense of the necessity of all that is of the creature,
being reduced into entire submission, and dependence on the Creator,
impressed my feelings, with pointings of duty to open the subject to others;
and in the resignation of my own will, I humbly trust, I was enabled to speak,
as the Spirit gave utterance, to the reaching of the witness in some minds then present.

On fourth-day, we were at Bayside, where more not of our Society came,
than could get into the house;
to whom the compassionate regard of the Shepherd of Israel was manifested.
The family where we lodged received us kindly,
and the woman appeared like a steady Friend; yet I was secretly exercised,
the cause being hid, and I felt no liberty to make inquiry.
On going to meeting I told one of the Friends,
I had no wish to return to that house of bondage; yet believe it was right we did:
for on entering again under the roof,
it feelingly presented to my view that the man was a slaveholder;
and on asking a Friend who came with us, I found it was so;
and that his wife had been convinced of Friends' principles.

Before we left, I found my peace to consist in discharging my religious duty,
not only respecting keeping our fellow creatures in bonds, but on some other subjects;
and the remarks appeared to be well received.
One of the daughters in particular was much tendered; that when I took leave of her,
she laid her head on my shoulder, said nothing, but wept abundantly.
We thence proceeded to Third Haven, and Marshy creek.

At the latter we had a meeting, among a people called Nicolites,
who much resemble Friends in their outward deportment.
I endeavoured to discharge my duty, according to renewed ability,
and an apprehension took place,
that they would not be long a distinct society from Friends.

17th of fourth month, first-day.
We were at Cool Spring; on second-day at Three Runs; third-day at Mother-kill;
in all which exercising labour was assigned:
the latter in particular was a very large mixed gathering,
in which were many black people.
Strength was given to divide the word to the different states;
and I humbly trust it was a time thankfully to be remembered:
the praise thereof was given to the Holy Head of the Church, to whom alone it belonged.
We went to Warner Mifflin's to dine, with several other Friends,
and feeling an exercise that drew to silence, I found it right to give way to it;
and it became general with those present, among whom were several young people;
but very unexpected indeed were the remarks I had to make,
of the state of some we read of, who had made a covenant with death,
and were at an agreement with hell.
The secret conflict of my mind was great,
in having such a passage to mention in a small company,
among whom appeared little visible sign of deviation.
I was informed some weeks after, that a young woman then present,
the only child of a valuable minister, married the same week,
a man of deistical principles and ordinary character.

24th of fourth month, first-day.
We were at a large meeting of Friends at Concord, and a very exercising one to me;
though, had I been more honest to my feelings in the discharge of duty,
I might have felt a more peaceful reward.
Another meeting being appointed in the evening, at Middletown, seven miles distant,
and very rough road, we could not stay to dine; indeed I had no appetite to eat;
so we took a little matter in the wagon, and reached the meeting in due time;
which was also a very large gathering, and through the renewed extendings of Holy help,
was an open time of labour, tending greatly to the relief of my oppressed mind.
We went that night to Chester, where a meeting was appointed at ten next morning,
as was another in the afternoon at Darby, both which were seasons of heavy exercise;
but the healing balsam of peace being mercifully granted,
was an ample reward for the labour of the day.

Fourth month, 25th. Returned to Philadelphia,
where we were again favoured to meet my endeared friends Deborah Darby and Rebecca Young,
with many others nearly united in the one precious faith.
We attended the North monthly meeting on third-day; Pine street on fourth-day,
and on fifth-day, accompanied by our valued friend Samuel Smith and others,
attended one at Darby: where I was glad again to meet with Chalkley Albertson,
a valuable minister from North Carolina, then on a religious visit:
and thankful to the blessed Author of all good,
that I had given up to the secret impression of duty in going there.

We all returned to the city that evening,
and next day were at the monthly meeting for the middle district; on seventh-day,
at that for ministers and elders preceding the quarterly meeting.

1st of fifth month, first-day.
We attended three meetings for worship; and on second-day the quarterly meeting,
which seemed near closing the labours of my valued country women.

In the evening one appointed for the black people was largely attended,
but was a time of heavy labour.
Next morning we were at the week-day meeting at Pine street;
after dinner we took a near and solemn leave of our before mentioned Friends,
and crossed the river Delaware, to visit the meetings on a part of the Jersey shore,
in our way to the yearly meeting, at New York.

8th of fifth month, first-day.
A very large meeting at Salem,
was graciously owned with the extendings of our Heavenly Father's love,
tending to stir up the lukewarm and forgetful,
and to encourage the righteous to hold on their way; that,
being of the number of those who keep the Truth,
they might become fitted to enter the everlasting kingdom.
In the course of the week, we attended meetings at Alloway's Creek, Lower Greenwich,
Cape May, Great Egg-harbour, and Little Egg-harbour.

15th of fifth month, first day.
We were at Barnagat, a poor shattered meeting every way,
yet I felt sympathy for the little that remained alive.
That night we lodged at a tavern, and early next morning got to Squancum,
where sickness so generally prevailed,
that it was doubted whether any could get to the meeting;
but after due consideration I was most easy to appoint one, at two o'clock;
and many more came than we expected, both of our own Society and others;
their minds appearing more staid and humble than common,
perhaps by reason of the sickness.
It was a contriting opportunity, for which my heart was made thankful,
to the blessed Author of all good.
Thence to Squan, which was a laborious meeting;
many seemed to love other things more than they loved Truth,
and the pure seed was much oppressed;
under a sense of which near sympathy and encouragement went forth,
to a lowly tried remnant.

On third-day we travelled fifty miles to Rahway, part of it in very heavy rain;
but the toils of the day were much made up,
in finding there our endeared friend Rebecca Jones, and others we much loved,
who were also on their way to New York.
I had felt pressed in spirit to get there that evening,
though we had sat a meeting with Friends there before.
My religious prospect was now to have one with those not of our Society,
for the lower class of the people, black or white;
and when we got there we found their monthly meeting was next day,
and a meeting of the above description already appointed at the request of John Simpson,
a valuable minister, which felt very pleasant to me;
this language being raised in my heart:
"`If the end designed by the All-wise Director is answered, it is enough.`"

I had some cause to apprehend,
His providential hand pointed out the path to that monthly meeting.
A large number attended in the evening, but were long in collecting,
and quietude was much interrupted by the noise of young children,
that great was the exercise of my mind, lest we should meet and separate in confusion,
rather than religious order; when the before mentioned Friend arose,
and in a few emphatical expressions recommended silence, and ingathering of mind;
stating an apprehension that he should not have much to communicate.
This tended to turn my attention more closely to that
which had been secretly struggling in my mind;
but faith was so weakened, and doubtful disputations had so far taken place,
that I scarcely knew how to rise on my feet;
yet that Almighty power who can disperse the darkest cloud,
was graciously pleased to do so at that time, opening counsel,
and breaking such bread as he saw meet for the multitude;
raising grateful acknowledgements in the minds of the exercised.

22nd of fifth month, first-day.
The public meetings at New York were very large:
my valued fellow labourer John Wigham and myself, being strangers and foreigners,
the desire of the people seemed raised to hear us in public testimony:
but I trust He who commands the clouds, was pleased to order our way in silence,
and strengthen peacefully to acquiesce in His holy will.
The meetings for business began on second-day,
and continued by adjournments till seventh-day,
wherein Friends appeared to labour in the ability received, for the help one of another;
and counsel was administered, as Truth opened the way, by those strangers present.
The business of men Friends closing about the same time,
the shutters that parted the house were opened;
a quiet pause took place in both apartments,
and the meeting appeared to end under a profitable solemnity.

29th of fifth month, first-day.
Three public meetings were held;
the last was one appointed in the evening for young people of all descriptions,
and was graciously owned by the regard of the Heavenly Father,
towards those in the slippery path of youth.
On third-day we left the city, parting with some endeared Friends in near affection;
and proceeded to visit the northern part of the state.
On fourth-day morning we were at Purchase; and in the evening at North Castle,
both very exercising meetings.
Fifth-day at Shapaqua, sixth-day at Collerbark, a small meeting;
but some tender visited minds being present, it was a contriting opportunity.

5th of sixth month, first-day.
In the morning, at Amawalk,
the quietness becoming religious meetings was much interrupted; on which,
as at many other seasons, I had close remarks to drop;
and being faithful to the requirings of Truth, on that and other subjects which opened,
I felt a peaceful release.
In the evening a meeting appointed at Bedford,
was largely attended by those not in profession with us,
whose minds so generally appeared strangers to the principle of Truth,
it was heavy work to labour among them; yet some sustaining hope was afforded,
that a little ground was gained.

Next day, we were at Peach Pond, a painfully exercising time,
in which I had a sense given, and had to tell Friends my apprehension,
that their meeting was not kept up in a way likely to produce religious improvement,
or even to be what is esteemed reputable among men.
I was afterwards informed, this was the real state of the case; and that,
some months before, a Friend expressing his feelings somewhat after the same manner,
had been publicly opposed by one of these self confident members;
when a tender spirited man, not of our religious Society, arose, and declared,
the stranger had told them the truth, it was just their situation.
I felt a secret travail they might be brought to a profitable remembrance,
that out of the mouths of two witnesses, things were to be established.

On third-day, we were at the Valley, a trying meeting,
though I was dipped into near sympathy with some exercised travellers.
A circumstance occurred there, which I think worthy of notice.
A valuable Friend belonging thereto,
found his mind so impressed with a belief that we should be there on third-day,
that at the close of their meeting on first-day, he mentioned the same,
though he did not know we were in the neighbourhood.
This, however singular, proved favourable to us, as the request to appoint a meeting,
had not come to hand.
He afterwards accompanied us to several meetings, being a living minister,
to whom we felt nearly united.

The next day, at Oblong, the life of religion seemed at a very low ebb;
the outward quiet also was again painfully interrupted; but,
through the renewings of best help,
I was favoured to clear myself in a faithful discharge of duty,
so as to feel the reward of peace.

On fifth-day, we were at New Milford, a small meeting of Friends.
Others who came in appeared so light and airy,
that a close testimony was given me to bear;
and though hard work to thresh the mountains of empty profession,
among our own members or others, yet a humble trust was raised,
that through painful labour, Truth gained some ground over contrary spirits;
and the few mourners were somewhat comforted.

On sixth-day, we were at the Branch, a trying meeting,
attended with close secret baptism of spirit;
yet encouragement was handed to the exercised travailers.
That evening, we crossed a high rough mountain to Apoquage.

At meeting there next day, the number of Friends was small,
and things felt very low in general;
that my mind was dipped into near sympathy with the few that were alive in the Truth:
counsel was opened, for the encouragement of such,
and to awaken others out of their lapsed state.

12th of sixth month, first-day.
In the evening, at Westside, the people gathered in due season,
and settled down in rather an unusual quietude,
which felt very grateful to my often tribulated mind;
and I fully believed tended to draw down the divine blessing.
The language of the Prophet, was livingly opened in my remembrance:
"`The Lord is in his holy temple, let all the earth keep silence before Him.`"
And the Almighty Father, who enjoined the people formerly to wait on Him,
for the renewal of their strength; to draw near, and then to speak;
was graciously pleased to open counsel, in testimony to the sufficiency of His own power;
for the information, instruction, and encouragement of many present:
that I humbly trust it may be said, it was a good meeting.

We went afterwards to visit an elderly Friend, in a declining state,
who appeared in so prepared and resigned a frame of mind,
that it was pleasant to sit by him.
It was late when we got to our lodgings, having about eight miles to go;
that I felt very weary: but on lying down I thought I could say with a pious author:

[verse]
____
"`Now another day is gone,
I'll sing my Maker's praise, etc.`"
____

On fourth-day, we attended the monthly meeting at Nine Partners.
A large number of Friends belong to it,
some of whom appeared well concerned for the maintenance of right order.

The wide difference between the gospel dispensation and that of the law,
was early opened in my view; and through the renewings of best help,
I was enabled to point it out, for the encouragement of the faithful;
reminding the lukewarm professors, of the purity and spirituality of that principle,
which we hold forth in so distinguished a manner to the world.
I felt much nearness of spirit Awards some women Friends;
and when separated from the brethren, my spirit was bowed before the throne of Grace,
in supplication to the Holy Head,
that He might be near to strengthen in every good word and work.

Next morning,
we sat with a committee appointed to have the
care of a boarding school in that yearly meeting;
for which purpose Friends have purchased a large house.
Feeling interested in the undertaking, I offered to return,
after taking some meetings in the neighbourhood; and with them to review the premises,
and render any assistance in my power; which appeared to be gladly accepted.

That evening, we went to an appointed meeting at Stanford, to which few Friends belong;
but it was fully attended by the lower class of people, who, I had to apprehend,
made little profession of religion.
Through the compassionate regard of the heavenly and universal Father,
counsel was opened in a plain simple manner, so that the unlearned might understand;
and I trust the witness for Truth was reached in some minds.

On sixth-day, the monthly meeting at Creek was large,
wherein I felt the help of the spirits of fellow labourers,
who were encouraged to faithfulness; with some close labour to arouse carnal professors.

On seventh-day morning, we returned to Nine Partners,
spent about four hours with Friends in viewing the house before mentioned,
making such remarks as occurred, which were taken down for further consideration.
We left them in the evening, with unfeigned desires for the prosperity of the school,
apprehending that many in the present day have imbibed
a very false idea of a right education for children,
and thereby such have lacked useful knowledge, in things both religious and civil.

26th of sixth month, first-day morning.
At New Britain, the people were more than the house could contain,
I felt dismayed when it was first proposed to hold the meeting out of doors,
fearing I could not bear the heat of the sun; but being shaded by trees,
I did better than I expected,
believing the renewings of divine regard were towards the multitude as formerly,
to feed with that food which He saw best for them.
To Him belongs the praise of his own works, both now and for ever.
