== Chapter IX.

[.chapter-synopsis]
* Her Travels in America, during the remainder of the year 1796.

16th of tenth month, first-day morning.
We attended a large gathering of our own Society and others.
In the afternoon, a meeting for the black people was a very exercising time;
yet a humble trust was raised, that it would be rendered profitable to some.
In the evening, many Friends being at our lodgings,
the renewed offers of heavenly regard were manifested among us.

On fourth-day, we were at West Nottingham.
The meeting was attended by Friends, and many not of our Society;
the reaches of heavenly love went forth, to the varied states and classes of the people,
in order to gather such as were afar off, to an acquaintance with Truth;
to strengthen those who were near,
to acknowledge the Lord`'s might and seek after
the knowledge of His will on all occasions,
not leaning to their own understandings.

On fifth-day, we were at Little Britain, a painful, exercising season;
little relief was gained either in silent travail, or in public labour.

On sixth-day, at East Britain, a quiet opportunity, held mostly in silence.

23rd of tenth month, first-day.
We were at East Nottingham, where also was dear John Wigham;
it was a very large gathering,
such a one as George Churchman thought he had not seen for seven years;
and it was graciously owned by the Shepherd of Israel, in opening counsel,
tending to draw the attention of the people, to seek after the knowledge of His holy way,
manifested by his pure Spirit in their own minds; and his great name was supplicated,
on behalf of those who profess the Truth, as it is in Jesus.

On second-day, we were at West Grove, a large meeting.
It was a time of deep wading, both in the silent part, and while speaking,
under a sense that many were willing to hear what the poor exercised servants had to say,
but very few to be baptized with the baptism, or drink of the cup,
that such have to partake of;
and through reluctance to come to the practical part of what is pointed out to them,
they remain hearing, but not doing the sayings of Christ;
so that the truly anointed ministers have almost to stand alone;
few to hold up their hands, even in the exercise of their gifts.

The minds of many of the hearers being afloat, and others at ease, makes it hard,
dragging work to get along, in the faithful discharge of duty;
which seemed in a distinguished manner to be the state of that meeting;
yet with a few lowly travellers my mind was nearly united.

On third-day, at Fallowfield, a newly settled meeting, not quite so trying as the last,
was much hurt by the late coming in of many.
Through the renewings of holy help,
strength was administered to open counsel to those professing with us,
and to such as were not of our fold,
setting forth the one effectual baptism which now saveth.

On fourth-day, at London Grove, a large meeting, the labour was exercising,
yet not without some feeling, that the Holy Shepherd was near,
to help those that put their trust in Him,
and to gather the wanderers to the fold of rest.
It was their preparative meeting, in which the queries were answered in writing:
and though there appeared a considerable number likely to be active in discipline,
they got slowly forward, which is often the case to a trying degree,
by having much dependence on those in the station of overseers.
I have been much exercised for the help of Friends in many places;
which labour has generally been well accepted.

On sixth-day at Kennet, a great number attended, mostly professing with us,
there being few others in that neighbourhood.
While sitting in silence, the only availing saving principle of Truth was opened,
and raised in my view, beyond the power of words to set it forth,
though a painful sense attended, that many had gone from it.
I was engaged, in an exercising labour,
yet not without a consoling hope that there were a number preserved,
among the several classes of the people, who are seeking the way to Zion,
with their faces thitherward.

That evening, we had a religious opportunity in a large family where we lodged,
which was graciously owned by the Shepherd of Israel.

On seventh-day, at Birmingham, a very large meeting, in the settling down of it,
was remarkably covered with solemnity; and the spirit of prophecy,
or preaching (see 1 Cor. 14:3) was poured forth on sons and daughters;
opening counsel to the varied states of the people.
Thanksgiving was returned to the blessed Author of all good, to whom alone tribute is due.

30th of tenth month, first-day.
At Bradford, a large crowded meeting, more than could get in,
were assembled before we got to the house.

On looking over the people in taking my seat, perhaps I may safely say,
my heart was touched with a measure of the same compassion,
which our blessed Lord had on the multitude that followed Him into the wilderness.
Strong were the desires raised in me, that their gathering might be to seek after Him,
in his spiritual appearance, the true teacher and bishop of souls;
which subject I had to open in gospel authority;
great was the stillness and attention that appeared in the meeting,
though many stood the whole time; and a secret hope attended,
that the witness for Truth would be availingly raised in some minds.

On second-day, we were at West Cain, a poor meeting, almost worn out every way.

On third-day, at East Cain, much labour was extended;
but did not seem to have that reach on some, which would have been grateful to feel;
yet I trust the exercised part, were in some measure encouraged to hold on their way.
On fourth-day morning we were at Willistown, a small meeting of Friends,
but a large collection of other professors, among whom the gospel was preached,
tending to bring to an acquaintance with the Spirit of Truth,
through the manifestation thereof in every mind, as the only way to witness saving help.
In the afternoon at Newtown, was a mixed gathering of careless professors,
and of others who were exercised for the cause of Truth;
that it required much care in dividing the word:
but through the renewings of divine help,
such as were waiting for the consolation of Israel,
were encouragingly recommended to be often waiting in the temple;
and floating minds were invited more steadily to seek an acquaintance with Truth,
that good part that would never be taken from them.

On fifth-day at Springfield, was a large meeting of young people;
some elders wanted stirring up to more faithfulness in
the discharge of duty towards God and man;
the young people were closely expostulated with,
and strongly recommended to become of the humble, whom the Lord would teach of his ways.

On sixth-day, at Merion, I had a time of close labour,
setting forth the religious duty of parents,
to children and those placed under their care,
in endeavouring by example and precept to acquaint them with the principle of Truth;
for want of such a care many when seen in the vision of light,
resemble those spoken of by the prophet, when he saw Israel scattered on the mountains,
like sheep having no Shepherd.
This appeared to be much the state of the meeting in a general way;
yet I had to believe that a few were preserved,
desirous to walk consistently with the profession we make,
and to support the testimony thereof; such were encouraged to hold on their way,
and not to cast away their confidence in the sufficiency of that divine power,
which can yet heal breaches, and restore paths to walk in.

We got to Philadelphia that evening, in company with several Friends who came to meet us,
by whom I was informed, the meeting we had been at was once large,
and in a flourishing state, lively in the best things;
but of late years had greatly declined.

On third-day evening, 8th of eleventh month, was a meeting for the black people,
towards the close of which I had some close remarks to make to them,
fearing their different situation in regard to the outward,
from many of their sorely afflicted race,
had not had the effect desired by many minds who were nearly concerned on their account.
They were tenderly yet earnestly recommended to greater circumspection,
and care in life and conduct; and to watch over one another for good.

On seventh-day, we attended the select quarterly meeting at Concord,
a season mercifully owned by the head of the church,
who engaged some of his servants in close plain communication,
among that part of the body, which appeared to be well received;
a humble trust was raised that it would be to some, as bread cast on the water.
At this meeting we had the unexpected, but acceptable company,
of my valued fellow-labourer John Wigham.
In going to our lodgings I observed many small houses,
inhabited by workmen employed in iron-works,
belonging to the Friend to whose house we were going;
and feeling the spring of gospel love flow towards them,
I inquired if there was a place where a meeting could be had with them next evening;
to which the Friend readily resigned his own house,
and took care to have general notice given.

13th of eleventh month, first-day morning.
We attended the meeting at Concord, an exercising time,
both in silence and in public labour.
We returned in time for the meeting before mentioned,
at which dear John Wigham and some other Friends met us.
Through the renewed compassion of Israel`'s Shepherd,
counsel and encouragement was opened, and the gospel preached to the poor.
The tribute of thanksgiving was returned to the Lord, who is everlastingly worthy.

On second and third-days, we were at the quarterly and youths`' meetings,
wherein divers servants and handmaids,
were exercised in communicating caution and counsel,
to the different states of the people; and a hope was raised,
that through the continuation of heavenly regard,
it might by some be remembered to profit.
We parted with divers Friends, in much nearness of spirit, and took several meetings,
the last at Reading, a very small one of Friends;
but many of the town`'s people coming in, it was an open time of labour;
though in close expostulation,
tending to advance the pure principle of Truth above every shadowy performance, name,
or profession of religion, as the only means of salvation to man.

20th of eleventh month, first-day.
At Maiden creek; in the early part of the meeting,
a sense of that emphatical declaration,
"`Holiness becometh the Lord`'s house,`" was opened in my view;
and though little more than a lively impression was received,
I felt it right to stand up with it, having a comfortable hope, there were those present,
who understood the meaning of it, both within and without,
so that all their ways were to be ordered of Him.
To such the language of encouragement went forth; yet others seemed much in the mixture,
so as scarcely to understand the preaching of the
gospel--that upon the whole it was a trying labour;
but feeling the evidence of peace I was strengthened therein.

Early on second-day morning, we began our journey towards the mountains,
two kind Friends accompanying us, who provided a change of horses,
and some other necessaries.
We had very poor cold lodgings the first night; the second we did much better,
and on fourth-day evening, got well to Muncy, a settlement of Friends;
we attended their meeting on fifth-day, in the early part of which,
my mind was impressively opened to see what it was in the creature,
that stood opposed to the will of the Creator;
that it was the divine power alone that could subject, and give resignation,
and enable to overcome all that stood in the gainsaying nature,
as there was a co-working with its operation.
On this deeply interesting subject, my tongue was loosened to speak, I humbly trust,
as the Spirit gave utterance.

We went to dine with a family who seemed to have all in possession,
but the one thing needful,
which I had felt it so forcibly my duty to impress upon the minds of all,
as the pearl of great price.
My spirit was secretly oppressed while with them; and finding no way for relief,
I was glad to return to our lodgings, where the heads of the family felt to me,
to be labouring after a growth in the Truth,
and desirous to bring up their innocent children consistently therewith:
a young woman was also there, to whom we felt much love.

On sixth-day afternoon, we had a meeting at Fishing creek, rather a suffering time;
yet I felt nearly united in the seed, to a lowly, tried remnant.
Next morning we set out very early, having sixteen miles of rough road to Catawassa,
and the river Susquehanna to cross,
which was so full of ice that it was difficult to get the boat along.
Some Friends were detained more than an hour at the water side, but,
through providential care, all got safe, and I was glad I attended that monthly meeting,
feeling much dipped into sympathetic labour;
and I had to communicate such counsel as was opened, which afforded relieving quiet.
In returning to our lodgings, the air was so piercing, as almost to deprive me of breath,
and it was some time before the shivering ceased--that
Friends seemed afraid it would become an ague,
a complaint prevalent in the country; but through favour it went off.

27th of eleventh month, first-day morning.
We went to Roaring creek, sat a pretty large meeting there, a time of close exercise,
both in silence and while led to open counsel, caution, and encouragement;
yet it was so far relieving, that I felt at liberty to descend the mountains;
and through favour we got safe back to Maiden creek, on third-day afternoon,
which felt cause of humble thankfulness to the great Preserver of men.

Next day we attended their monthly meeting,
and had cause rejoicingly to believe it was in best
wisdom our lot was again cast among Friends there.
On fifth-day, at Exeter, on sitting down and entering into silent retirement,
I was made somewhat sensible of the opening of life;
but how painfully did it get closed up,
through the too ready admittance of ease and luke-warmness,
by many who profess the Truth as it is in Jesus.
I found it my place, towards the latter part of the meeting, low and tried as I was,
to speak of things as I felt them, in near sympathy with the wrestling seed;
and was favoured to feel some relief thereby.

On sixth-day, at Potts-Town, we attended what is called an indulged meeting, i. e,
one not fully established.
It was a season, which the gracious Shepherd of Israel owned,
in manifesting his renewed loving kindness to his little ones.

4th of twelfth month, first-day.
At Richland, a large particular, and also a monthly meeting;
too many appeared unconcerned about the weight
and importance of what they met together for,
by their conduct expressing more care how to accommodate the body,
than to profit the mind.
I had to labour closely among them, and through a faithful discharge of duty,
felt relief: my soul was prostrated before the throne of grace,
that the faith of the mourners in Zion might be increased;
that the hope of the righteous might not fail,
but that their trust might be renewed in the sufficiency of that power,
which is not of us, but of God.

At Gwynedd, on third-day, a large gathering,
for want of the foremost rank taking their proper places,
was long in settling into that quietude becoming religious occasions;
but as my mind was engaged to labour after that stillness,
wherein the Lord is known to be God,
the interesting salutation of the apostle was livingly opened in my view:
Grace mercy and peace from God the Father, through our Lord Jesus Christ,
be with your spirits: Amen.

This, from its remaining impressively, attended with a secret prayer,
that that meeting might be found worthy of the like blessing,
it became my duty to communicate.
Many things were opened, I humbly trust, in the light of Truth,
and under gospel authority, to the different states of the people;
yet it was rather a season of digging and pruning,
than of finding many plants ready for the watering.
But I was instructively impressed,
that I must be a faithful labourer in the discharge of duty, and content with my wages.

On fourth-day, we were at the Valley, a small exercising meeting; on fifth-day,
at Plymouth, in the early part, my mind was gathered into a humbling feeling,
that our great Creator was graciously waiting on the workmanship of His hand for good,
to enable mankind to become acquainted with the measure of his own gift in themselves;
in grateful acknowledgement whereof, I was led to bear testimony;
and from the relieving peace afforded to my own mind, I felt a sustaining hope,
that the witness for Truth was raised in many present.

On sixth-day, at Providence, I was early impressed, that it was eternal life to the soul,
which all mankind stood in need of; on which subject I was opened,
to point out the way whereby it might be experienced; and I humbly trust,
through best help, many were made measurably to feel the truths of the gospel.

After a religious opportunity in a Friend`'s family, we proceeded towards Radnor.
On seventh-day, was a large meeting there, wherein I was dipped into suffering,
in silent travail with the seed oppressed in many minds,
not feeling any expectation I should be able to gain relief,
until the gentle movings of life,
accompanied the revival of the gracious promise formerly given:
"`Because thou hast kept the word of my patience,
I also will keep thee from the hour of temptation;`" and the
language of encouragement went forth to the sincere-hearted;
yet on the whole it was a very exercising time, and there was not so much relief gained,
as at some other seasons.

11th of twelfth month, first-day.
At Haverford, many assembled not of our religious profession.
It was a season of searching labour, in close expostulation and caution,
against a spirit of unbelief,
and everything that tends to separate from the divine harmony.
I had much greater openness to declare the truths of the gospel, than the day before;
and my mind was renewedly humbled in thankfulness to the Author of all good,
for his unspeakable gift to the children of men.
We reached Philadelphia that evening,
and attended the morning meeting of ministers and elders next day; in the afternoon,
had a religious opportunity in a Friend`'s family, and in the evening,
one with divers Indians of two different tribes, collected at a Friend`'s house.

Several expressed their gratitude to the good Spirit,
and wished to have in writing what they had heard,
that they might communicate it to their brethren, when they returned home:
after a pause in silence I told them, through an interpreter,
if the good Spirit should put any thing further into my mind towards them,
I would endeavour to comply with their request; which I did a few days after.

We stayed in Philadelphia nearly four weeks;
in which time we visited divers who were ill and infirm, also some of the schools,
and attended about thirty religious meetings.
In the last, for children, about seven hundred were supposed to be present,
who are in some sort under Friends`' care, in obtaining learning,
though the greater part are not members.
Much salutary counsel and caution was communicated to them and others,
from divers Friends, which I hoped might profitably impress some of their minds.
