== Chapter X.

[.chapter-synopsis]
* Conclusion of her first visit to America.
* 1797.

On leaving Philadelphia, we crossed the river Delaware in our wagon on the ice,
accompanied by our valued friend Samuel Smith; and after taking some other meetings,
we were on 15th of first month, first-day, at Woodbury.

The people of other societies being informed that strangers were there,
the meeting was very large; and through the renewings of holy help, I humbly trust,
the gospel was preached, reaching the witness in many minds.
On second-day, we returned to the city,
and after attending three meetings for worship there,
and three monthly meetings for ministers and elders, we went to Germantown,
where we again met my nearly united fellow labourer John Wigham.
At the close of a meeting with Friends next morning, I was impressed with a concern,
to have another in the evening, for those not professing with us,
which was fully attended, and I trust mercifully regarded by the compassionate Father.

5th of third month, first-day.
We were at a meeting at Moorestown,
which was largely attended by those not professing with us,
to whom the gospel was preached, in the renewed ability which Truth furnishes.
On third-day we got to Philadelphia again, where further labour presented divers ways,
with much openness for it, both in public and private.

The latter end of this month, in the general spring meeting for ministers and elders,
(since discontinued,) my valued fellow labourer John Wigham,
informed Friends of his prospect of being nearly
released from further service in these parts,
and obtained testimonials from them, of near concurrence with his acceptable labours.
But the time did not appear to be come for me to give the like information,
which felt no small trial to the natural part;
yet I found resignation was the way to peace.
During our stay in the city, in company with several other Friends,
we paid two visits to the prisoners, going to some in their cells,
and others more at large.
We had cause to hope the witness of Truth was raised in many minds, and that,
through true repentance and amendment of life, their sins would be forgiven.

The 16th of fourth month, first-day.
Under the renewed humbling prevalence of our Heavenly Father`'s love,
which unites his flock and family wherever scattered,
we parted with our near and dear friends there,
having again with us our valued companion Joseph Whitall.

We went to Burlington,
from whence we were accompanied by our much esteemed friend John Hoskins,
to Shrewsbury quarterly meeting,
the several sittings whereof were times of close searching labour indeed;
but in the upright discharge of duty,
I was favoured with a renewed portion of that precious legacy,
our blessed Lord left with his immediate followers:
(see John 14:27) From thence we went to Plainfield, where on second-day afternoon,
we had a large satisfactory meeting.
We got to New York on third-day evening;
and early next morning crossed the river to Flushing, on Long Island;
the quarterly meeting for ministers and elders beginning at ten.
A renewal of strength to labour in the several sittings was furnished,
much to the relief of my own mind, and I believe the satisfaction of Friends.
We then proceeded to take the rest of the meetings as follows: Cowneck, Westbury, Jerico,
Matinicock, Bethphage, Hollow-hills and Newtown,
visiting some who were sick in their families;
and we felt united to the faithful labourers of every class.
Through divine favour we got safe back to New York on sixth-day evening.

7th of fifth month, first-day.
In both meetings, I was strengthened publicly to labour in the discharge of duty.
On third-day our nearly united friend and
companion Joseph Whitall left us to return home;
my prospect being to stay mostly in the city, till the yearly meeting.
During this time we visited some who were indisposed,
and divers Friends`' families as way opened; and attended a small meeting at West Chester,
where were many not professing with us; some, as I was afterwards informed,
were great men, two of them judges, of what is called the Supreme Court;
but the Great Judge of all the earth being near to help,
I was enabled to discharge my duty, so that I trust His cause did not suffer;
but that His holy name was magnified before the people.

During the yearly meeting, great was the travail of my spirit,
that tenderly visited minds among the younger part of our Society,
might not take up a rest in any outward form, however supported by tradition;
or have any bonds laid upon them, other than through the influence of His pure Spirit,
who remains to be the infallible teacher, and who declared his yoke to be easy,
and his burden light; and blessed be His name,
those who like Him are meek and lowly of heart, will assuredly find rest to their souls.

On sixth-day evening the yearly meeting concluded.
Next day we parted with many brethren and sisters,
in the nearly uniting cement of gospel fellowship.

4th of sixth month, first-day.
We stayed the morning meeting, and on returning to our lodgings,
I felt the secret arising of gospel love towards the servants, in the family,
though not members of our Society; and in giving up thereunto,
could feelingly bear testimony, that as is the soul of the master,
so is the soul of the servant, in His sight who is no respecter of persons.
It was a contriting season; and in much tenderness at parting,
they wished the Lord might bless us.
Many Friends coming in, the heart-tendering love of our Heavenly Father was again felt,
and his great and holy name supplicated for the continuance of his preserving power,
that it might be round about His heritage;
and that his grace might be manifested to be sufficient, in every trying season.
Being thus renewedly favoured to partake of the wine of His kingdom,
the tribute of thanksgiving and praise was offered; for unto Him it belongs,
both now and for ever.

We then took a tender and solemn leave, and embarked for Rhode Island,
in company with our valued friend Charity Cook, from South Carolina,
and divers other Friends.
We sailed about fifteen leagues that night, when a thick fog coming on, we cast anchor.
About midnight the wind blew very hard, accompanied with thunder, lightning,
and heavy rain, which appeared awful, our situation considered; but,
in humble confidence that we were under the notice of Israel`'s Shepherd,
my mind was favoured to be stayed upon Him.
About two o`'clock, the storm abating, we weighed anchor, and through divine favour,
got to Newport before six in the evening without being much tried with sickness.

The different sittings of the yearly meeting for New England,
were seasons of heavy exercise, yet, through divine help, a little strength was renewed,
to labour with other concerned brethren and sisters,
for right order in the discipline of the church; and a general concurrence prevailed,
that their meetings beginning at an earlier hour, would tend to more profit;
and the ninth was concluded upon instead of the eleventh; which, for the cause`'s sake,
was relieving to my mind;
the heat having been frequently so oppressive at that late hour,
that the body was scarcely able to support its feelings,
and the best life was thereby greatly borne down;
and nothing could be advanced for the continuance of that late hour,
but the bias of old custom,
which many exercised members were religiously engaged to break through.

We stayed the week-day meeting, and on sixth-day,
after a humbling opportunity with divers young people at our lodgings,
we went to Portsmouth; and next day to New Bedford,
in company with my valued fellow-helper John Wigham.
My dear companion having been absent from her near connections two years,
and preserved through many trials, both within and without,
her being now favoured to return in usual health,
was cause of mutual thankfulness to the blessed Author of all good.

18th of sixth month,
first-day morning.--Our Divine Master graciously condescended to own us together,
in our religious approaches before Him; which,
with the quiet retreat after attending so many large gatherings, was peculiarly grateful.
On seventh-day we went on board the packet with many other Friends,
to attend the quarterly meeting at Nantucket;
the several sittings whereof were times of heavy exercise,
though in one of the meetings for discipline I got some
relief I stayed a week longer on the island,
and attended other meetings that came in course,
wherein the life of truth was mournfully low;
and my spirit was much exercised in silent travail,
and in sympathy with the few living members,
though the number in each meeting seemed so small,
as scarcely to be able to bear the weight of the dead.
We left a Friend there visiting families;
and though there appeared little fruit from former labours of that sort,
I was willing to hope it might tend to stir up the pure mind in some,
and quicken others to more diligence in the most important business.

Having sometime felt my mind drawn, to see Friends once more of Salem monthly meeting,
on the 8th of eighth month, I set out with my beloved companion, and went there.
We paid a religious visit to a Friend confined by illness,
and returned with Friends to Lynn, where the monthly meeting was largely attended,
and proved a relieving season, though a time of close labour,
in trying to awaken those who were at ease;
but much encouragement was handed to the exercised part of the family.

A meeting being appointed for us at Boston next day, we attended it.
Though on our sitting down,
my spirit was deeply exercised under a weight of discouragement,
so as almost to repent of our coming, yet, by sinking low and waiting in patience,
I was preserved in humble dependence on the Lord.
After some time divers not of our Society came in, who appeared to be of the higher rank,
and one, if not more, I understood afterwards, was of the order of Priests.
He that is mighty opened counsel,
tending to raise his own blessed principle of light and life, above all outward forms;
and true gospel ministry over that which is attained by man, through any other channel.

At Bedford monthly meeting, held 22nd of eighth month,
I had a further relieving opportunity of opening counsel,
as my mind was religiously impressed with it.
Great indeed had been my solicitude for the welfare of every class,
appertaining to the flock and family; being strengthened to believe,
that if divers peculiarly visited minds,
are found faithful in the discharge of their duty, rendering to God and man their due,
the present and rising generation,
will become more and more like a field which the Lord hath blessed.

In the evening at my lodgings, when divers Friends were present,
my heart was renewedly humbled, under a sense of our Heavenly Father`'s love,
uniting like bone unto bone, in the spiritual kindred,
of which I had to make some mention, in much contrition of spirit;
also to commemorate the time of my first entering their borders,
when a baptism as unto death was witnessed, and every pleasant picture so marred,
that I seemed unable even in the common line of affection, to love those,
I had before known and loved.
Read this, fellow-traveller, thou that canst! and know thereby,
that times and seasons are in the Lord`'s hand;
and the return thereof is to be waited for in the abasedness of self.
Then shall we be strengthened, in the ability received of Him,
in all His dispensations to rejoice evermore, to pray without ceasing;
and in every thing to give God thanks.

Next morning I was enabled to part cheerfully with some,
who seemed to feel as near to me as my natural life; indeed I fully believe,
united in that fellowship that will last beyond time; and,
accompanied by my beloved companion, her father, brother and sister, went to Providence,
where we attended meeting next day.

On sixth-day the two latter returned home, and our kind friends Moses and Mary Brown,
went the first stage with us towards the city of Hartford, in Connecticut.
We lodged at a tavern there on seventh-day night,
at which the people appeared well disposed;
so that way opened to have some religious conversation with them,
and to leave some books, which were gladly accepted.

27th of eighth month, first-day morning.
We sat meeting with the newly convinced Friends at West Hartford,
with whom we had been two years before.
I was thankful to feel they had made some progress in the way and work of Truth,
wherein I had to encourage and bid them God`'s speed.
At four in the afternoon, a meeting was appointed about a mile distant,
for those not of our Society; which was largely attended.
Soon after taking my seat, the word of life accompanied the opening of this passage,
recorded in the Scriptures of Truth: "`I am the Lord thy God,
which teacheth thee to profit,
which leadeth thee by the way thou shouldst go:`"
and it became my religious duty to revive it.
Through the renewings of Holy help, the gospel was preached,
and the pure truth exalted beyond all forms.

On second-day morning early we pursued our journey,
not making any other stop in a religious line,
than to have conversation with serious individuals and to leave some books.
So peaceful a release from more extensive labours in this part of the vineyard,
was rather unexpected to me; my mind, in first passing through Connecticut,
having felt much exercised on account of the people--the
disposition of whom is greatly altered towards our Society,
and there is now an open door to labour,
where a spirit of opposition and persecution in earlier times,
had strongly barred the way.
My desire was to stand in entire resignation to the Divine will,
and this at present appeared the accepted offering in his sight; whether He may see meet,
in any future day, to call me again to labour there, or on any part of this continent,
remains among his hidden things; but all within me craves that His holy will may be done,
and that every day I live may be unto Him, in entire subjection and dedication of will.

With close travelling we got to Friends`' meeting at Purchase, in York State,
on fourth-day, which proved a satisfactory one,
where we unexpectedly met our valued friends John and Catharine Murray, of New York;
with whom we returned to the city next day, after attending the meeting at Mamaroneck,
which was a time of close labour,
in laying judgment to the line of the transgressing nature,
and in feeling with and for the oppressed seed.
After a religious opportunity in a Friend`'s family, we went on to New York,
and got safely there late in the evening.
Here we received affecting accounts,
of the yellow fever having broken out again in Philadelphia;
but feeling my mind pressed forward to pursue the prospect in view,
we proceeded to Rahway, in New Jersey, on seventh-day.

3rd of ninth month, first-day.--We sat two meetings with Friends and others,
which through Divine favour, proved relieving seasons:
and in the evening I was particularly refreshed,
under a fresh sense of the gracious extendings of the love of Christ,
when he told his immediate followers:
"`Ye are they which have continued with me in my temptations;
and I appoint unto you a kingdom.`"
I had to make some mention of this for the encouragement of those present,
to faithfulness in following the Lamb whithersoever he might lead;
not so much with a view to any reward here or hereafter,
as to manifest our obedience to his pure law, who is just in all his ways,
and righteous in all his doings.

Next day we went to Mendham, and on third-day were at an appointed meeting there,
in the early part whereof, the precious incomes of love and light appeared to be opening.
My spirit suffered much hidden exercise for a considerable time,
lest the Lord`'s opportunity should be in any wise frustrated,
through the unsettledness of the meeting in its long gathering,
and some disturbance from young children;
but through the dedication of my dear companion, in giving up to the pointings of duty,
the door got a little opened for my standing on my feet; and through unmerited mercy,
strength was given to preach the gospel to the poor,
and to exalt the testimony of Truth above all opposition.

Being a fine moonlight evening we got safe back to Rahway about nine o`'clock.
Next day we visited divers Friends in their families,
and on fifth-day I was favoured with a further relieving time in their meeting,
peculiarly towards the youth:
also in a parting opportunity with divers Friends in the afternoon.
We then went home with a Friend three miles into the country,
where divers came to see us next day; and before we separated in the evening,
we were renewedly contrited together under a fresh sense of our Heavenly Father`'s love,
wherein I had to express a belief, it would be a season to be remembered,
when the great deeps might divide us one from another outwardly.

10th of ninth month, first-day.--We attended meeting at Stony-brook,
a time of close labour,
having a threshing instrument to lift up against the transgressing nature in man;
yet the language of encouragement went forth to the mourners in Zion;
that such might so steadily hold on their way, as to know Him in whom they have believed,
to be a covert from the heat and from the storm,
and as the shadow of a mighty rock in a weary land.

The same evening about sunset we got to Nathan Wright`'s,
where I found my endeared friend, his wife, in better health than when we left her.
I had for some days been weightily brought into feeling with Friends,
under the solemn prospect of attending the yearly meeting in the city of Philadelphia,
the disorder there making a more rapid progress;
and some considerations occurred respecting the propriety of solid Friends meeting,
and feeling together after the pointings of Truth, whether to hold it at the usual time,
in the city, or at any other place, or to adjourn it to a future period.
This I particularly wished two valuable Friends,
who were under appointment as representatives from their quarterly meeting,
and who had come with us from Rahway, to weigh in their minds;
and if spared till morning I should be willing to accompany them to Burlington,
to consult our elder brother John Hoskins and others, on a matter of so great importance.

The proposal appeared relieving to them, also to our friend William Rotch,
who was dipped into much exercise on that account, he accompanying us.
We had a solid conference together, the result whereof was,
for J. H. to go next morning to Frankford,
where some Friends who came out of the city had lodgings, to spread the matter farther,
as way might open.
The concern being thus far moved in, we returned in the evening to Nathan Wright`'s,
and the Friends from Rahway expressing great satisfaction in the steps taken,
went homeward early next morning.

On fourth-day we attended Mansfield meeting, where, on taking my seat,
my spirit was soon covered with solemnity,
in secretly viewing the design of the Lord`'s judgments being again on the earth;
and strong were my secret cries to Him,
that the inhabitants might thereby learn righteousness.
My dear companion giving up to supplicate His holy name,
under an impressive similar sense thereof,
my way was made more easy to discharge my religious duty, in close expostulation;
wherein our valued brother and fellow-labourer John Cox,
who came there to meet and conduct us to his house, was a co-worker,
and fellow-helper in the Lord.

Next day we were at Burlington,
where many families of Friends from the city were residing,
on account of the malignant fever; among whom I had again to labour after a close manner,
to remind them of the only refuge for the righteous,
and that those who are living in a state of forgetfulness of God,
not remembering their latter end,
would be in great danger of not finding this sure hiding place in the day of trouble;
in which line of labour our before mentioned friend and brother, was led nearly to unite,
bearing further testimony thereunto; so that, as formerly, it might be hoped,
"`that in the mouth of two or three witnesses, every word may be established.`"
However, whether those that hear will obey or not,
it becomes stewards to be found faithful,
and such as the Lord anoints for watchers on the walls of Zion, not to keep silence,
when his voice says: "`Cry.`"

Next morning we set out to attend the conference which
Friends had concluded should be held at Frankford;
to which place I can truly say, I moved forward under great weightiness of spirit;
and on taking my seat there, the desire of my heart was granted,
in feeling myself as one without purse, or scrip, or change of dress;
that the fresh impression and sense of Truth then opened,
might be singly and solely my director,
if I should have any sentiment to drop in that opportunity.

The conclusion to hold the yearly meeting in the city at the usual time,
was neither unexpected nor uneasy to me;
indeed any thought or part I had taken on my own account was very small,
compared to the exercise I had been dipped into,
for many tender-spirited Friends in the country, who I believed,
were as much concerned for, and dedicated to, the cause of Truth,
as those who had felt themselves bound to stay in the city; but who,
from the numerous inhabitants of it fleeing through their borders,
and the affecting accounts daily brought, that the disorder was spreading,
looked upon themselves somewhat as sheep preparing for the slaughter,
in attending the yearly meeting there at that time.

May I never outlive the season of fellow-feeling with members in suffering,
from whatever cause it may arise;
for I believe this will never have a tendency to shake the confidence of any,
in Divine superintendence, and the all-sufficiency of the Lord`'s Arm to preserve;
while it may bow them to the root, and like accepted Gideon,
bring them to try the fleece, both wet and dry.
I wish the number of such to increase in many other matters of importance,
as well as the present; for then I believe fewer would move on the shallow waters,
or confide in the form or profession of Truth, short of the power, which is of God,
and not of man.
We went home with Nicholas Wain, who resided at Frankford;
and in the evening had a tendering opportunity, in addressing one of his sons.
I was also on my own account desirous to know, and do, what was right,
in regard to my religious movements, in this critical and trying juncture;
that nothing might move me on the right hand or on the left,
short of the secret intimation of His pure Spirit;
which I have much cause to believe I was mercifully favoured with,
in directing my course to the city.

17th of ninth month, first-day morning.-- We attended Market street meeting,
and my way was opened to labour among the remnant that was left,
as also at the North house, in the afternoon.
Friends at both places expressed their gladness to see me; particularly some, who had,
through mistake, been informed that I did not feel liberty to come among them,
even to attend the yearly meeting, on account of the prevailing disease;
but so far from having had any such sentiment,
when favoured to feel the pointings of Truth to direct my course,
my mind was preserved both from terror and fear; yet I humbly crave,
both for myself and others, a careful seeking after that wisdom,
which dwells with prudence; and not to run unhidden,
through any presumption of the creaturely will.

On second-day we attended the monthly meeting at Frankford,
I was engaged to encourage and strengthen Friends to
stand faithful in their testimony against wrong things,
even in their nearest connections, and thereby to manifest they loved Truth above all.
That evening we went to Byberry, and next morning, in our way to Abington,
called to visit a beloved Friend, and fellow-labourer in the work of the ministry,
who was brought into a vey weak state through bodily illness;
that her recovery was doubtful.
We were humbled and comforted together, under a fresh,
sense of our Heavenly Father`'s love,
of which she expressed a grateful and thankful feeling.
We then proceeded to a meeting appointed on account of a burial there,
wherein gospel truths were opened, in close expostulation among those gathered,
many of whom appeared much unacquainted with the way and work of truth;
yet I trust some feeling minds were encouraged to persevere in well doing,
that thereby they might be made meet for the kingdom of heaven.

We had a religious opportunity in the Friends`' family where we dined,
with whom I could feelingly sympathize, in the trial they had recently met with,
of their only son, a hopeful youth, losing his life in the water.
Our lodgings were at our kind friends S. and H. Fisher`'s,
who were residing at a country house, about four miles from Philadelphia;
and next day they with us attended Pine street monthly meeting,
wherein I had to believe that as sufficient for
the day might continue the evil or trial of it,
so by an indwelling with the pure seed, or word of life,
renewal of strength in the inner man would be equally witnessed,
in every afflictive dispensation, whether from within or without;
some hints whereof I had to mention, for the encouragement of the poor in, spirit.

On fifth-day my dear companion, her father, and myself,
again attended the meeting at Market street, and on sixth-day,
a public one appointed at Germantown,
where divers came besides those of our religious Society; and I humbly trust,
through holy help, the gospel was preached, and the great name of our God was praised.

On seventh-day morning the yearly meeting for ministers
and elders began in the city-- a solemn season indeed,
wherein my spirit was early bowed to supplicate the Lord on high,
that the courts of his house might be the hiding place of His Israel;
where all would be preserved, in such childlike dependence upon Him,
that self could have no room to boast of its own strength,
or dare unworthily to judge those whose hearts might mediate terror,
or through fear of taking the prevailing disease, did not assemble;
and there was some cause to believe the petition was in a good degree answered.
The religious state of Society, respecting that part of the body,
was weightily entered into.

24th of ninth month,
first-day.--The meetings for public worship were reported to be small, but solid,
instructive, edifying seasons, which I fully believe was a just report;
and it livingly sprang in my heart to express a sentiment then revived,
as one part of the cause; that most who assembled,
had felt deeper after their motives for coming,
than when no uncommon obstruction appeared,
and so had somewhat experienced a fulfilling of the declaration:
"`Every one shall be salted with fire, and every sacrifice salted with salt.`"
The women`'s meeting opened as usual at Market street, and though very small,
I thought not more than a tenth part of the number that assembled the year before,
it was favoured with much solemnity,
under which covering the affairs of the Society were entered into; and I trust it.
will be safe to say, were conducted in the wisdom of Truth.
In the afternoon a Friend from the men`'s meeting came to inform us,
that they had adjourned to the large part of the North house,
being in a district of the city in which the disorder had not made so much progress;
which was acceptable tidings to some of us,
the desire of being near together having previously prevailed.

Our meeting accordingly met next morning in the small part,
which was much more than sufficient to hold us, on the ground floor.
In the second sitting of the select meeting,
the certificates of our friend Gervas Johnson, from Ireland, were read,
and much sympathetic encouragement spread towards him;
after which it appeared to be the time to open my prospect to Friends,
of having a peaceful release to return to my native land,
when the yearly meeting was over, if life and health permitted;
and some were appointed to prepare a certificate respecting me,
which was brought to the next sitting; and appearing to be cordially united with,
was signed by the clerk.
Our closing select opportunity was on fifth-day morning, when,
through the fresh extendings of our Heavenly Father`'s love, our spirits were contrited,
and enabled to say farewell! in the Lord.

After this was held the meeting for worship at Market street, in which,
almost on taking my seat, the word of life arose in me to say: "`Fear not,
daughter of Zion, behold thy King Cometh, meek and lowly,
etc.`" on which subject I was enlarged, much to the relief of my own mind,
and I trust to the encouragement of many present.
Several of my fellow labourers were also engaged to preach the gospel.
This was the last public meeting I was at in the city:
and I believe will be remembered as a solemn one, to many minds.
The remaining sittings of the women`'s meeting were weighty:
the holy Head of the Church being near, strengthened to labour,
for the help and edification thereof; also to part from one another on sixth-day,
29th of ninth month,
under the humbling sense of the prevalency of His heart-tendering love;
wherein His holy name was praised, who is eternally worthy.

After contriting religious opportunities in several families, we left the city;
and on the way to our lodgings in the country,
called to take leave of our endeared friend, Rebecca Jones,
who was under the weight of bodily indisposition; with whom, and the Friend she was with,
we were again favoured with the precious ownings of Heavenly regard;
and thereby I trust enabled as formerly, to put one another forward after a godly sort.

On seventh-day morning, we proceeded on our way to New York;
from whence a prospect had previously opened, that I might embark.
We called to take leave of the widow of our worthy friend John Pemberton, with whom,
and her sister Sarah Zane, we had a religious opportunity,
as we had also at our friend M. F.`'s, where we dined,
several families of their connections being present;
among whom were some tender plants of our Heavenly Father, who had often felt,
and now at parting did feel in a peculiar manner,
very near to my natural and spiritual life.

We got well to New York,
where to our comfort we found that my endeared fellow labourer John Wigham,
had returned from Nova Scotia, in order to embark for our native land.

Having a prospect of taking passage in the ship Severn, bound for Liverpool,
we went on board, and found our minds easy to engage places therein;
our friends Charity Cook and Mary Swett, going on a religious visit to Europe,
intending to embark with us; also E. W. returning home.
During our stay, we attended meetings as they came in course,
and one appointed for the black people.

On second-day evening, our farewell opportunity took place,
with many I dearly loved in the Truth, and I trust was nearly united to therein,
particularly my endeared companion and her worthy father,
with our very kind friends John Murray and wife, and their dear children;
but had renewedly to experience bitter cups to nature and spirit sweetened,
through the humbling, yet strengthening influence,
of our Heavenly Father`'s heart-tendering love; in which we were enabled to greet,
and bid one another farewell!
May his ever worthy name be praised, by all his called and chosen children,
is the renewed fervent prayer of my heart.
