== Chapter XII.

[.chapter-synopsis]
Her travels in England, and second voyage to America.

After my return home, many trials and exercises fell to my lot,
fully known only to Him who seeth in secret,
and who can sanctify every allotted or permitted trial.
And if through much tribulation we are made meet for the kingdom,
the great and blessed end will be answered.

From this time I did not travel any long journey for some years;
but after the yearly meeting, in 1800,
I felt an opening prospect of visiting some meetings in the southern counties;
and when the time appeared to be drawing near, I was about to address a young woman,
an acceptable minister, on the subject of bearing me company; but the prospect I had had,
seemed rather suddenly to close: and in waiting to know the Master's will,
the in-speaking voice was clear to my understanding;
"`Thou may'st resign the southern prospect, and look towards the north,
and join my deeply tried handmaid Elizabeth Coggeshall.`"
I was not left in the least doubt respecting the intimation;
so when our monthly meeting came on, I informed Friends what had been my prospect,
and what it then was; and if united with, I wished it might be mentioned,
that my concern was to join the said Friend from a sense of religious duty;
which was accordingly inserted in my certificate.

I received a letter from her dated at Ulverstone,
stating that the Friend who had accompanied her for some weeks was so ill,
that her recovery was very doubtful;
and having no companion in view she was much dismayed;
so in the twelfth month I met her at York.

She was then and during the remaining part of the journey, under deep exercise of mind,
in which according to my measure I nearly partook with her;
that the cement of our fellowship was much in suffering,
and as I have found this to be as strong a bond of union,
as any part of the gospel travail, so I trust the bond will not be broken through time.
She took such meetings in her way to London, as she had not been at before;
and after visiting those in that city,
and being furnished with a certificate from the morning meeting,
as a committee of the yearly meeting of ministers and elders, we returned northward,
and in the latter end of the fourth month, 1801,
I went with my endeared friend and companion,
on board the vessel about four miles from Liverpool,
in which she embarked for her native land.

Several months before leaving America,
the mind of Martha Routh appears to have been attracted homeward,
under painful apprehensions of the approach of a domestic affliction,
which afterwards fell out as she had anticipated.

On this occasion she conceived the returning home, pretty speedily,
to be the most proper step; and she entered into covenant with her Heavenly Father,
that if He would be pleased to permit her return to her outward habitation,
and should afterwards call her forth to labour further in that part of the vineyard,
she would, through his renewed assistance, obey His will.
Accordingly, in about three years after her return,
she informed her friends how it had been with her, and how it still remained,
as to her going again to America.

Respecting this voyage she gives the following brief account,
I felt more easy to be certified of, as going to reside in America for a while,
than singly on the ground of religious duty as heretofore; because,
being under the care of Friends there as a member,
if preserved to keep my habitation in the Truth,
I might obtain their certificate for any further religious movement that should open;
and when the time appeared fully come, my certificate was, at my own request,
addressed to the monthly meeting of Friends at New Bedford, in Massachusetts.

We (my husband and self) took our passage on
board the Alleghany from Liverpool to New York,
in company with our valued friends Charity Cook and Mary Swett,
returning from their religious mission in Europe, a Friend from Liverpool,
intending to settle in America, and a little orphan child, who descended from Friends.
On this voyage, of which I sent an account to my cousin Susannah Hadwen of Liverpool,
my spirit was often deeply wounded with the dark state of our captain,
who had once been a member of our Society.
After a passage of sixty-six days, we arrived safely at New York,
where we were kindly received by our friends John and Catharine Murray;
and after stopping some time we proceeded to New Bedford,
where we were welcomed with the greatest cordiality.

In about three months after our arrival,
my mind was much turned towards Friends' school at Nine Partners,
on account of which I had felt nearly interested in my first journey;
and my former dear companion L. R., with her brother, accompanied me thither,
through a part of Connecticut, taking meetings as we passed along,
till we came into the state of New York.
We attended two quarterly meetings, and stopped about three weeks in that seminary;
her brother leaving us there, to attend the yearly meeting at Philadelphia,
where he had opportunity to be at the burial of
my endeared fellow labourer Sarah Stephenson.
He again met us near the time of the yearly meeting at New York;
which having lately been the field of that beloved Friend's gospel labour,
was a very solemn and interesting season.

We then journeyed towards New Bedford, taking meetings as our way opened;
and to find my husband and the families favoured with health,
was cause of renewed thankfulness.

In this little journey we travelled about seven hundred miles.
The yearly meeting on Rhode Island coming on soon afterwards, I attended it,
in company with several of W. Rotch's family, with whom I returned;
staying pretty much in the neighbourhood of New Bedford for some time,
except going to the island of Nantucket, accompanied by my friend E. Rotch the elder.

Now a more distant prospect opened before me;
but trials and difficulties seemed so in the way, that I scarcely knew how to move.
After some time of weight and exercise,
I requested to be recommended to the monthly
meeting of the middle district in Philadelphia;
and I found I had not missed my way in going thither,
for an exercised female minister +++[+++Elizabeth Foulke]
had a little time before, spread a concern to visit such individuals,
as from one cause or other, had been disowned by that monthly meeting,
originally the only one in the city, and who remained separated.
Some had been disowned as far back as thirty years.
A man Friend, a minister of the same meeting, feeling near sympathy,
offered himself to accompany her, but after paying two or three visits told her,
he believed his free-will offering was not accepted by the Master,
and that he could not go forward under this apprehension.

Elizabeth Foulke feeling the weight too great without a fellow labourer,
could not proceed.
Thus deeply exercised, she wrote to James Simpson, a valuable minister in the country,
adopting the language of the man of Macedonia, to come and help her.
He informed her, that he believed it was not his business;
but in a dream or vision of the night, he had seen a female Friend,
who he was persuaded was designed to be her helper.
Still remaining under the burden, which she scarcely knew how to support,
she had informed my dear friend Phebe Pemberton, of her tried situation,
a little time before our arrival; and two days after came to my lodgings,
with a deeply exercised countenance.
I wished her to say nothing to me on the subject till after the monthly meeting was over.

It was held the next day;
when I desired her to accompany me to the men's meeting to present my certificate.
After the brethren had accepted it,
and expressed their satisfaction at my being amongst them again,
Elizabeth Foulke informed them, she had made little or no progress in the visit,
on account of being left alone.
After a silent pause, I told Friends, if it did not seem too hasty,
and was united with by them, I felt a willingness to accompany her;
which was more approvingly spoken of, than may be needful for me to remark.
Our valued friend David Bacon, in the station of an elder, was appointed to attend us,
and proved indeed our fellow helper in Christ.
Before we proceeded, I felt most easy to have the before mentioned friend, Peter Andrews,
enquired of, if he was quite clear in giving up the visit; he said he was,
and thankful I was sent instead.
We then moved forward as way opened;
and the united band had cause to commemorate the mercy and kindness of Israel's Shepherd,
whose crook was held forth to gather the lost sheep:
some of whom have since returned to his fold,
and become public testimony bearers of His goodness,
and that His mercy endureth for ever.

Our kind friend Phebe Pemberton acceptably accompanied
us to divers meetings adjacent to the city,
till near the yearly meeting, at which a Friend spread his concern,
to pay a religious visit to Friends in Great Britain and Ireland,
which was fully united with;
and my husband being desirous of returning with him to England,
he sailed in the same ship; and they were favoured with a quick and safe passage.

As my way opened, I had suitable companions to many meetings round about;
my valued friend Anna Mifflin accompanied me into the Jerseys,
as far as Egg Harbour and Cape May; also our kind friend and attendant Samuel Cooper,
of Pleasant View, with his carriage, another Friend being on horseback.

Through best help we got along without any accident,
though some of the roads were getting bad.
Returning safe to Philadelphia, I continued there about two months,
attending meetings almost every day, as they came in course;
and some others out of the city, with the schools at West-Town.

About this time my feelings were awakened to look homewards;
and finding I was not clear of some meetings in New England, my kind friend Sarah Zane,
a younger sister to the pious widow of that meek and suffering disciple of his Lord,
John Pemberton, being certified of by Friends of Philadelphia,
we set forward in the twelfth month, when the river Delaware was so full of ice,
that some of our Friends on shore were anxious how we should get through;
but being met by our affectionate friend Samuel Cooper, with his own boat,
I felt no fear of our safe landing, or dismay at the apparent danger;
though it took a much longer time than usual.
We were so cordially received at his pleasant home,
that the difficulty was soon compensated; and next day,
with our kind attendant George Williams from the city, we proceeded for New York,
which we entered the last day of the year 1804.

The weather was extremely cold, with a considerable fall of snow,
though not so deep as afterwards; for before we got to Hartford,
it was scarcely safe for wheels to pass;
yet we attended the meeting next day at West Hartford.

After a public meeting in the city we went in a sleigh to New Bedford;
our before mentioned friend returning to Philadelphia.
We went pretty swiftly along on the snow;
but the motion brought on something like sea sickness:
looking very pale when we arrived at the inn,
the landlady said many were affected in like manner;
but in due time we got safely to New Bedford.

After again attending several meetings in that neighbourhood,
my way was impressively opened, to go to a few meetings eastward, as far as Boston, Lynn,
and Salem, with female companions, and Joseph Austin.
We did not stop a meeting at Boston, but gave expectation to the Friends where we lodged,
of being at one there on our return.
During our absence, a Friend from Nantucket came there on business,
and being well acquainted with a wealthy merchant of great repute, named Samuel Parkman,
informed him of our intentions.
At the time expected, he sent a servant to meet us on our way from Salem,
to take us the best and nearest road to his house.
When we got into the parlour, a large room, I thought of Cornelius the Centurion;
for he seemed to have gathered up his relatives, and connexions, young and old,
who received us as though we also had been their near of kin;
that my heart was contrited in the recollection of the very different reception our
suffering brethren and sisters had formerly met with at that place.
Though nothing further opened than a liberty for social conversation,
and answering the enquiries made of us,
it appeared to be a mutually satisfactory interview.

My mind was however secretly under weight respecting the public meeting:
I had thought of the tenth hour; some proposed eleven o'clock.
I said, I had mostly left these matters to those resident in a place, but at that time,
ten o'clock seemed to fix with me.
After a little pause, Samuel Parkman replied: "`And I believe you are right;
for it is our Quarter Sessions here, which open at twelve o'clock;
it will give more liberty for such as incline to attend, than a later hour.`"
So after desiring those who were to give notice, to request punctuality to the hour,
we went to our lodgings.
The meeting collected very fully and punctually,
and Samuel Parkman appeared to have brought the numerous
company we had been with at his house the evening before,
whom he seated in a suitable manner, and then sat down in the gallery,
by the Friend who attended us.
Seeing divers come in who seemed of the great of the earth,
my spirit was awfully bowed before the Throne of Grace, for help and direction.

The meeting was scarcely more than fully gathered into quietude,
when the word of life arose, with that authority which I durst not dispute,
though on leaving my seat I saw little more to express, than:
"`With the word of a King there is power.`"
And may my soul ever bear in grateful remembrance the truth of this assertion,
as applicable to the King of kings, who graciously condescended to be mouth and wisdom,
tongue and utterance, till I felt clear of apprehended duty,
in bearing testimony to the all-sufficiency of His power, for every good word and work,
I had only taken my seat a short time, when the spirit of supplication was poured forth,
to beseech the Lord on high, that in his own time,
the blood of the martyrs which had been shed in that place,
might prove as the seed of the kingdom; that the children then unborn,
might become acquainted with the pure and holy principle of grace and truth,
which cometh by Jesus Christ; for the support of which,
his faithful servants loved not their lives unto death.
A great solemnity appeared over the meeting; and after a little pause,
the public clock struck twelve, when one of the great men went out,
but in a very quiet manner: and in a short time the meeting broke up.

S+++.+++ Parkman came, and took me by the hand in a very affectionate manner,
saying very gravely: "`You have indeed manifested,
that 'With the word of a King there is power,' or you could not have been supported;
for you were just an hour and a half on your feet, before you offered the prayer to God;
and that he may prosper you in every future work and service, is my sincere desire.`"
I felt then like a worm; and could hardly tell what answer to make,
more than just to acknowledge his kind attention.
Many tender persons near the door of the meeting-house,
offered grateful acknowledgements to the blessed Author of all good,
that they had had the opportunity of being at meeting;
expressing a hope they should not soon forget it.
In the afternoon we journeyed forward; and next day got safely back to New Bedford.

My feelings now began to be awakened more and more, to look towards my native land;
not that I felt a full clearance in some places; but having done what I could,
it felt best to pack up the chest which contained the accommodations for a voyage,
and to settle such goods as were to be left behind, etc.;
that if increasing liberty should be obtained,
and way open to take shipping from some distant port, I might have them in readiness;
though as before, it seemed safest for me to say little about it,
till it became needful to request a certificate.

About the latter end of third month,
taking a near and affecting leave of my beloved friends there,
one of them accompanied my companion and self to New York,
by water about two hundred miles.
We had a pretty favourable passage for the time of year,
and were as usual very kindly received by our friends John and Catharine Murray.
Having a prospect of attending some meetings on Long Island,
and a quarterly meeting at Purchase, my faith was greatly tried,
through a permitted accident.

Going into a friend's house in New York, a plank broke under me,
and caused a severe wound on the shin bone, which gave me great pain;
but not feeling liberty in spirit to omit these meetings,
our dear friends J. and C. Murray, with worthy Thomas Dobson,
father of Lindley Murray's wife, accompanied us to Long Island,
when being clear of meetings there,
the former Friends went with us to the quarterly meeting at Purchase;
and though I travelled along with great difficulty,
my mind feeling a peaceful acquittance, I was mercifully enabled to move forward.

When about to leave New York,
I felt so nearly and tenderly affected towards Friends there,
that a secret impression attended me it might be the farewell opportunity;
which proving the case, my way opened, under the influence of the same cementing love,
to salute their women's yearly meeting, which began about the time of my embarkation,
with an epistle; which a Friend was commissioned to inform me was so acceptable,
that copies were circulated to the quarterly meetings.

Journeying forward, taking some meetings in our way,
we were met at Frank ford by our valued friends James Pemberton, and Elizabeth Foulke.
The quarterly meeting coming on at Philadelphia, I was very desirous to attend it,
though with considerable difficulty; yet my mind being relieved thereby,
I was favoured with quietude to remain under the hospitable
roof of my dear friends James and Phebe Pemberton.

During this time of confinement, I had opportunity steadily to look homewards,
and hearing of a vessel called the Rose, of which the captain, Caleb Hathaway,
was in part owner, likely to sail for Liverpool in about three weeks,
I felt quite easy to have my passage taken in her;
though divers of my kind friends thought it was running a risk
for me to go to sea before the wound in my limb was healed,
and I a stranger to all on board.
Before my departure, my endeared friend Rebecca Wright, and two precious young women,
came to take leave, and stopped two nights with me.

On the morning of my embarkation, many Friends coming in,
a farewell religious opportunity opened,
and our separation was attended with such tenderness and contrition,
as was humbling beyond the power of expression.
After which my beloved friends Phebe Pemberton and Elizabeth Foulke, with divers others,
accompanied me to the ship: three of whom staid two nights with me on board,
returning with the pilot.

Here may be inserted an extract of a letter from Rebecca Jones,
written on the occasion of Martha Routh's return home.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Fifth month 29th, 1805.

[.salutation]
My dearly beloved friend and sister Martha Routh!

Feeling my heart this morning renewedly bound to thee,
in the precious fellowship of the gospel,
in the afflictions whereof I have also often been thy companion,
I have called for pen and ink to salute thee on board the Rose; and perhaps it may,
soon after thy arrival on thy own shore, be put into thy hand.

My feelings on parting with thee at J. Pemberton's last seventh-day,
amidst such a concourse of thy friends, were indescribable; fully believing that,
though we may never more meet in mutability,
our spirits will not be separated by distance, either of time or space.
I don't dare to say that thou wilt never see America again; that and all future events,
I desire to leave to thy blessed Master, who hath often made a way for thee,
even where thou couldst see no way: and He will not forsake thee,
nor suffer thee to become desolate: "`Because he hath set his love upon me,
therefore will I deliver him; I will set him on high, because he hath known my name:
he shall call upon me and I will answer him,
etc. etc.`" (read 91st Psalm.) This gracious promise, so replete with mercy and goodness,
springs sweetly in my remembrance, as a portion especially designed for thy inheritance,
now after thy retreat from our laborious field, wherein thou hast not fainted.

Well, my dear friend, count it no strange thing if thy faith and patience be again proved.
Thou knowest too well the danger of pleasant things,
to look for or desire them further than in the will of Him,
"`who doeth all things well;`" and who hath, in the promise alluded to,
given thee the fullest assurance of his care and protection,
through thy painful pilgrimage.
The "`Alpha`" indeed,
will also reward thy unwearied endeavours to
promote His blessed cause and testimony on earth,
with a peaceful admission among His faithful servants,
when thy tribulations and labours are over:
and be thy ever blessed "`Omega,`" thy "`evening song.`"

--

I was now left in the Rose entirely with strangers,
who were very kind and civil in their way;
but I felt the trial so great of having no member of our Society on board,
that I thought even a lamb out of our own flock, would have been a precious companion;
yet I was mercifully preserved in quietude, and my wound gradually healed.
I found captain Hathaway a serious man, much inclined to look towards Friends;
and when with me he spoke and acted like one;
but he was then too weak to take up the cross when in company with others,
though he has since become a member of our religious Society.

I suffered while at sea as heretofore, from sickness,
yet not so heavily as in former voyages,
and in about six weeks was favoured to land safely at Liverpool.
