== Chapter XIII.

[.chapter-synopsis]
* Her further travels
* Her last illness and decease
* The Testimony of Hardshaw East monthly meeting concerning her.

Towards the close of the year 1808,
Martha Routh was visited with a painful cough and affection of the lungs,
which confined her to the house, and mostly to her bed for many weeks.
Under this affliction, it appears, she was favoured with a degree of quietude,
in which she could feelingly adopt the acknowledgement
of having been an unprofitable servant,
in the cause of righteousness.

She had had a previous prospect of attending the half-year's meeting for Wales,
held at Carmarthen, and the quarterly meeting for Bristol and Somerset,
etc. and she was favoured to recover her strength,
in time to obtain a certificate from her monthly meeting, and accomplish the service.
Of the half-year's meeting she remarks:
"`The number of Friends belonging to the principality was small,
but divers from England were there,
and the united little band was mercifully owned
with the descendings of the dew of heaven.`"

In 1809, she accomplished her last journey with a certificate,
by attending the four northern quarterly meetings as they fell in course,
and taking such other meetings as could be visited by the way.
On this occasion she was accompanied by her friend Mary Cockbain,
being herself in so delicate a state of health,
as to be obliged frequently to sit up several hours in the night,
to relieve the oppression of the lungs.
She attended meetings at Preston, Kendal, Cockermouth, Whitehaven, Wigton, Newcastle,
Darlington, Colthouse, Yealand, and Lancaster, some of them large public gatherings,
a number of meetings for discipline being also included.
"`On returning; home,`" she writes,
"`I was led to take a secret survey of the continued dealings of Divine kindness,
in thus furnishing me with a renewal of strength, to labour in His vineyard;
and fervent desires were raised to bless His holy name for ever.`"

After mentioning circumstances connected with the decease of her friend Sarah Stephenson,
which happened in America,
while they were both engaged on that continent in religious service,
though at a considerable distance from each other,
Martha Routh concludes her Journal (in 1814) as follows:
"`And I am now often ready to say on my own account;
Lord! now let thy poor servant also depart in peace; for mine eyes,
through thy adorable mercy, have seen thy salvation.`"

The account of her illness and decease, are comprised in the following testimony.

[.embedded-content-document.testimony]
--

[.blurb]
=== Testimony from the monthly meeting of Hardshaw East, concerning Martha Routh, deceased.

Our beloved friend Martha Routh was born at Stourbridge, in Worcestershire,
the 26th of fourth month, 1743, O. S. Her parents Henry and Jane Winter,
were steady religious Friends, from whom she had the advantage of a guarded education;
and through the merciful visitations of our Heavenly Father's love,
religious impressions were early made upon her tender mind.
As she advanced in years, the same Divine power followed her;
by which she was preserved from many of the evils which abound in the world;
and as she submitted to the further discoveries of the
Divine principle of light and grace in her own heart,
she was made an experimental witness of its cleansing and sanctifying operation.

About the seventeenth year of her age, with the approbation of her father,
her surviving parent, she removed td Nottingham;
where first as an assistant and afterwards as principal,
in a boarding school for Friends' children,
she manifested much concern and watchful care
for their preservation and religious improvement.

She had, for several years,
been impressed with a view of being called to the work of the ministry;
and in the thirtieth year of her age, she first appeared in that service.
In the year 1775, in company with that valuable minister of the gospel, Ruth Fallows,
she visited the meetings of Friends in some of the northern counties, and Scotland.
In the following year, she was married to Richard Routh, of Manchester,
and became a member of that meeting.

After her settlement there, with the concurrence of Friends,
she visited at different times, the meetings of Friends in this nation, Scotland,
and Ireland, also those in the United States of North America;
labouring diligently in that country for three years; and on her return,
brought satisfactory certificates of her services there.

When at home, she was a diligent attender of meetings for worship and discipline;
and was, therein, frequently and fervently engaged,
to labour for the promotion of truth and righteousness.

Indeed, this our beloved friend,
was eminently devoted to discharge whatever she believed to be required at her hands,
whether at home or abroad.
Unwearied in promoting the cause of Truth,
a good example of plainness and Christian moderation in her manner of living,
diligent in visiting the widow, the fatherless, and the afflicted,
whether in body or mind; with whom she was a sincere sympathizer, having often, to such,
to communicate a word of comfort; also according to her ability,
she extended pecuniary assistance to those who were in need.

During the winter preceding her decease, her bodily strength was on the decline;
yet she continued to be diligent in attending meetings.

In the fifth month she left home to attend the yearly meeting in London;
and was favoured to perform the journey without much apparent fatigue.
Soon after her arrival there she became unwell,
but was able to attend most of the sittings of the yearly meeting.
Her illness increasing, she was confined at the house of our friend Simon Bailey,
in London.

During the time of her confinement, which was about seven weeks,
we are informed that she did not communicate much,
but sufficient to evince that her mind was centred on the Rock of ages;
though at seasons under great conflict.
Her utterance was very feeble and broken,
so that it was difficult to preserve the connection in what she expressed;
yet in substance it was strong and lively.
To a Friend, she said her mind was fast anchored in the Beloved of souls;
and at another time said:
"`I want my fellow pilgrims to know that there
is a rest prepared for the people of God.`"

Alluding to her many and close provings by sea and land, she rejoicingly acknowledged,
that she witnessed a state comparable to a morning without clouds.
At another time she said: "`I have known many plunges.
I think the end cannot be far off.`"
And the repeated solemn request to those about her was:
"`Crave the release of my spirit in the Divine will, and not otherwise.`"

Her departure was scarcely perceptible;
a short time previous to which there was a sweetness on her countenance,
and a prevailing solemnity, which was a support in that awful season, to those present;
and we have no doubt that she is entered into that rest prepared for the righteous.

She departed this life, the 18th of the seventh month, 1817,
at the house of Simon Bailey aforesaid;
and was interred in Friends' burial ground at Bunhill Fields, the 25th of the same,
after a solemn meeting at Devonshire-House; aged seventy-four,
and a minister near forty-five years.

[.signed-section-closing]
Given forth at our monthly meeting of Hardshaw East, held at Manchester, the 27th of the eleventh month, 1817.

--
